### ISSUE TITLE
Broken escaping in pattern for uris

### ISSUE THREAD

**Issue by rweyand** [networknt/json-schema-validator#1]
The escaping for whitespaces in the uri-pattern is wrong which leads to uris containing an "s" not verifying.

**Comment by stevehu** [comment]
@rweyand Thanks a lot for your help. I was so lucky that never got any url with "s":)  I have merged the pull request and released a new version [0.1.2](https://github.com/networknt/json-schema-validator/releases/tag/0.1.2)
