### ISSUE TITLE
Additional i18n language(spanish) support related (#847)

### ISSUE THREAD

**Issue by channaveer1** [networknt/json-schema-validator#1019]
Hi @stevehu i have new i18n language i.e spanish its urgent for us its in production. can you please provide the access .

**Comment by channaveer1** [comment]
Hi @networknt/json-schema-validator Please do the needful at the earliest

**Comment by stevehu** [comment]
@channaveer1 What do you need? Do you need to provide a PR? or do you need a new release? Or do you need someone to implement the Spanish i18n?

**Comment by channaveer1** [comment]
I need to provide PR. i already created spanish i18n i have the code with me.

**Comment by stevehu** [comment]
Then you need to fork the repo, and update the code and issue a PR. You don't need any permission to do so.

**Comment by channaveer1** [comment]
@stevehu I have issued the PR please check and let me know please. 

https://github.com/networknt/json-schema-validator/pull/1021

**Comment by channaveer1** [comment]
Please let me know why pipeline is failing for java 8 and if possible please ping me the solution

**Comment by justin-tay** [comment]
Note that you can easily add support for additional languages by just bundling the relevant properties files with your application as they will be loaded from the classpath. No modifications to the library is actually required.

**Comment by stevehu** [comment]
Close this issue as it is duplicated with https://github.com/networknt/json-schema-validator/issues/1025
