### ISSUE TITLE
Parsing failure of the response, when the request failed with a schema validation

### ISSUE THREAD

**Issue by ddobrin** [networknt/json-schema-validator#102]
When a request contains an incorrect "date" type, matching the exact pattern:
^\d{4}-(?:0[0-9]{1}|1[0-2]{1})-(0?[1-9]|[12][0-9]|3[01])$

the response 
would return the correct status:
{ "error" : {"statusCode":400,"code":"ERR11004","message":"VALIDATOR_SCHEMA","description":"Schema Validation Error - $.match.core.person.demographics.dateOfBirth: does not match the date pattern ^\d{4}-(?:0[0-9]{1}|1[0-2]{1})-(0?[1-9]|[12][0-9]|3[01])$","severity":"ERROR"} }

Format is correct and done as per:
https://tools.ietf.org/html/rfc3339#section-5.6

The client will parse the response and encounter a parsing exception, due to the escape character in the pattern: ...^\d{4}... 

The issue can be resolved in the encoding, if the response is changed to: ...^\\d{4}..."

There are 2 options, based on the desire to offer more or less details:

1. Return only a validation error and indicate the field which failed, without returning the pattern. Swagger/OpenAPI specs can document the pattern in the spec itself
2. address the return to ensure that it passes parsing

**Comment by stevehu** [comment]
@ddobrin Is #114 address this issue?
