### ISSUE TITLE
V1.4.0 ValidatorTypeCode.getKeywords(SpecVersion.VersionFlag.V201909) has missing keywords

### ISSUE THREAD

**Issue by spaukner** [networknt/json-schema-validator#1031]
before the refactorings for 1.4.0 version the  `ValidatorTypeCode.getKeywords(SpecVersion.VersionFlag.V201909)` had a size of 44 entries, now it only has 5 entries.
for eg `ValidatorTypeCode.ALL_OF` has a version code of VersionCode.MaxV7 but should still be valid at V201909 

there is also a issue on the docs https://github.com/networknt/json-schema-validator/blob/master/doc/validators.md#custom-validators
where it states `.formats(BUILTIN_FORMATS)` but it should now be ` .formats(Formats.DEFAULT)`

**Comment by justin-tay** [comment]
1.4.0 adds support for vocabularies. As such the majority of the keywords for 2019-09 and 2012-12 have been moved into their respective vocabularies.

If want you want is to modify an existing meta schema

```java
JsonMetaSchema metaSchema = JsonMetaSchema.builder(JsonMetaSchema.getV201909()).keyword(new IsMandatoryKeyword())).build();
```
