### ISSUE TITLE
Add an option to toggle debug message

### ISSUE THREAD

**Issue by thisisfel1x** [networknt/json-schema-validator#1035]
Our console is currently being spammed with the debug message from the `BaseJsonValidator`. It would be great if you could set a boolean to turn off this message, as we log at debug level ourselves

**Comment by stevehu** [comment]
I assume you set the logging level at the root logger. So all packages are logging at the same level. I recommend adding custom loggers to set the logging level at the package level. Then you can set debug on your code.
