### ISSUE TITLE
EmailValidator limits the user length to be <= 64

### ISSUE THREAD

**Issue by sangharshgautam** [networknt/json-schema-validator#1040]
Hi,

I see that the [EmailValidator](https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/org/apache/commons/validator/routines/EmailValidator.java?plain=1#L52) is limiting the user length in an email to be less than or equal to 64 [Ref](https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/org/apache/commons/validator/routines/EmailValidator.java?plain=1#L224-230),

I was wondering if there is a reference to any standard being used here.

The [RFC 4.1.2](https://datatracker.ietf.org/doc/html/rfc5321#section-4.1.2) listed on on https://json-schema.org/understanding-json-schema/reference/string#built-in-formats)
does not suggest any such limitation. 

Please can you advice as this is being reported as a  bug in our application which uses json-schema-validator library,

Best regards,
Sangharsh

![image](https://github.com/networknt/json-schema-validator/assets/4318051/9b6294ac-0a22-426c-8b75-5ec85014a107)

**Comment by stevehu** [comment]
I think it is implemented based on common sense. I haven't seen any email username longer than 64, do you have any use case that deals with longer email? If there is a valid use case, we can adjust the validation rule. Thanks.

**Comment by justin-tay** [comment]
RFC 5321 in section [4.5.3.1.1](https://datatracker.ietf.org/doc/html/rfc5321#section-4.5.3.1.1) 

The maximum total length of a user name or other local-part is 64 octets.

**Comment by sangharshgautam** [comment]
@stevehu  @justin-tay  Thanks for your responses
