### ISSUE TITLE
v0.1.24 error on array union type

### ISSUE THREAD

**Issue by 2beers** [networknt/json-schema-validator#108]
This worked on 0.1.23, but it shows the json is not valid in 0.1.24
schema
```
{
	"type": "object",
	"properties": {
		"vars": {
			"type": "array",
			"items": {
				"anyOf": [
					{
						"type": [
							"string",
							"number",
							"boolean"
						]
					}
				]
			}
		}
	},
	"required": [
		"vars"
	]
}
```

json
`{"vars":[232]}`

error:
`$.vars[0]: should be valid to any of the schemas [union];`

Is this a bug, or am I doing something wrong?

**Comment by stevehu** [comment]
@2beers It looks like a bug introduced in the latest release. @nitin456 you are the master of anyOf and I am wondering if you could put this into the test case in your pull request? There are a lot of PRs in other repositories and I am still trying to catch up. Thanks @2beers for bringing this up.

**Comment by nitin456** [comment]
@stevehu Unfortunately, there was no test case around union types. I missed this :(.
I have fixed this in latest PR https://github.com/networknt/json-schema-validator/pull/107.

**Comment by stevehu** [comment]
Excellent! Thanks a lot for your help.

**Comment by stevehu** [comment]
@2beers Could you please confirm if this issue is resolved in the latest release? Thanks.

**Comment by 2beers** [comment]
@stevehu Yes. tested on v 0.1.26 and it's working fine.
Thanks

**Comment by stevehu** [comment]
Thanks for the confirmation.
