### ISSUE TITLE
Possible performance improvement: JsonNodePath.hashCode()

### ISSUE THREAD

**Issue by txshtkckr** [networknt/json-schema-validator#1082]
While profiling the validator locally, I found that a non-trivial amount of time was spent calculating hash codes for JsonNodePath objects. This is comparatively expensive for longer paths because it has to recurse the linked list of parents back to the root, incorporating all of their values at each step. One way to improve this is to adopt the same space/time trade-off that the String class uses, which is to cache non-`0` hash values in a non-`volatile` field to optimistically skip recalculating what should be a stable value. In the `String` class, we see that pattern done like this:

```
    private int hash; // Default to 0

...

    public int hashCode() {
        int h = hash;
        if (h == 0 && value.length > 0) {
            hash = h = isLatin1() ? StringLatin1.hashCode(value)
                                  : StringUTF16.hashCode(value);
        }
        return h;
    }
```

This is thread-safe in spite of the variable not being marked `volatile` because the value is calculated deterministically from immutable state. If we are unlucky and the `0` value is seen due to the unsafe publishing of the calculated value, we just pay the price of recalculating it, a penalty which will typically be seen at most once per thread and worthwhile to skip `volatile` access. For `JsonNodePath`, the equivalent code looks like this:

```
    @Override
    public int hashCode() {
        int h = hash;
        if (h == 0) {
            h = Objects.hash(parent, pathSegment, pathSegmentIndex, type);
            hash = h;
        }
        return h;
    }
```

Note: Including the `parent != null` check is possible and probably okay. I didn't do it because it would change the current hash value of a root path, which currently depends on `type`, to `0` for all root paths regardless of `type`.

**Comment by txshtkckr** [comment]
<img width="1090" alt="Screenshot 2024-07-03 at 11 09 00" src="https://github.com/networknt/json-schema-validator/assets/877763/e5add173-de7e-4cea-a0e5-f6bace32dd6e">

JProfiler "Hot Spots" analysis showing it taking 50% of the CPU time in the test I ran.

**Comment by txshtkckr** [comment]
Another snapshot taken with that change in place. Hashing cost drops dramatically:

<img width="1157" alt="Screenshot 2024-07-03 at 11 24 12" src="https://github.com/networknt/json-schema-validator/assets/877763/e8d21d1e-1e18-4fcc-809f-d81ed47fdb3f">

**Comment by justin-tay** [comment]
Thanks for reporting the issue, analysis and fix.
