### ISSUE TITLE
`oneOf` for empty array. 

### ISSUE THREAD

**Issue by juancki** [networknt/json-schema-validator#1098]
First of all thanks for your great work.

I was bumping from the version 1.0.69 to 1.5.1 and found that I'm getting the following errors in my tests.

Error:
```
$: must be valid to one and only one schema, but 0 are valid
```

```json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "$id": "https://example.com/example.schema.json",
  "title": "Flink-collection-sdk JsonDocumentSerdeSchemaTest ExampleClass v1",
  "description": "pte-examples",
  "type": "object",
  "properties": {
    "integer": {
      "type": "integer"
    },
    "str": {
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": [],
  "oneOf": []
}
```

Payload:
```json
{"integer":1,"str":""}
```

When I remove the `oneOf` field completely I'm no longer getting errors.

This change was introduced around version 1.0.80 - 1.081.

1. Is this the expected behavior for an empty array of `oneOf`?

**Comment by justin-tay** [comment]
The [specification](https://json-schema.org/draft/2020-12/json-schema-core#section-10.2.1.3) says

```
This keyword's value MUST be a non-empty array. Each item of the array MUST be a valid JSON Schema.
```
