### ISSUE TITLE
Validation Error when using OneOf in OpenAPI specs

### ISSUE THREAD

**Issue by ddobrin** [networknt/json-schema-validator#110]
The OneOf Validator iterates through the validators for each choice in OneOf and validates.
When it encounters the second "valid" schema element, it returns a validation error:

{ "error" : {"statusCode":400,"code":"ERR11004","message":"VALIDATOR_SCHEMA","description":"Schema Validation Error - $.search: should be valid to one and only one of the schemas ","severity":"ERROR"} }

In this case, the matching element was the 8th out of 11th, however the code analyzed them one by one and failed in the second one already, where only the 8th is a true match.

The issue is in the PropertiesValidator, where it tries to find an entry by a key and does not find it.
It treats the "not found" as normal, instead of issuing an error and letting the OneOf Validator handle it gracefully (in this ignore it)
...
            JsonNode propertyNode = node.get(entry.getKey());

            if (propertyNode != null) {
                errors.addAll(propertySchema.validate(propertyNode, rootNode, at + "." + entry.getKey()));
...

Proposed resolution includes the issuance of an error when property node does not match and letting the caller in the recursive chain handle it.

It must be properly validated and ascertained that there are no side-effects.

It is a showstopper for a number of APIs at a client site.

**Comment by ddobrin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [json-schema-validator: fixed #110 Validation Error when using OneOf in OpenAPI specs](https://trello.com/c/a0OqlzAW/50-json-schema-validator-fixed-110-validation-error-when-using-oneof-in-openapi-specs)

**Comment by stevehu** [comment]
From the OpenAPI 3.0 specification document, oneOf – validates the value against exactly one of the subschemas. If you have two or more subschemas valid, then an error should be thrown.
