### ISSUE TITLE
Unable to validate all elements of the array using 2020-12 Json schema

### ISSUE THREAD

**Issue by Ashish7812** [networknt/json-schema-validator#1101]
I have the following input
```
[
    {
      "path": "",
      "redirect": ""
    },
    {
      "path": "/path1",
      "redirect": "/path1/PRSSO"
    },
    {
      "path": "/wildcard*",
      "redirect": "/web/wildcardpath"
    }
  ]
```

and the following schema

```
{
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "title": "Path and Redirect path schema.",
      "type": "array",
      "prefixItems": [
        {
           "$schema": "https://json-schema.org/draft/2020-12/schema",
            "title": "Only redirect path schema definition.",
            "type": "object",
            "properties": {
              "path": {
                "type": "string",
                "maxLength": 0
              },
              "redirect": {
                "type": "string",
                "maxLength": 0
              }
            },
            "required": [
              "path",
              "redirect"
            ]
        }
      ]
    }

```
I am initializing the JsonSchema object like below

```
JsonSchemaFactory factory = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V202012,
                builder -> builder.jsonNodeReader(JsonNodeReader.builder().locationAware().build()));
SchemaValidatorsConfig config = SchemaValidatorsConfig.builder().build();
JsonSchema schemaObj = factory.getSchema(schemaContent, InputFormat.JSON, config);

schemaObj.validate(inputValue, InputFormat.JSON,
                executionContext -> {
                    executionContext.getExecutionConfig().setFormatAssertionsEnabled(true);
                });
```

The above example only validates the first element in the array and notifies that the validation is successful and no error is present. It does not validate the rest of the two elements.

Am I doing something wrong? Would someone be able to guide me?

**Comment by justin-tay** [comment]
The [`prefixItems`](https://json-schema.org/understanding-json-schema/reference/array#tupleValidation) keyword is used for tuple validation. The keyword you are looking for is [`items`](https://json-schema.org/understanding-json-schema/reference/array#items).

**Comment by Ashish7812** [comment]
I am using 2020-12 schema and in this schema we can not use **items** we need to use **prefixItems**.
Based on this https://json-schema.org/draft/2020-12/release-notes **items** has changed to **prefixItems**.

When I use items it throws an error. 
java.lang.IllegalArgumentException: The value of 'items' MUST be a valid JSON Schema.

**Comment by justin-tay** [comment]
The `items` keyword used to perform tuple validation and is now `prefixItems` but you already stated that you don't want tuple validation so you don't want `prefixItems`. The `items` keyword accepts a schema not an array of schemas which is why the error message says that the value of `items` must be a valid JSON schema instead of an array of schemas.

**Comment by Ashish7812** [comment]
Thanks @justin-tay  I found the root cause and after updating the schema to 

```
{
   "$schema":"https://json-schema.org/draft/2020-12/schema",
   "title":"Path and Redirect path schema.",
   "type":"array",
   "items":
      {
         "$schema":"https://json-schema.org/draft/2020-12/schema",
         "title":"Only redirect path schema definition.",
         "type":"object",
         "properties":{
            "path":{
               "type":"string",
               "maxLength":0
            },
            "redirect":{
               "type":"string",
               "maxLength":0
            }
         },
         "required":[
            "path",
            "redirect"
         ]
      }  
}
```

I can validate all the items present in the following data

```
 [
    {
      "path": "",
      "redirect": ""
    },
    {
      "path": "/prweb",
      "redirect": "/prweb/PRSSO"
    },
    {
      "path": "/wildcard*",
      "redirect": "/prweb/wildcardpath"
    }
 ]
```
