### ISSUE TITLE
"Unknown keyword exclusiveMinimun" when validating an OpenAPI 3.0 document

### ISSUE THREAD

**Issue by sonallux** [networknt/json-schema-validator#1119]
I am currently trying to validate an OpenAPI 3.0 document using the `json-schema-validator` library and I am getting the following warning when creating the `JsonSchema` object:

```
[main] WARN com.networknt.schema.UnknownKeywordFactory - Unknown keyword exclusiveMinimum - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword or if it should generate annotations AnnotationKeyword
```

I am using this code to create the `JsonSchema` object:

```java
return JsonSchemaFactory
    .getInstance(SpecVersion.VersionFlag.V4)
    .getSchema(SchemaLocation.of("https://spec.openapis.org/oas/3.0/schema/latest"));
```

What is wrong with this and why am I getting the message printed to the console?

**Comment by jkosternl** [comment]
Which version of the library did you use @sonallux? Please always specify that in a question. 
In v.1.5.2 that keyword was changed a bit in OpenAPI 3.0, see #1114 
Make sure you are using it in the right way. 
You can also check `src/test/java/com/networknt/schema/oas/OpenApi30Test.java` as an example.

**Comment by sonallux** [comment]
@jkosternl I am using the v1.5.2. But the Issue is also present in the recently released v1.5.3.

The examples in `src/test/java/com/networknt/schema/oas/OpenApi30Test.java` are different to the use case I have. I want to validate a complete OpenAPI 3.0 definition file against the official OpenAPI 3.0 schema.

Here is a more complete example:

```java
@Test
void testOpenApiValidation() throws Exception {
    var schema = JsonSchemaFactory
        .getInstance(VersionFlag.V4)
        .getSchema(SchemaLocation.of("https://raw.githubusercontent.com/OAI/OpenAPI-Specification/refs/heads/main/schemas/v3.0/schema.yaml"));

    var result = schema.validate(Files.readString(Path.of("petstore.yaml")), InputFormat.YAML);

    assertEquals(0, result.size());
}
```

**Comment by stevehu** [comment]
You cannot use v4 for OpenAPI 3.0. Try the latest version and let us know if it works.

**Comment by sonallux** [comment]
> You cannot use v4 for OpenAPI 3.0. Try the latest version and let us know if it works.

@stevehu thanks for your reply. But I do not understand it.

The OpenAPI 3.0 Schema file is explicitly mentioning it is using JsonSchema v4 [here](https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.0/schema.yaml#L2). Also the `SpecVersionDetector` is is reporting v4 for the OpenAPI 3.0 Schema.
