### ISSUE TITLE
pom.xml scm url URI is invalid

### ISSUE THREAD

**Issue by rpoet-jh** [networknt/json-schema-validator#1131]
The pom value for `scm:url` is currently `https://github.com:networknt/json-schema-validator.git`.  I think it should be `https://github.com/networknt/json-schema-validator.git` (`/` instead of `:` after github.com).  Probably check the `scm:connection` and `scm:developerConnection` as well.

I came across this when validating an SBOM that has `json-schema-validator` as a dependency, validation was failing on the `vcs:url` .

**Comment by stevehu** [comment]
This is very interesting. I am using the current format for all the repos, and there is no issue at all. Here is the result of scm:validate. 

```
[INFO] connectionUrl scm connection string is valid.
[INFO] project.scm.connection scm connection string is valid.
[INFO] project.scm.developerConnection scm connection string is valid.

```
