### ISSUE TITLE
Is the RE matching error data correct showing a matching error because there is an escape character recognition error?

### ISSUE THREAD

**Issue by zhengshengjun1125** [networknt/json-schema-validator#1136]
data： container::fi9v3f,S-Easy Returns\nCowl Neck Solid Glitter Ruffle Hem Maxi Dress.scmId::P-113849522
<img width="1105" alt="image" src="https://github.com/user-attachments/assets/746b8e7e-e4aa-4815-bd13-3ef46ad634ce">

please fix it? tk u

**Comment by stevehu** [comment]
I think the \n is the problem. I would suggest testing your regex and data outside of the schema validator with pure java test cases. Thanks.

**Comment by zhengshengjun1125** [comment]
> I think the \n is the problem. I would suggest testing your regex and data outside of the schema validator with pure java test cases. Thanks.

thank you， i reslove it by other regex about 1 hour ago ，replece the regex .* to [\s\S]
