### ISSUE TITLE
when I set type:["string",null],this custom errorMessage is invalid

### ISSUE THREAD

**Issue by MrGengLei** [networknt/json-schema-validator#1137]
oneOf:errorMessage is valid,but type:["string",null] errorMessage is invalid
{
  "type": "object",
  "properties": {
    "keyword": {
      "oneOf": [
        { "type": "string" },
        { "type": "null" }
      ],
      "errorMessage": {
        "oneOf": "keyword必须为字符串"
      },
      "title": "关键字"
    },
    "keyword1": {
      "type": ["string","null"],
      "errorMessage": {
        "type": "关键字1必须为字符串"
      },
      "title": "关键字"
    }

  }}

**Comment by stevehu** [comment]
I don't think all keywords have customized errorMessage support. For some keywords, the error message is standard and it does support translation into Chinese. Thanks.
