### ISSUE TITLE
LocalDateTime validation error

### ISSUE THREAD

**Issue by chenyan71** [networknt/json-schema-validator#114]
validation error on java.time.LocalDateTime:

for example:
    "lastUpdated": "2018-11-15T21:08:59",

validation error:
{"statusCode":400,"code":"ERR11004","message":"VALIDATOR_SCHEMA","description":"Schema Validation Error - $.lastUpdated: does not match the date-time pattern ^\\d{4}-(?:0[0-9]{1}|1[0-2]{1})-(0?[1-9]|[12][0-9]|3[01])[tT ]\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?([zZ]|[+-]\\d{2}:\\d{2})$","severity":"ERROR"}

change it to:     "lastUpdated": "2018-11-15T21:08:59Z" will pass the validation.

But when we load from attachment the value change back: "lastUpdated": "2018-11-15T21:08:59"

**Comment by ddobrin** [comment]
@chenyan71 : Check also issue #102

**Comment by stevehu** [comment]
JSON is derived from Javascript and it has a unique date time format. We had the same issue in react-schema-form validation and it has been discussed for a long time and I think everyone agreed that we need to stick with the JSON format instead of ISO format. 

https://stackoverflow.com/questions/10286204/the-right-json-date-format

**Comment by chenyan71** [comment]
n the code-gen, if the field define the format as date-type, code-gen will use LocalDateTime
if("format".equals(entryElement.getKey())) {
                                       String s = entryElement.getValue().toString();
                                       if("date-time".equals(s)) {
                                           propMap.put("type", Any.wrap("java.time.LocalDateTime"));
                                       }
But in java 8, LocalDateTime doesn't include zone info
So the generated JSON will not match the regex we defined for the schema validation

**Comment by chenyan71** [comment]
from the light-codegen, if the field define the format as date-type, light-codegen will use LocalDateTime
if("format".equals(entryElement.getKey())) {
                                       String s = entryElement.getValue().toString();
                                       if("date-time".equals(s)) {
                                           propMap.put("type", Any.wrap("java.time.LocalDateTime"));
                                       }
But in java 8, LocalDateTime doesn't include zone info
So the generated JSON will not match the regex we defined for the schema validation and will have schema validation error

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [LocalDateTime validation error](https://trello.com/c/2qkRgfDL/66-localdatetime-validation-error)

**Comment by stevehu** [comment]
Is this fix helpful? https://github.com/networknt/json-schema-validator/issues/575

**Comment by dcebotarenco** [comment]
Still no support for LocalDateTime (ISO) from java? 
Do I have to change the global Spring ObjectMapper to put the 'Z', which might affect other of my contracts? 
I use https://camel.apache.org/releases/release-3.19.0/, which uses schema validator 1.0.72 with itu:1.7.0

**Comment by stevehu** [comment]
We do support date without "Z" and here is the test case. What is your date format? 

```
         {
                "description": "an valid date-time string",
                "data": "1963-12-30T08:30:06",
                "valid": true
            },
```

**Comment by dcebotarenco** [comment]
I have the following errors:
$.createdDateTime: 2021-09-14T19:09:15 is an invalid date-time
$.lastModifiedDateTime: 2021-10-15T17:00:30 is an invalid date-time.

The string is a representation of a LocalDateTime instance.

I use the following versions as part of camel-spring-boot-starter:3.19.0:
* com.networknt:json-schema-validator:1.0.72
* com.ethlo.time:itu:1.7.0
* org.apache.camel.springboot:camel-json-validator-starter:3.19.0
* org.apache.camel.springboot:camel-spring-boot-starter:3.19.0

Method ```com.networknt.schema.DateTimeValidator#isLegalDateTime```  returns false. Where an exception is thrown in itu 1.0.72

![image](https://user-images.githubusercontent.com/1030373/212745274-2123c0d2-f4f1-489d-ae9a-d42e9c1ef745.png)

```
[com.ethlo.time.DateTime.toOffsetDatetime(DateTime.java:237), com.ethlo.time.internal.EthloITU.parseDateTime(EthloITU.java:298), com.ethlo.time.ITU.parseDateTime(ITU.java:51), com.networknt.schema.DateTimeValidator.lambda$isLegalDateTime$1(DateTimeValidator.java:65), com.networknt.schema.DateTimeValidator.tryParse(DateTimeValidator.java:79), com.networknt.schema.DateTimeValidator.isLegalDateTime(DateTimeValidator.java:63), com.networknt.schema.DateTimeValidator.validate(DateTimeValidator.java:53), com.networknt.schema.JsonSchema.validate(JsonSchema.java:279), com.networknt.schema.PropertiesValidator.validate(PropertiesValidator.java:69), com.networknt.schema.JsonSchema.validate(JsonSchema.java:279), com.networknt.schema.JsonSchema.validate(JsonSchema.java:262), org.apache.camel.component.jsonvalidator.JsonValidatorEndpoint.onExchange(JsonValidatorEndpoint.java:120), org.apache.camel.support.ProcessorEndpoint$1.process(ProcessorEndpoint.java:61), org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66), org.apache.camel.processor.SendProcessor.process(SendProcessor.java:172), org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:477), org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181), org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59), org.apache.camel.processor.Pipeline.process(Pipeline.java:175), org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392), org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:96), org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:214), org.apache.camel.impl.engine.SharedCamelInternalProcessor$1.process(SharedCamelInternalProcessor.java:111), org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83), org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:108), org.apache.camel.support.cache.DefaultProducerCache.send(DefaultProducerCache.java:199), org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:176), org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:172), org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:153), org.apache.camel.impl.engine.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:187), org.apache.camel.impl.engine.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:195), 
...
```

I think [gorestrun](https://github.com/gorestrun) is right in the above comment.
I had to downgrade the version, so the software is backwards compatible with my current data - as it was using optional 'zZ'

```
implementation('com.networknt:json-schema-validator'){
    version {
        strictly '1.0.52'
    }
    because("https://github.com/networknt/json-schema-validator/issues/114")
}
```
or do I have to append a timezone by converting a LocalDateTime to ZonedTimeDate or Instant. This is very risky and unnecessary in my case. As current system implementations use LocalDateTime as part of DTOs processed by Apache Spring Camel
https://stackoverflow.com/questions/6038136/how-do-i-parse-rfc-3339-datetimes-with-java

Tell me if you need more details. 
I am glad to help you.

**Comment by dcebotarenco** [comment]
I cannot find your example anywhere in the repository where 
```
{
        "description": "an invalid date-time string",
        "data": "1963-12-30T08:30:06",
        "valid": false
      }
```
I looked it up in draft4 and draft7.
Am I missing something? 

https://github.com/networknt/json-schema-validator/blob/416572e159d5d13bffa43a04d578fd7d384ef776/src/test/resources/draft4/optional/format/date-time.json
https://github.com/networknt/json-schema-validator/blob/1c68e2cbf4626a555edab2e603f083ca5fcdacad/src/test/resources/draft7/optional/format/date-time.json

**Comment by itatdcer** [comment]
Is there an accepted solution for this problem?

I'm having the same problem reported here. Schema: 
`{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "eventDate": {
            "type": "string",
            "format":"date-time"
        }
    }
}`

JSON: 
`{
    "eventDate": "2018-11-19T00:00:00"
}`

Results in validation error:
`$.eventDate: 2018-11-19T00:00:00 is an invalid date-time`

**Comment by fdutton** [comment]
@itatdcer JSON Schema uses the date-time definition from RFC 3339, which requires a time-zone offset. However, you can provide a custom format validator to change this behavior. See an example of how to do this here.
https://github.com/networknt/json-schema-validator/blob/e9dea3bf3b210f30caa41e1a6c23371a86bf2a01/src/test/java/com/networknt/schema/Issue784Test.java

**Comment by itatdcer** [comment]
@fdutton Thanks for your quick reply.
Yes, I figured that out, but still, it feels weird that the Jackson serializer / desserializer works with yyyy-MM-dd'T'HH:mm:ss but the validation against the schema doesn't.
Nevertheless, I've implemented, as suggested, a custom Format that solves my problem.

Thanks!

**Comment by fdutton** [comment]
@itatdcer Yes, Jackson can deserialize into a LocalDateTime but the `date-time` format maps to an OffsetDateTime not a LocalDateTime.
