### ISSUE TITLE
VersionFlag for OpenAPI 3.0 and OpenAPI 3.1

### ISSUE THREAD

**Issue by TakahikoKawasaki** [networknt/json-schema-validator#1140]
Do you plan to add new entries to the `SpecVersion.VersionFlag` enum for OpenAPI 3.0 and OpenAPI 3.1?

The `SchemaId` class have static fields, `OPENAPI_3_0` and `OPENAPI_3_1`, which correspond to OpenAPI 3.0 and OpenAPI 3.1, respectively. However, the `SpecVersion.VersionFlag` enum does not include entries corresponding to OpenAPI 3.0 and OpenAPI 3.1.

If `VersionFlag.OPENAPI_3_1` is available, I'd like to call `JsonSchemaFactory.getInstance(VersionFlag.OPENAPI_3_1)`.

**Comment by stevehu** [comment]
My understanding is that json schema version doesn't have OPENAPI_3_0 and OPENAPI_3_1 at all. Although the library can be used to verify OpenAPI specifications, it still uses one of the official json schema versions. For example 2020-12.

**Comment by TakahikoKawasaki** [comment]
Apologies, I seem to have misunderstood. I thought it was necessary to update json-schema-validator to incorporate the fix for [a certain bug](https://github.com/schemathesis/schemathesis/issues/2484) in the OpenAPI schema file. However, after changing the schema file used for validation from https://spec.openapis.org/oas/3.1/schema-base/2022-10-07 to https://spec.openapis.org/oas/3.1/schema-base/2024-11-14, the validation passed. I will close this issue.
