### ISSUE TITLE
Fail to validate numeric and Integer in TypeValidator

### ISSUE THREAD

**Issue by jiachen1120** [networknt/json-schema-validator#116]
In typeValidator

1. "+1" will not be recognized as an Integer or Numeric
2. "All decimals cannot be recognized as numeric
3. No check for the case "0.0.1"

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fail to validate numeric and Integer in TypeValidator](https://trello.com/c/uhuoka3r/79-fail-to-validate-numeric-and-integer-in-typevalidator)
