### ISSUE TITLE
Support numerals the way JSON spec defines them

### ISSUE THREAD

**Issue by kosty** [networknt/json-schema-validator#118]
Currently [`TypeValidator`](https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/TypeValidator.java#L65) has a loose mode (which is great) but [`isInteger`](https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/TypeValidator.java#L101) and [`isNumeric`](https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/TypeValidator.java#L125) do not fully comply with numeric literals defined by [JSON spec](http://json.org/). In particular the following values are not regarded as numbers by JSON (some of them are successfully validated by `TypeValidator`)

```
"01.1", "1.", ".1", "E1", "E+1", "E-1", ".E1", ".E+1", ".E-1", ".1E1", ".1E+1", ".1E-1", "+1"
```

also  the following values are all valid numbers as per spec

```
"1", "-1", "1.1", "-1.1", "0E+1", "0E-1", "0E1", "-0E+1", "-0E-1", "-0E1", "0.1E+1", "0.1E-1", "0.1E1", "-0.1E+1", "-0.1E-1", "-0.1E1", "10.1", "-10.1", "10E+1", "10E-1", "10E1", "-10E+1", "-10E-1", "-10E1", "10.1E+1", "10.1E-1", "10.1E1", "-10.1E+1", "-10.1E-1", "-10.1E1" 
```

**Note**
`+1`, `0001` is currently successfully validated by `TypeValidator` adhering to spec might introduce breaking change for some of existing users

**Comment by kosty** [comment]
@stevehu please treat this PR as a proposal/starting point. Let's figure out which direction to take it.

**Comment by stevehu** [comment]
For sure. I have already invited other members who are familiar with the project to review. We can discuss in the PR. I am glad that you have included unit tests to make the usage very clear. Thanks.

**Comment by kosty** [comment]
Just realized, this was not closed after merge. Closing
