### ISSUE TITLE
Alternate source for remote schema

### ISSUE THREAD

**Issue by rhwood** [networknt/json-schema-validator#124]
I have a need to be able to validate JSON schemas using an isolated system that cannot reach the internet. Since all schemas I need to validate include `"$schema": "http://json-schema.org/draft-04/schema#"`, this is causing a java.net.ConnectionException. Is there a way to map URLs to a local resource, so that we could have a local copy of an externally defined schema (similar to the [CatalogResolver](https://docs.oracle.com/javase/9/docs/api/javax/xml/catalog/CatalogResolver.html) for XML processing in the JRE)?

**Comment by stevehu** [comment]
If your local resource is a valid URL, then it is OK. JSON schema doesn't support local file system and we have to implement something like an extension to the spec. I remember somebody might have explored it already and gave up.

**Comment by rhwood** [comment]
Accidentally closed.

**Comment by rhwood** [comment]
Do you mind if I create a PR that allows for this outside the specification?

**Comment by stevehu** [comment]
Yes. Please.
