### ISSUE TITLE
$ref external schema references do not use URL mappings

### ISSUE THREAD

**Issue by rhwood** [networknt/json-schema-validator#134]
Although #125 introduces the ability to map external schema URLs to alternate/local URLs to avoid calls to unreachable URLs in `$schema`, external schema URLs in `$ref` do not use the mappings.

**Comment by rhwood** [comment]
I'll probably be able to create a PR to address this soon.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [$ref external schema references do not use URL mappings](https://trello.com/c/4DvlN9QR/209-ref-external-schema-references-do-not-use-url-mappings)
