### ISSUE TITLE
Maps of URLs can have performance impacts

### ISSUE THREAD

**Issue by rhwood** [networknt/json-schema-validator#136]
While incorporating the feature of URL mappings into an app, [Spotbugs](https://spotbugs.readthedocs.io/en/stable/) flagged the [inefficient use of URL in maps](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#dm-maps-and-sets-of-urls-can-be-performance-hogs-dmi-collection-of-urls).

While this is an easy fix, it does make a breaking change in the API since 1.0.5.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Maps of URLs can have performance impacts](https://trello.com/c/VGBLPFkh/210-maps-of-urls-can-have-performance-impacts)
