### ISSUE TITLE
Any plans to improve on the json schema version supported?

### ISSUE THREAD

**Issue by hktegner** [networknt/json-schema-validator#144]
Would love to see support for draft-07. I see a couple of implementation of validators already. Any plans for improvements in this area?

**Comment by stevehu** [comment]
It is planned for a long time but never got a chance to get it started. Some of the ideas are documented in https://github.com/networknt/json-schema-validator/issues/54

This library is part of the light-4j framework and it is used by a lot of users indirectly. We are adding new features very often. Some of the features are beyond schema validation and purely driven by the OpenAPI specification. If you have any particular use case that needs draft-07 feature, let's address it one by one.

**Comment by stevehu** [comment]
@hktegner We have added several v7 features recently and planning to add more. Is there any particular features you are interested in?

**Comment by stevehu** [comment]
@hktegner I have refactored the library to add support to multiple versions easily for both users and developers. Could you please review the PR https://github.com/networknt/json-schema-validator/pull/213?

**Comment by stevehu** [comment]
We are making big progress to support v6, v7, and v2019-09. Closing this issue for now.
