### ISSUE TITLE
Fails to validate MIN and MAX when number type is converted to BigInteger

### ISSUE THREAD

**Issue by BalloonWen** [networknt/json-schema-validator#147]
When parsing Json content, and convert numbers to BigInteger will cause MIN and MAX validation fail.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fails to validate MIN and MAX when number type is converted to BigInteger](https://trello.com/c/OlhgMOth/223-fails-to-validate-min-and-max-when-number-type-is-converted-to-biginteger)

**Comment by stevehu** [comment]
1.0.9 is released to resolve this issue. Thanks.
