### ISSUE TITLE
add validation for string type: uuid

### ISSUE THREAD

**Issue by chenyan71** [networknt/json-schema-validator#151]
schema:
  type:string
  minLength: 1
  format: uuid

we need add new format validation for uuid format string

**Comment by stevehu** [comment]
I found the following links and hope they are helpful. 

https://github.com/json-schema-org/json-schema-spec/issues/542

https://tools.ietf.org/html/rfc4122

https://stackoverflow.com/questions/50204588/how-to-define-uuid-property-in-json-schema-and-open-api-oas

**Comment by chenyan71** [comment]
user can use pattern to define the uuid format. But since uuid is validate format for openAPI. We should have validation for it. Added separate validator for it
