### ISSUE TITLE
Integer type validation fails for values bigger than java.lang.Long.MAX_VALUE

### ISSUE THREAD

**Issue by chuwy** [networknt/json-schema-validator#154]
Having this JSON Schema:

```
{"properties": {"int": { "type": "integer" }}}
```
And following two JSON instances:

```
{"int": 9223372036854775808 }
```

```
{"int": 9223372036854775807 }
```

Former fails with `[$.int: number found, integer expected]`, while latter is successfully validated.

Tried with 1.0.5 - 1.0.10 version of the library.

**Comment by chuwy** [comment]
Couldn't reproduce it with unit test suite. Maybe the reason was that I'm using it with Scala and convert [circe](https://github.com/circe/circe) JSON AST into Jackson.

**Comment by stevehu** [comment]
@chuwy Thanks for the confirmation that the unit tests work. Difference language handlers JSON differently and we have encountered several issues when implementing JSON schema in Java.

**Comment by chuwy** [comment]
Sorry for bothering, it was a bug in circe-jackson adapter: https://github.com/circe/circe-jackson/issues/65. Closing
