### ISSUE TITLE
Fix date-time validation

### ISSUE THREAD

**Issue by jiachen1120** [networknt/json-schema-validator#155]
Due to the wrong use of the pattern of SimpleDateFormat, the 24-hour partial time verification result is incorrect.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix date-time validation](https://trello.com/c/O8x8XcG3/244-fix-date-time-validation)

**Comment by stevehu** [comment]
1.0.12 is released and all framework references are updated.
