### ISSUE TITLE
when schema type is integer but max/min value is a float point number

### ISSUE THREAD

**Issue by BalloonWen** [networknt/json-schema-validator#160]
whenever there's a combination like:
{"type": "integer",
"maximum": 1e+32}
will validate error

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [when schema type is integer but max/min value is a float point number](https://trello.com/c/X3QwTNzO/255-when-schema-type-is-integer-but-max-min-value-is-a-float-point-number)
