### ISSUE TITLE
Integers are not validated by numeric multipleOf

### ISSUE THREAD

**Issue by chuwy** [networknt/json-schema-validator#161]
Having this JSON:

```
{"int": 1}
```

And this schema:

```
{
  "properties": {
    "int": { "multipleOf": 0.1 }
  }
}
```

I'm getting this result:

```
[{"path":"$.int","message":"$.int: must be multiple of 0.1","keyword":"multipleOf","targets":["0.1"]}]
```

While I expect it to be success.

In [specification for](https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.2.1) `multipleOf` we have:

> A numeric instance is valid only if division by this keyword's value results in an integer. 

So, I assume my expectation is valid.

**Comment by BalloonWen** [comment]
@chuwy I couldn't reproduce, what's the json-schema-validator version are you using? Or can you provide more details?
I've tested with version 1.0.14 and 1.0.8, both work.
I added this to the schema
```
  /todoItem:
    post:
      description: create a todoItem
      operationId: createTodoItem
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                int:
                  multipleOf: 0.1
```
and send a request with json:
```
{
	"int": 1
}
```
and it passes the validation
if I send a request with json:
```
{
	"int": 0.01
}
```
I'll get a result with:

> {"statusCode":400,"code":"ERR11004","message":"VALIDATOR_SCHEMA","description":"Schema Validation Error - $.int: must be multiple of 0.1","severity":"ERROR"}

**Comment by stevehu** [comment]
@chuwy Is this issue spotted in Java or Scalar? Any more details to help us to reproduce it?

**Comment by chuwy** [comment]
Hey guys,

Sorry I forgot about this ticket. I used 1.0.5 when stumbled upon it, but right now cannot reproduce it with as well with any version. This was also Scala, but the inconsistency I noticed in #154 should have been fixed, so I don't think it matters.

I'll try to dig into historical data, maybe I misrepresented something.

**Comment by stevehu** [comment]
@chuwy Thanks a lot for your confirmation.
