### ISSUE TITLE
POM file <licenses> missing SLF4J

### ISSUE THREAD

**Issue by drostowsky-tmobile** [networknt/json-schema-validator#165]
Our app includes networknt library. 

If you follow the Google instructions for generating notices for your app's open source licenses (https://developers.google.com/android/guides/opensource), you'll find slf4j MIT license is missing from the notices the build tool produces. The Google build tool looks at this project's pom.xml <licenses> element, and the only one it finds is Apache. It also needs to include at least the MIT license for slf4j, and maybe others in the dependency list (admittedly I havent reviewed them all).

https://www.slf4j.org/license.html

**Comment by stevehu** [comment]
@drostowsky-tmobile Thanks a lot for pointing out this issue. We have updated most of the repositories as some of the customers requires indemnification. One example is the NOTICE file in the repository like [light-4j NOTICE](https://github.com/networknt/light-4j/blob/master/NOTICE). Would this format be enough? If yes, I will add one to this library.

**Comment by drostowsky-tmobile** [comment]
While that'll be ok legally, but the Google build plugin still needs your pom.xml updated as well.

**Comment by stevehu** [comment]
@drostowsky-tmobile I do have a section in the pom.xml that declares the license of this library. 

```
    <licenses>
        <license>
            <name>Apache License Version 2.0</name>
            <url>http://repository.jboss.org/licenses/apache-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

```

From this document, each project should only declare its license not the dependencies. The dependencies are not part of our deliveries but only needed in users' applications. 

https://maven.apache.org/pom.html#Licenses

**Comment by drostowsky-tmobile** [comment]
Ah, got it. Thx!
