### ISSUE TITLE
Allow using URN and not just URLs

### ISSUE THREAD

**Issue by flozano** [networknt/json-schema-validator#166]
(From https://github.com/networknt/json-schema-validator/pull/141)

Right now, if we understand correctly, references to external schemas are forced to be URLs.

We'd like to extend the validator to register some well-known URNs for some internal schemas, without publishing them in a valid URL, but we don't think it's possible in a clean way with current code-base, so if we want to use this library we need to replace those URNs to URLs in a pre-processing which shouldn't be required.

**Comment by flozano** [comment]
related to https://github.com/networknt/json-schema-validator/issues/100

**Comment by stevehu** [comment]
@flozano I agree that we need to support both. For now, most users are using external references as they want to share some comment schemas between the specifications of services. Eventually, users would like to refer to some common schemas.

**Comment by flozano** [comment]
In our case, it's not so much about sharing with 3rd parties, but about our own private schemas. We have many schemas which use URNs that refer to a few well-known schemas. 

If we could use URI instead of URL it would be fixed. I could attempt to do a pull-request, but I'm afraid URL is scattered all over the code, so it'd be very big.

**Comment by stevehu** [comment]
@flozano Please give it a try. We have sufficient test cases to ensure nothing is going to break.

**Comment by stevehu** [comment]
@flozano Could you please provide several examples of URNs that are publicly accessible? Also, any documents or links that might help us to understand the requirement in your case.

**Comment by flozano** [comment]
You can see one here: 
https://api.flightstats.com/flex/airports/rest/v1/schema/json

in this example, the ref refers to a URN inside the same document, but it could be externally defined. Basically I think schema validator should not dictate what references are and how they are fetched for everyone.

By using URL you enforce the references to be URLs, by using URI you can let the "fetcher" implementator decide how to resolve those.

**Comment by flozano** [comment]
Please note that, as per https://json-schema.org/understanding-json-schema/structuring.html, $ref and $id are URIs and not URLs

**Comment by stevehu** [comment]
For people (including me) who are confused about URL, URI, and URN, please check this link 

https://stackoverflow.com/questions/176264/what-is-the-difference-between-a-uri-a-url-and-a-urn

I think we should support all of them as they do have a place in the JSON schema.

**Comment by jawaff** [comment]
I'm starting to understand what you're looking for. We already have a means for injecting a URLFetcher, but the main problem is combining the ids and $ref values together. If the ids and $refs are for a URN, then they probably just get concatenated (that's my guess). However, a URL component has some special rules (which are handled by the URL constructor).

I could make the update and allow some sort of injectable fetcher for custom schemes.

**Comment by jawaff** [comment]
There only seems to be 7 files that need updated at first glance. It looks like the URI constructor and URI#resolve method do what we need. We just need to make some sort of URIFetcher that allows custom schemes to be fetched. By default, the current URLFetcher can be used for all of the URL schemes.

**Comment by jawaff** [comment]
I've got something almost done, but I'm having problems with combining ids and $refs. The URI#resolve method doesn't work as expected for some things and broke some of the tests.

One of the failing unit tests had to do with the custom classpath: URI scheme. The id was 'classpath:/tests/relativeRefRemote.json' and the $ref was 'integer.json'. I would have expected that to be recognized as a relative path and to end up with 'classpath:/tests/integer.json'. However, the result was 'integer.json' as the combined URI.

The only builtin Java tool I've found for combining these things correctly so far has been the URL constructor. Maybe we need to allow injectable behavior for combining pieces of URIs based on the scheme. We can use the URL constructor for the URL schemes (which would include our custom classpath scheme) and expect a custom 'combiner' for other URIs.

**Comment by flozano** [comment]
wow that was fast. If you upload what you have I can try to help... as you know better the code-base, there's no point in me trying to duplicate the effort. I was still exploring how to do it. I agree using different strategies for URL-looking URIs and for non-URL-looking URIs should be doable.

**Comment by jawaff** [comment]
My computer's hard drive ended up dying on me right before I uploaded my
changes. I'm going to need a bit more time to get all of that sorted out.
I've got a solution all figured out. I just need to rewrite it.

**Comment by jawaff** [comment]
I think I got something worked out on a spare computer. I'm going to submit a pull request.

**Comment by stevehu** [comment]
@jawaff I am sorry to hear the hard drive problem. I have sent you an invite to join light-4j so that you can create a branch and constantly check in your code. I am doing the same although my hard drive is backing up daily.

**Comment by jawaff** [comment]
@stevehu Thanks for the invite. I've got a fork of this project. I could have easily checked in my changes to the fork, but I was still experimenting and didn't really want to yet. It's not a big deal. I've got everything rewritten and ready to review now. Hopefully you like my solution.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow using URN and not just URLs](https://trello.com/c/SmcDmFud/273-allow-using-urn-and-not-just-urls)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow using URN and not just URLs](https://trello.com/c/SmcDmFud/273-allow-using-urn-and-not-just-urls)

**Comment by stevehu** [comment]
@flozano I have reviewed and merged the PR @jawaff submitted. Could you please review and let us know if it covers all your scenarios. If possible, please add more test cases if you see some of the scenarios are not covered. 

@jawaff Thanks a lot for your help.

**Comment by jawaff** [comment]
@stevehu Thanks for checking out my updates so quickly. I hope I didn't miss anything in my updates.

**Comment by flozano** [comment]
This covers all our scenarios, very little glue code was needed. 

We're just ditched our own fork of the "everit" validator and already enjoying this validator.

Thanks a lot @jawaff and @stevehu !!!

**Comment by jawaff** [comment]
I messed up a bit and still need to add in a URIFactory for the 'urn'
scheme, just so you know. I was still confused until I found a spec for the
structure of URNs. However, I don't think there's a standard way to fetch a
URN's file, so a URIFetcher will still need to be injected (I'm assuming
you already got that figured out).

**Comment by jawaff** [comment]
I'm glad I could help. I really like this project. It's simple and
organized well. I almost went with everit a while back, but I didn't like
how they used their own json parser instead of Jackson or Gson.

**Comment by stevehu** [comment]
@flozano @jawaff This is a perfect scenario that we work together. Thanks a lot.

**Comment by jenschiavone** [comment]
Hello. I've been reading through various threads about supporting nested schemas and am still unable to tell if that is supported in networknt json-schema-validator. I have my schema defined locally in my project. When I write my definitions in my main schema file and reference them, everything works. But I really prefer to have my definitions in other files within the same directory. I cannot get my refs to those definitions to work though. I need to understand if I'm doing something wrong or if this capability is simply not supported by this library. If it IS supported, could you please provide a very basic example of referencing a definition in another, local file? Thanks.

**Comment by stevehu** [comment]
In the specification, local files are not supported. We do have some ways to support local files, but it is not recommended.
