### ISSUE TITLE
Create new option to set unknow json property as error

### ISSUE THREAD

**Issue by fvp** [networknt/json-schema-validator#170]
This is a request to create a new option to throw an error in case the json property is not present in the json schema. For the usecase when it is needed to validate that the user is not inputting the incorrect json by mispelling a json property. Specially for not required properties.

**Comment by stevehu** [comment]
@fvp Currently, we only ensure that required properties are presented in the JSON during the validation. Do you have any particular use case that needs to validate not required properties? As I understand, this is not the standard validation in the JSON schema. I just want to understand your use case more so that we can make the right implementation decision. I think we need to make this as configurable if this has been implemented.

**Comment by fvp** [comment]
@stevehu The usecase is: 
You have an actor manually creating a json for an API post call and let's say there is a property "field1" which is optional. If the user mispell "field1" to "fiele1" the json validator will let the request go through successfully and the optional field won't have the correct setting. I need a way to alert the user that the property is not in the json schema, therefore not valid.

For sure this feature would be a configurable option, maybe disabled by default. 

I could help on the development.

**Comment by fvp** [comment]
Hi @stevehu , what do you think about this topic?

**Comment by stevehu** [comment]
Although this is not a standard JSON validation, I am open to accepting a PR which the feature can be enabled explicitly by configuration. This to ensure that the core library still sticks to the standard but allow a certain level of customization to meet user's special use cases. Would you be able to implement this feature?

**Comment by kosty** [comment]
@fvp was just passing by and noticed the thread. would `"additionalProperties": false` work for you in this case?

**Comment by fvp** [comment]
Hi kosty, for me it is ok. I ended up with no time to work on this feature. If you end up implemented that would be great ;-)

**Comment by stevehu** [comment]
I misunderstood the question in my previous answers. I think @kosty is right. Set additionalProperties to false will prevent any additional properties. Here is another duplicated question on this topic and I have answered it on the Stackoverflow. 

https://github.com/networknt/json-schema-validator/issues/322
