### ISSUE TITLE
Jackson-databind vulnerability version update

### ISSUE THREAD

**Issue by mike-clarke1-blackrock** [networknt/json-schema-validator#182]
Jackson-databind 2.9.9 and earlier has a number of recently identified vulnerabilities:
https://www.cvedetails.com/vulnerability-list/vendor_id-15866/product_id-42991/Fasterxml-Jackson-databind.html

These have been addressed in v2.9.9.2 and higher. Please update the jackson-databind dependency to the latest version so that transitive dependency vulnerability checks do not raise warnings

**Comment by stevehu** [comment]
Pending release before this weekend. Thanks for raising it up.
