### ISSUE TITLE
SchemaValidatorsConfig not propagated

### ISSUE THREAD

**Issue by jorcasso** [networknt/json-schema-validator#187]
When loading a schema using `$ref` I have found a case where the configuration I use to instantiate the main schema is not being honored, in my case I want to set `typeLoose=false`, but it seems is not propagated.

I have taken a look to the code and I think the issue is in this line:

https://github.com/networknt/json-schema-validator/blob/20b246f7f1db151bc68b21b3ba8be71c7e7278cc/src/main/java/com/networknt/schema/JsonSchemaFactory.java#L304

A `ValidationContext` is instantiated there, but the `SchemaValidatorsConfig` passed as an argument is not used.

Please could you take a look?

**Comment by stevehu** [comment]
@jorcasso Could you please review the change? Thanks.

**Comment by jorcasso** [comment]
Thanks for the fix @stevehu. I have managed to try the library with the fix and it resolves our issue. I guess it will be included in next release, right?

**Comment by stevehu** [comment]
@jorcasso Thanks for the review and confirmation. Yes. It will be in the next release. We still have several pending issues to merge before the release but it will be soon.
