### ISSUE TITLE
couldnot validate the email format in json schema

### ISSUE THREAD

**Issue by ctopCanada** [networknt/json-schema-validator#188]
in my schema, there is one field named emailAddress, and defined as below

"emailAddress": {
					"maxLength": 80,
					"format": "email",
					"type": "string"
				},

if we use networkNT to validate the string gmail@@gmail.com, it will not throw validation exception at all.

**Comment by stevehu** [comment]
@ctopCanada Thanks a lot for your suggestions. I have made some changes and add your use case to the test. Please review and let us know if you have questions.
