### ISSUE TITLE
Undertow Dependency in pom.xml

### ISSUE THREAD

**Issue by o4oxide** [networknt/json-schema-validator#19]
Hi,

Great job. I was taking a look at the library but noticed the undertow dependency in the pom and didn't see anywhere in the code where it is being used. Also could there be some more documentations even if it is javadoc so one can tell easily and quickly what is going on where.

Thanks for this.

**Comment by stevehu** [comment]
Thanks for pointing this out. It is used to serve remote schema in test cases and it should be in test scope. I have release 0.1.5 and it will soon be available from Maven Central.
