### ISSUE TITLE
OneOfValidator cannot validate object with multiple properties

### ISSUE THREAD

**Issue by jiachen1120** [networknt/json-schema-validator#190]
For example, we have following schema defined:
```yaml
Pet:
    oneOf:
      -$ref: '#/components/schemas/dog'
      -$ref: '#/components/schemas/cat'
Dog:
    type: object
    properties:
      id: 
        type: string
      color: 
        type: string 
```
And the validation context is {"id": "abc", "color": "black"}, it seems the validation should be successful. However, it fails with the error message:
```
{"statusCode":400,"code":"ERR11004","message":"VALIDATOR_SCHEMA","description":"SchemaValidation Error - $: should be valid to one and only one of the schemas ","severity":"ERROR"}
```
The reason is our validator will return the error message when the node.size() larger then 1
```java
// validate that only a single element has been received in the oneOf node
        // validation should not continue, as it contradicts the oneOf requirement of only one
        if(node.isObject() && node.size()>1) {
        	errors = Collections.singleton(buildValidationMessage(at, ""));
        	return Collections.unmodifiableSet(errors);
        }
```
I am not pretty sure whether my understanding is correct or not, please advise:)
@stevehu

**Comment by ddobrin** [comment]
It is possible that it fails in:
Pet:
    oneOf:
      -$ref: '#/components/schemas/dog'
      -$ref: '#/components/schemas/cat'
... and would succeed if you change the schema to:
Pet:
    type: object
    oneOf:
      -$ref: '#/components/schemas/dog'
      -$ref: '#/components/schemas/cat'

Is this from the petstore?

**Comment by stevehu** [comment]
@jiachen1120 What is the definition for the cat? It should fail if both cat and dog are matching to the input.

**Comment by jiachen1120** [comment]
@ddobrin @stevehu Good morning! Sorry for the bad example. The example is just a simplified draft used to replace actual internal content. Let's be more specifically :) 

If LID has two properties:
```ymal
CIdentifier:
      type: object
      oneOf:
      - $ref: '#/components/schemas/LID'
      - $ref: '#/components/schemas/EID'
 
LID:
      type: object
      properties:
        another:
          type: string
        lID:
          type: string
EID:
      type: object
      required:
        - eID
      properties:
        eID:
          type: integer
```
The validation context is 
```
{"lID":"abc","another":"def"}
```
It seems satisfy the definition of oneOf. However it failed. The reason is that when validating the above context, oneOfValidator will check whether the length of the node is <= 1 before do the validation. The above node's size is 2. Therefore, no validation applied to the above context, an error will return directly.  The size checking mechanism seems added recently, the previous version can work properly. I am not  pretty sure the reason of the size checking, please advise, thanks!! :)

**Comment by stevehu** [comment]
@ddobrin Could you please confirm?

**Comment by ddobrin** [comment]
There are different use cases in the test package and I have a series of real life scenarios at my client's site.

I have used it in both situations.

That check is for more than 1 "object" being passed in and avoids the validation. You can have different cases.

The previous version doesn't work, for the simple fact that the set of test cases needs to include a few more (the ones which I have available). This prompted the oneOf fixes, as we had failures in the APIs at the client.

Dan

**Comment by jiachen1120** [comment]
This is the test case I added to json-schema-validator test, It failed. Could you please provide me some test case example? Thanks :)
```
"schema": {
			"oneOf": [
				{
					"type": "object",
					"properties": {
						"color": {
                                                    "type": "string"
						},
                                                "id": {
                                                  "type": "string"
                                                }
					}
				},			
				{
					"type": "object",
					"required": [
						"type"
					],
					"properties": {
						"type": {
							"enum": [
								"TYPE_2"
							]
						}
					}
				}
				
			]
		},
        "tests": [
            {
                "description": "first oneOf valid",
                "data": {
				    "color": "black",
                                    "id": "abc"
				},
                "valid": true
            }
```

**Comment by miklish** [comment]
@ddobrin From single stepping through the code, we found that `nodes` contains the number of schema elements in the oneOf, not the number of objects in JSON. This is why this fails on valid JSON.

**Comment by kosty** [comment]
@stevehu  could this fix be released? the 1.0.20 version contains a bug where validator state leeks from one execution to another and it breaks me and my customers. 

@ddobrin  please, submit "fixes" along with corresponding test coverage. And, probably, avoid `ThreadLocal` all together.

**Comment by stevehu** [comment]
@kosty 1.0.21 has been released. Sorry, I didn't realize that the bug has wider impact. @ddobrin and I had a discussion on the ThreadLocal approach and it seems the only option to resolve the context propagation at the moment. Do you have any better ideas?

**Comment by ddobrin** [comment]
We could not "connect" the oneOf validator with the PropertiesValidator, without changing the contract of all validators, which would have had a larger impact. This is why we chose ThreadLocal

**Comment by kosty** [comment]
@ddobrin it's really hard to answer that from shallow understanding of bug. A test case would be very appropriate here to demonstrate both bug and fix

**Comment by kosty** [comment]
@stevehu thanks! appreciate your prompt reaction.
