### ISSUE TITLE
null is not valid against nullable array with typeLoose false

### ISSUE THREAD

**Issue by chuwy** [networknt/json-schema-validator#194]
I have this test case:

```json
    {
        "description": "multiple types can be specified in an array with null",
        "schema": {"type": ["array", "null"], "items": {"type": "string"}},
        "tests": [
            {
                "description": "a null is valid",
                "isTypeLoose": true,
                "data": null,
                "valid": true
            }
        ]
    }
```

I assume this should pass validation, but it fail with following error:

```
[$[0]: null found, string expected]
```

It passes however with `"isTypeLoose": false` or no `items`. I thought this should have been fixed in https://github.com/networknt/json-schema-validator/issues/183, but I observe this behavior in 1.0.20 as well. It seems this behavior was introduced in 1.0.8 (presumably [here](https://github.com/networknt/json-schema-validator/pull/146/files#diff-c491ef6889ebf1aa58ddc7ba626a43a7R66))

I have several questions about it:

1. `isTypeLoose` is related to OpenAPI specification and goes against official v4 specification
2. `isTypeLoose` should make validation less strict, e.g. make `"3"` (string) pass against `integer` type
3. In this case however, seems `isTypeLoose` does something different and it should be considered a bug
4. Regardless of whether this is a bug or not, do you think `isTypeLoose` should default to `false`? At least I'd assume a JSON Schema validator library should be compliant with official specs

**Comment by chuwy** [comment]
I fixed this by changing:

```java
if (!node.isArray() && !config.isTypeLoose()) {
```
to 
```java
if (!node.isArray()) {
```

in [ItemsValidator.java](https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/ItemsValidator.java#L66). But now several other tests fail, e.g.

```json
    {
        "description": "an typeLoose array of schemas for items",
        "schema": {
            "items": [
                {"type": "integer"}
            ]
        },
        "tests": [
            {
                "description": "wrong types",
                "data": "foo",
                "isTypeLoose": true,
                "valid": false
            }
        ]
    }
```

Funny thing is that IMO this instance *is* valid against above schema, because `items` simply irrelevant to string `foo`. Probably I just still don't understand a meaning of "looseType" config, it looks very confusing to me.

**Comment by stevehu** [comment]
@chuwy TypeLoose is to handle the OpenAPI specification as it is different than the JSON scheme validation at the moment. The specific flag is to allow the library to treat query parameters, headers and path parameters without worry about the types. In the HTTP context, everything is a string but the schema might indicate that pageNum is an integer. So the library will tolerate the input "20" as an integer although it is a string. That is what TypeLoose works. If you are using pure schema validation, set the TypeLoose to false.

**Comment by chuwy** [comment]
Thanks @stevehu! So this confirms my understanding and I will change its use in our lib. Then it also means that `typeLoose` is relevant only to strings and probably my fix is actually correct.

**Comment by stevehu** [comment]
Yes. The change looks good.

**Comment by chuwy** [comment]
Sorry, by "my fix" I meant one mentioned here: https://github.com/networknt/json-schema-validator/issues/194#issuecomment-538374799. I'm just not sure what we need to do with other tests that fail because of that fix, IMO those test cases are invalid (also regardless of `typeLoose`).

I still think this is a bug and the fact that it works with `typeLoose: false` is just a lucky coincedence.

**Comment by stevehu** [comment]
Let's keep this open as a bug so that we can investigate further. Thanks.

**Comment by koxauvin** [comment]
I ended up reverting back to 1.0.7 to get my case or work. Confirming > "It seems this behavior was introduced in 1.0.8" from above.

**Comment by MarinaRappoport** [comment]
`isTypeLoose` also converts string/integers/objects to array, that seems not to be correct according to documentation. I opened another issue for that:
https://github.com/networknt/json-schema-validator/issues/415

**Comment by stevehu** [comment]
This shouldn't be an issue for the latest version 1.4.x
