### ISSUE TITLE
[Question] How to use NonValidationKeyword?

### ISSUE THREAD

**Issue by stanlyDoge** [networknt/json-schema-validator#196]
Hi

I am defining my schema, which contains an unknown keyword. And because of that, I am getting this message: `WARN  Unknown keyword example - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword`.

I am not sure where and how I should use `NonValidationKeyword`. Can you help me, please?

My schema json looks like this: 
```
"age": {
    "title": "age",
    "type": "object",
    "additionalProperties": {
        "type": "array",
        "items": {
            "format": "int32",
            "type": "integer"
        }
    },
    "example": {
        "tier1": [
            1,
            2,
            3
        ]
    }
}
```

**Comment by chuwy** [comment]
Hey @stanlyDoge,

I think idea the is that you create your own metaschema and add this keyword during building. Here's for example our use case (sorry its Scala, but I think syntax should be self-explanatory):

https://github.com/snowplow/iglu-scala-client/blob/master/src/main/scala/com.snowplowanalytics.iglu/client/validator/CirceValidator.scala#L187-L192

We have our own format of JSON Schema, where each schema can contain `self` keyword with no validation semantics. [Example](https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/duplicate/jsonschema/1-0-0#L4-L9). So we create a metaschema with `http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#` `$schema` and tell the validator that it will contain `self` keyword.

**Comment by stanlyDoge** [comment]
Thanks for the reply! :)
