### ISSUE TITLE
Use with obfuscation

### ISSUE THREAD

**Issue by complex1ty** [networknt/json-schema-validator#200]
Hi,
I use this library in Android and obfuscate the release build with Proguard. However, the library will crash after obfuscation due to the reflection code to instantiate validators inside the method `public JsonValidator newValidator(...)` in the class `ValidatorTypeCode`. All validator classes are renamed during compile time so they are not able to load using their original names during runtime. Could we replace the reflection code to make it compatible with obfuscation? Thank you.

**Comment by miklish** [comment]
You should be able to configure Proguard to not obfuscate specific classes.

**Comment by stevehu** [comment]
@miklish In the hindsight, I think the reflection is too complicated and error-prone. The PR @complex1ty submitted is much better so that we don't need to calculate the class names. We just need to make sure that the enhancement covers all our use cases.
