### ISSUE TITLE
String for Number should fail with the default SchemaValidatorsConfig

### ISSUE THREAD

**Issue by stevensouza** [networknt/json-schema-validator#203]
The library isn't detecting the difference between a string and a number.  I would expect the following to fail and it doesn't.  I changed product-no-errors-data.json to the following (note the string).

```
{
    "id": 1,
    "name": "A valid product name",
    "price": "99.99"
}

```
And put a test in JsonSchemaTest that should fail but doesn't.

  ```
 @Test
    public void testFailFast_AllErrors_Number() throws IOException {
        try {
            validateFailingFastSchemaFor("product.schema.json", "product-one-error-data-number.json");
            fail("Exception must be thrown");
        } catch (JsonSchemaException e) {
            final Set<ValidationMessage> messages = e.getValidationMessages();
            assertEquals(1, messages.size());
        }
    }
```

**Comment by stevehu** [comment]
@stevensouza The library works for both JSON schema and OpenAPI specification which has headers, query parameters as strings. However, there is a switch in the configuration to control if a string is valid for a number defined in the spec. It is called typeLoose flag. The default is false so you should have an error if calling the library directly without passing the type loose flag. What you have encountered might be a bug. What is the content of the product.schema.json? I need to debug into ti to find out the issue. Thanks for raising it up.

**Comment by stevensouza** [comment]
I used your product.schema.json without any changes - https://github.com/networknt/json-schema-validator/blob/master/src/test/resources/tests/product.schema.json

I only changed "price" in the data file to "99.99" instead of 99.99 from the no error data file.  So the test should have had one error, but had none.  Also it would be interesting to test if boolean has the same issue.  

One of the things that is most important for me to test is that numbers are in my json document and not strings, so this is an important one for me.

**Comment by stevensouza** [comment]
Also, I did not change the default value of the typeLoose flag.

**Comment by stevensouza** [comment]
Note I also changed the id field to a string and it didn't detect that error either.
{
    "id": "1",
    "name": "A valid product name",
    "price": "99.99"
}

**Comment by stevensouza** [comment]
How do I disable this?  I am using this library independently and getting this error.

Here is the test I am running in my codebase...What am I doing wrong?  my schema file defines a number and it is accepting a String just like I mentioned above.

    @Test
    public void invalid2() throws Exception {
        JsonSchema schema = getJsonSchemaFromClasspath(SCHEMA_FILE);
        JsonNode node = getJsonNodeFromClasspath(JSON_FILE_ERRORS);
        Set<ValidationMessage> errors = schema.validate(node);
        System.err.println(JsonUtil.toJsonString(errors));
        assertThat(errors).hasSize(5);
    }

    protected JsonSchema getJsonSchemaFromClasspath(String name) throws Exception {
        JsonSchemaFactory factory = JsonSchemaFactory.getInstance();
        InputStream is = Thread.currentThread().getContextClassLoader()
                .getResourceAsStream(name);
        JsonSchema schema = factory.getSchema(is);
        return schema;
    }

**Comment by stevehu** [comment]
@BalloonWen @rhwood @ddobrin @jawaff We have defaulted typeLoose in the SchemaValidatorsConfig in the loadDefaultConfig(). Since it is designed for the light-4j framework for OpenAPI specification only, it is possible to remove the flag and set it in the openapi-validator module in the light-rest-4j? I have walked through history and couldn't find any clue on the reason we set it as true by default. Thanks.

**Comment by stevehu** [comment]
I think I understand why the default for typeLoose is true in the config class. In the openapi-validator module, we only set it to false to skip the validator for the body. We need to update the config for headers, query parameters and path parameters to true instead in the light-rest-4j. I will make the change if there is no objection. 

https://github.com/networknt/light-rest-4j/blob/master/openapi-validator/src/main/java/com/networknt/openapi/RequestValidator.java#L121

**Comment by BalloonWen** [comment]
> I think I understand why the default for typeLoose is true in the config class. In the openapi-validator module, we only set it to false to skip the validator for the body. We need to update the config for headers, query parameters and path parameters to true instead in the light-rest-4j. I will make the change if there is no objection.
> 
> https://github.com/networknt/light-rest-4j/blob/master/openapi-validator/src/main/java/com/networknt/openapi/RequestValidator.java#L121

Yes, at that time that was the minimum change because only request body needs to be validated strictly.

**Comment by stevehu** [comment]
@BalloonWen Thanks a lot for the clarification. With the fail-fast feature added, the normal schema-validator usage might need to use the config file now. I will update the library and adjust the light-rest-4j openapi/swagger-validator.

**Comment by stevensouza** [comment]
Ok, here is what i did to solve the problem.  Thanks for your help.
`
    protected JsonSchema getJsonSchemaFromClasspath(String name) throws Exception {
        JsonSchemaFactory factory = JsonSchemaFactory.getInstance();
        InputStream is = Thread.currentThread().getContextClassLoader()
                .getResourceAsStream(name);
        SchemaValidatorsConfig config = new SchemaValidatorsConfig();
        config.setTypeLoose(false);
        JsonSchema schema = factory.getSchema(is, config);
        return schema;
    }`
I would think that a better default for json schema validation would be ot have typeLoose default to false though and to specify this somewhere in some documentation.
