### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by stevensouza** [networknt/json-schema-validator#204]
First of all thanks for your library and efforts.

Is there any other use documentation besides what is on the quickstart guide?  So much work obviously went into this useful library, but a little more documentation would be helpful.  If not then a tip for where in the tests to look for basic usage would be helpful.

**Comment by stevehu** [comment]
@stevensouza It is a good idea to add additional documents for the library. I will create a doc folder and link the md files in the folder from the README.md file. Given the time constraint, I will just start it and help other developers can add more content together. Also, it would be great if all of you give us ideas on what section/topic are interested at the moment. Thanks.

**Comment by stevehu** [comment]
config.md is added for configurations.
