### ISSUE TITLE
the if-then-else.json is failed in test for V7 and V2019-09

### ISSUE THREAD

**Issue by stevehu** [networknt/json-schema-validator#214]
When we implement the if-then-else, we have added an if.json for our test cases. Now, I have moved the if-then-else to V7 and V2019-09 only and added the official test suite. 

The if-then-else.json has one failure now and I have make the test case ignored in V7 and V201909 for now. This needs to be investigated and fixed.

**Comment by andersonf** [comment]
@stevehu, I know how to fix the issue, I will wait the PR #213 be merged to create a new PR to fix this.
If you wish to fix it in PR #213, We just need to replace line 57 in IfValidator.java to be:
`} else if (!ifErrors.isEmpty() && elseSchema != null) {`
Thanks!
