### ISSUE TITLE
Can json-schema-validator used for YAML validation

### ISSUE THREAD

**Issue by piyushkumar13** [networknt/json-schema-validator#217]
As per this https://json-schema-everywhere.github.io/yaml, json schema can be used to validate the yaml as well. Can `json-schema-validator` be used for yaml validation ?
If yes, advise me how I can achieve this? As of now, I am not able to validate yaml using this library

**Comment by stevehu** [comment]
This library is part of the light-4j framework to validate request/response at runtime against the OpenAPI specification file openapi.yml. So it does work with YAML and it is the main use case for us. If you are not using light-4j, you need to load the yaml with https://github.com/FasterXML/jackson-dataformats-text first and then everything is the same as JSON.

**Comment by piyushkumar13** [comment]
@stevehu  Thanks it has worked. Just sharing what I did, it might be helpful for someone else.
Add the dependency 
```
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
            <version>2.10.1</version>
        </dependency>
```
and created object mapper using yaml factory i.e `ObjectMapper objMapper  =new ObjectMapper(new YAMLFactory());`

**Comment by piyushkumar13** [comment]
@stevehu I am facing another issue. I am not sure about pinging in the same issue, however, taking my chances. I am trying to use JsonSchema draft-07 and initializing JsonSchemaFactory as per one of your testcases : https://github.com/networknt/json-schema-validator/blob/master/src/test/java/com/networknt/schema/V7JsonSchemaTest.java#L24

Using following dependency :
```
        <dependency>
            <groupId>com.networknt</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>1.0.26</version>
        </dependency>
```
I cannot find any factory method `getInstance` which accepts Draft version as what is advocated in the testcase. 
Could you please help me with the code snippet to use draft-07 json schema(or any other draft after 04) to validate. Thanks in advance.

**Comment by piyushkumar13** [comment]
Looks like it is just released : https://github.com/networknt/json-schema-validator/releases

**Comment by stevehu** [comment]
@piyushkumar13 Thanks a lot for your feedback. I have incorporated your process into a document [yaml.md](https://github.com/networknt/json-schema-validator/blob/master/doc/yaml.md). Please review and feel free to add/update more details. Thanks.

**Comment by piyushkumar13** [comment]
> @piyushkumar13 Thanks a lot for your feedback. I have incorporated your process into a document [yaml.md](https://github.com/networknt/json-schema-validator/blob/master/doc/yaml.md). Please review and feel free to add/update more details. Thanks.

Looks good @stevehu . I have added an example, here is the PR : https://github.com/networknt/json-schema-validator/pull/218
