### ISSUE TITLE
Android 6 support

### ISSUE THREAD

**Issue by matthias-sattel** [networknt/json-schema-validator#221]
Hi,
in order to use your library on Android 6 (API>=23) we had to backport it to Java 6. Would this be a contribution that you would like to integrate into this project or will you stick to Java 8 ?
Best regards,
Matthias

**Comment by stevehu** [comment]
@msattel I am not an Android developer and recently upgrade to Java 8 in order to leverage the new Java 8 features. I did a research and found Android 6 was discontinued in 2018 with on security patches anymore. Do we still have developers working on this platform?

**Comment by stevehu** [comment]
https://github.com/networknt/json-schema-validator/issues/162

**Comment by msattel** [comment]
@stevehu As far as I know around 15% of the Android users are still running on Android version 6 and below. This is why our management devided, that we have to support those old Android versions. Otherwise we would not support it at all and hopefully this situation will change soon.

**Comment by stevehu** [comment]
@msattel I tried to change the java version back to 1.6 as below and found only a few places need to be updated in the src. There might be some test cases leverage Java 8 lambda expressions. Would you like to submit a PR? 

```
        <java.version>1.6</java.version>
        <java.testversion>1.8</java.testversion>
```

**Comment by miklish** [comment]
Android 1.6 is from 2009. That's a full 10 years ago. What kind of revenue are you expecting from users that can't afford to update their hardware at least once every decade?

**Comment by msattel** [comment]
@miklish It is Anrdoid 6, not Android 1.6
https://en.wikipedia.org/wiki/Android_version_history#Android_6.0_Marshmallow_(API_23)
It is from 2015 and yes, outdated from my point of view. But seems to still have a lot of end users and thus possible app customers.

**Comment by msattel** [comment]
@stevehu I will provide the PR asap. Have a nice weekend

**Comment by ondrej** [comment]
Hi @msattel , are you still working on a PR for this? We just started using the library on Android all the way back to API level 22 (Java 5.1) and while we haven't encountered any issues yet, would be keen to see what could break and if we can help make it official. Thanks!

**Comment by msattel** [comment]
@stevehu @ondrej  Sorry for the delay, I just created the PR https://github.com/networknt/json-schema-validator/pull/244

**Comment by stevehu** [comment]
@msattel Thanks a lot. I will mark this issue closed.

**Comment by stevehu** [comment]
@msattel As more and more dependencies lose the support for Java 6, it is time to re-evaluate our situation again. Do we still need to support Java 6 or move to Java 8? What is your opinion? Thanks.

**Comment by filipebezerra** [comment]
I think we have a big issue concerned about Android development, because Android platform is highly fragmented and thus lead software developers and companies having to support them because of their business model or product requirements.

Modern Android applications now are recommended to use [Jetpatck components](https://developer.android.com/jetpack/getting-started), Google recommends to [support Java 8](https://developer.android.com/studio/write/java8-support#library-desugaring) as the Java language level because some features are supported

**Comment by stevehu** [comment]
We have dropped Java 6, and Java 8 will become a maintained branch for the 1.0.x release.
