### ISSUE TITLE
add anchor validator for v2019-09

### ISSUE THREAD

**Issue by stevehu** [networknt/json-schema-validator#227]

**Comment by Whathecode** [comment]
I'm getting a `NullPointerException` when trying to validate JSON using the following schema:

```
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "oneOf": [
    { "$ref": "#SomeDef" },
    ...
  ],
  "$defs": {
    "SomeDef": {
      "$anchor": "SomeDef"
      ...
    }
  }
}
```

The stacktrace:

```
java.lang.NullPointerException
com.networknt.schema.JsonSchemaException: java.lang.NullPointerException
	at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:399)
	at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:57)
	at com.networknt.schema.JsonSchema.read(JsonSchema.java:228)
	at com.networknt.schema.JsonSchema.getValidators(JsonSchema.java:466)
	at com.networknt.schema.JsonSchema.validate(JsonSchema.java:283)
	at com.networknt.schema.BaseJsonValidator.validate(BaseJsonValidator.java:114)
```


I'm going to guess this simply means, as per this issue, fragment references to anchors aren't supported?

A workaround for now is using `#/$defs/OpenDataStreams`.

**Comment by Whathecode** [comment]
Looking at the code a bit, I suppose [`JsonSchema.nodeContainsRef()`](https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/JsonSchema.java#L198) would need to be modified.

Right now, [when encountering a `#...` ref](https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/JsonSchema.java#L158), the current schema is traversed [recursively ](https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/JsonSchema.java#L189) to look for an underlying node with `$id` (or `id` for draft 4) equaling the ref (`#...`). If I'm not mistaken, [looking at the spec](https://json-schema.org/understanding-json-schema/structuring.html#anchor), this is compatible with the old drafts, but not draft v2019-09.

Would implementing this feature simply entail swapping out that lookup with a recursive search for an `$anchor` equaling the ref minus the prefix `#` in the case of draft v2019-09?

**Comment by Whathecode** [comment]
I'm having a go at a PR. Seemingly there is already [a failing, disabled, unit test related to this issue](https://github.com/networknt/json-schema-validator/blob/master/src/test/java/com/networknt/schema/V201909JsonSchemaTest.java#L162).

**Comment by stevehu** [comment]
@Whathecode The test cases for Anchor were disabled because the keyword wasn't implemented. I tried to run the official test cases from the IDE with the latest code from your branch and found some errors. Most of them are related to accessing the remote URL (http://localhost:1234/bar). It might be due to the test server didn't start properly. I am wondering if you could take a look. If you are interested, I can grant you access to the networknt repo and you can create a branch here to get help from other users. Thanks.

**Comment by Whathecode** [comment]
This is that I describe in the PR. 🙂 Please have a look there.
