### ISSUE TITLE
URI validation does not allow relative reference

### ISSUE THREAD

**Issue by Apenbrood** [networknt/json-schema-validator#23]
Validating property of type string with format uri only allows absolute uri. For example "#item" is not allowed.

If you look at rfc3986 this should also be allowed.

**Comment by stevehu** [comment]
Thanks for opening the issue. I will take a look to get it fixed.

**Comment by stevehu** [comment]
@Apenbrood I think we do handle local reference and remote reference and there are test cases to cover it. Have you spot any particular issue with local reference?

Here is the code that handles local ref.

```
        if (refValue.startsWith("#")) {
            // handle local $ref
            if (refValue.equals("#")) {
                schema = parentSchema.findAncestor();
            } else {

                JsonNode node = parentSchema.getRefSchemaNode(refValue);
                if (node != null) {
                    schema = new JsonSchema(mapper, refValue, node, parentSchema);
                }
            }
        } else {
            // handle remote ref

```

**Comment by Apenbrood** [comment]
Sorry for being less clear.

If you have a schema which describes a object, like this:

{
    "properties": {
        "id": {
            "type": "string",
            "format": "uri"
        }
    },
     "type" : "object"
}

then json:

{ 
    "id" : "#item" 
}

will not validate.

I ran into this when using the metaschema on http://json-schema.org/documentation.html to validate json schemas. 

According to http://json-schema.org/latest/json-schema-core.html#rfc.section.8.2  "id": "#foo" is allowed. And if I read RFC 3986 then fragment identifiers are allowed.

**Comment by stevehu** [comment]
Thanks for the clarification. I will put it into the test suite when the fix is in.

**Comment by chuwy** [comment]
We also cannot validate JSONs like `{"url":"/princess-fly-free-offer"}` with `format: uri`, although it seems to be valid as per RFC. Getting this validation message (format slightly modified by client lib):

```
{
  "path": "$.url",
  "message":"$.url: does not match the uri pattern (^[a-zA-Z][a-zA-Z0-9+-.]*:[^\\s]*$)|(^//[^\\s]*$)",
  "keyword":"format",
  "targets":["uri","(^[a-zA-Z][a-zA-Z0-9+-.]*:[^\\s]*$)|(^//[^\\s]*$)"]
}
```

**Comment by stevehu** [comment]
@Apenbrood @chuwy Could you please retest and confirm if the latest change for the URN support works or not? Thanks.
