### ISSUE TITLE
v7 support is not completed

### ISSUE THREAD

**Issue by shark300** [networknt/json-schema-validator#230]
In #54  and #213 were introduced draft-v7 support but idn-* validations are not working in 1.0.28. There are a some ignored test cases what are related to v7 support. This is misleading because it is not fully supported.

**Comment by stevehu** [comment]
@shark300 You are right. There are still several validators that are not implemented and there are separate issues to track them. I just reopened #54 and will close it until everything is done. Thanks for raising this.

**Comment by fdutton** [comment]
Resolved in #775
