### ISSUE TITLE
validator doesn't validate by schema with $ref to another local file using URIFetcher

### ISSUE THREAD

**Issue by jonua** [networknt/json-schema-validator#233]
Schemas was placed in the root of the *resources/* folder.

**schema 1**
```json
{
  "$id": "an_id_for_complex_schema_json",
  "type": "object",
  "properties": {
    "field1": {
      "type": "string"
    },
    "field2": {
      "type": "number"
    },
    "field3": {
      "$ref": "file:second.schema.json"
    }
  }
}
```

**schema 2**
```json
{
  "$id": "an_id_for_second_schema_json",
  "definitions": {
    "externalField": {
      "type": "string"
    }
  }
}
```

**test**
```java
@Test
    void doTest() throws IOException {
        String pathToFile = Thread.currentThread().getContextClassLoader().getResource("test.file.txt").getPath();
        String base = pathToFile.substring(0, pathToFile.lastIndexOf("/"));
        Path directory = Paths.get(base);

        JsonMetaSchema metaSchema = JsonMetaSchema.getV201909();

        JsonSchemaFactory factory = new JsonSchemaFactory.Builder()
                .addMetaSchema(metaSchema)
                .defaultMetaSchemaURI(metaSchema.getUri())
                .uriFetcher(uri -> {
                    String fileName = uri.toString().substring(uri.getScheme().length() + 1);
                    Path path = Paths.get(directory.toString(), fileName);
                    return new FileInputStream(path.toString());
                }, "file")
                .build();

        InputStream is = Thread.currentThread().getContextClassLoader().getResourceAsStream("complex.schema.json");
        JsonSchema schema = factory.getSchema(is);

        ObjectMapper mapper = new ObjectMapper();
        JsonNode jsonNode = mapper.readValue("{\"field1\":\"sss\", \"field2\":33.2, \"field3\":23}", JsonNode.class);
        Set<ValidationMessage> violations = schema.validate(jsonNode);

        Assertions.assertFalse(violations.isEmpty());
    }
```

*expected*: green test
*actual*: expected: &lt;false&gt; but was: &lt;true&gt;

it is a bug or what does I'm doing wrong?

**Comment by stevehu** [comment]
I don't think the reference `"$ref": "file:second.schema.json"` is valid. Change it to

```
http://localhost:1234/second.schema.json
```
and move the second.schema.json into the remotes folder will work.

**Comment by jonua** [comment]
But I'm wrote a URIFetcher which fetch my "second.schema.json" from disk.

```
JsonSchemaFactory factory = new JsonSchemaFactory.Builder()
...
.uriFetcher(uri -> {
    String fileName = uri.toString().substring(uri.getScheme().length() + 1);
    Path path = Paths.get(directory.toString(), fileName);
    return new FileInputStream(path.toString());
}, "file")
.build();
```

why it isn't works?

What is a "remotes folder"? Have you an example?
Can't I accomplish a validation json by schemas placed locally?

**Comment by stevehu** [comment]
All remote files are in this folder. 

```
https://github.com/networknt/json-schema-validator/tree/master/src/test/resources/remotes
```

**Comment by jonua** [comment]
Ok, thanks, @stevehu

**Comment by jonua** [comment]
@stevehu this constants contains a "file" item https://github.com/networknt/json-schema-validator/blob/63b0c8cdf3defacf4caa40518ecce45bb29a298c/src/main/java/com/networknt/schema/uri/URLFactory.java#L33 what is the point for that constant?

**Comment by stevehu** [comment]
@jonua The file protocol is supported by the library but it is definitely not recommended as it is a non-standard. These days, most people will use the URL mapping to map the remote reference to the local so that we still use the validate json schema. 

https://github.com/networknt/json-schema-validator/blob/master/doc/schema-map.md

**Comment by jonua** [comment]
And my second question: my way with using custom URIFetcher doesn't works. Why?

**Comment by stevehu** [comment]
I haven't looked at the details of your custom fetcher but if you can load the schema correctly, it should work. Debug into it and find if the second schema is loaded correctly.

**Comment by jonua** [comment]
my mistake in inattention.
Bug in the `second.schema.json` file. Need to fix file content on:

```json
{
  "$id": "an_id_for_second_schema_json",
  "type": "object",
  "properties": {
    "externalField": {
      "type": "string"
    }
  }
}
```

Field ** definitions** need replace with field **properties** and add field **type** and test will be green.

Thanks, @stevehu, for the explanation and discussion
