### ISSUE TITLE
Fetch schemas from secure source

### ISSUE THREAD

**Issue by jonua** [networknt/json-schema-validator#235]
Hello,
I want to load schemas from source which secured with Bearer token (or basic auth or something else).
URLFetcher is a `final` class:(
How can I fetch schemas from secured source or what is a best way to create a custom solution?

**Comment by stevehu** [comment]
I think the easiest way is to implement different authentication methods in the URLFetcher and calling a different method based on the configuration. All other methods might require customization of the library. What do you think?

**Comment by jonua** [comment]
Thanks for you reply, @stevehu 

How can I may implement some methods in URLFether if that class is **final**? 
And if we don't discuss the extending a default URLFetcher class - I don't understand, how can I replace a default URLFetcher's in uriFetcherMap in SchemaJsonFactory#Builder becose that builder doesn't provide direct access to this map.

Do you can describe you idea about implementing different auth methods in the URIFetcher class in more detail?

**Comment by stevehu** [comment]
@jonua Even we make the URLFetch not final, it is useless to extend it as there is only one meaningful method there. What I am saying is to update the exact class to get some config properties from the config file. 

For example, 

```
if(oauth) {

} else if(basic) {

} else {
   current logic. 
}

```

**Comment by jonua** [comment]
How can I combine this solution with JsonSchemaFactory?

**Comment by stevehu** [comment]
Good question. After I looked at the factory, I remember that we do support multiple fetchers in the schema loading at https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/JsonSchemaFactory.java#L61

In this case, we just need to implement OAuth2 fetcher and Basic fetcher and map them to a list of schemas. What do you think?

**Comment by jonua** [comment]
Yes, I have been use that. Thanx, @stevehu

**Comment by stevehu** [comment]
@jonua Would you like to contribute your secured URIFetcher implementation to share it with other users? I think more and more schemas will be secured in the future. Thanks.
