### ISSUE TITLE
Can I cache a JsonSchema instane? Is it self-sufficient instance?

### ISSUE THREAD

**Issue by jonua** [networknt/json-schema-validator#238]
Hi,
I want to cache a JsonSchema instance loaded once. An instance of JsonSchema is a self-sufficient instance? I noticed that JsonSchema instance have a "currentUri" field. Are there cases in which schemas will be loaded from source by URIFetcher's again when I trying validate a json?
I did not find this behaviour in json-schema-validator code, but maybe I was inattentive?

**Comment by stevehu** [comment]
@jonua I don't think we are creating multiple instances for the same schema. If it happens, it is a bug.
