### ISSUE TITLE
URLFactory doesn't save a query params

### ISSUE THREAD

**Issue by jonua** [networknt/json-schema-validator#239]
here the test (junit5)
```java
...
import com.networknt.schema.uri.URIFactory;
import java.net.URI;
import org.junit.jupiter.api.Assertions;
...
@Test
void test() {
    URIFactory urlFactory = new URLFactory();
    URI baseUrl = URI.create("http://localhost/path/to/schema?query=value");
    URI resultUri = urlFactory.create(baseUrl, "we/need/to/go/deeper");

    Assertions.assertNotNull(resultUri.getQuery());
    Assertions.assertEquals(baseUrl.getQuery(), resultUri.getQuery());
}
```

it is a bug or a feature?

**Comment by stevehu** [comment]
This is very strange as the conversion is very straight forward in the create method. Would you be able to debug into it to see where the query parameter is lost? 

```
  @Override
  public URI create(final String uri)
  {
    try {
      return new URL(uri).toURI();
    } catch (MalformedURLException | URISyntaxException e) {
      throw new IllegalArgumentException("Unable to create URI.", e);
    }
  }

```

**Comment by jonua** [comment]
params are lost when I use a `URI URLFetcher#create(URI baseURI, String segment)` method, not a `URI create(String uri)`

after execution a code:
```java
new URL(baseURI.toURL(), segment).toURI()
```

result URI contains "segment" query params only

**Comment by stevehu** [comment]
We never thought that a query parameter will be used to access the remote schema. I think we can resolve the issue by calling getQuery() on the baseURI and setQuery() on the newly created URL object. Would you be able to test it out and submit a PR? Thanks.

**Comment by jonua** [comment]
I can submit PR but I can't sure if the query parameters should be saved in the default behaviour. So I asked clarifying question - it is a bug or feature?:)
For example - we have a schema placed in two file: fileA & fileB. fileA is a "main" schema file, accessible by link **http://domain.name/path/to/fileA?ref=someParams**. fileA have a reference to the fileB like this:

```json
...
"field1": {
    "$ref": "path/to/fileB"
}
...
```

fileB can be loaded by direct link or with additional query param like "ref" (for example content from [github](https://developer.github.com/v3/repos/contents/))

should a link to fileB be created dependent of view of link to fileA in uri-factory or link to fileB should have been already in completed view in the fileA (like "$ref": "path/to/fileB?ref=someParams") ?

**Comment by stevehu** [comment]
@jonua That is a very good question. Frankly, I never thought about it in-depth and your question makes me revoke my previous idea. To answer your question first, it is not a feature and it is not a bug neither in my opinion. As I said, I never thought about this use case as most of the remote schema references are static files. Now, I understand in some scenarios, it can have a query parameter and there are several flavors to handle it. I would recommend that leave the current method intact and create a brand new method to support query parameters. This gives most users an option to use the simple method but advanced users another method. What do you think?

**Comment by jonua** [comment]
@stevehu yes, it is a good idea
