### ISSUE TITLE
connection/socket timeout has an infinite value?

### ISSUE THREAD

**Issue by jonua** [networknt/json-schema-validator#240]
Looks like the URLFetcher has a default values (infinite) for a connection/socket timeout. Right?

**Comment by stevehu** [comment]
Yes. The fetcher is a very simple implementation and assumes a lot of conditions. We should create an exception upon timeout and convert it into a validation error somehow.

**Comment by jonua** [comment]
In my implementation of a custom URLFetcher I use a [unirest](http://unirest.io/) instance with timeout. But this is hardly a good idea for a library - additional dependency will complicate implementation

**Comment by stevehu** [comment]
@This is good enough. I just want the users to know that the default implementation is simple and works for normal scenarios; however, it doesn't handle all possible exceptions. There is a way to substitute with customized implementations. I will write a document for this. Thanks.
