### ISSUE TITLE
Is it possible to use custom meta schema or vocabulary?

### ISSUE THREAD

**Issue by SridharSubramaniam** [networknt/json-schema-validator#241]
Didn't find a method in code - but thought of asking - does the library support custom meta schemas?

similar to addMetaSchema in ajv.
https://github.com/epoberezkin/ajv

**Comment by stevehu** [comment]
Yes. It does support customized meta schema with this builder method. We have provided default instances for v4, v6, v7, and v2019-09 but users can always create their own JsonMetaSchema instance with customized meta schema. 

https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/JsonMetaSchema.java#L188

**Comment by SridharSubramaniam** [comment]
That's good to know. Will test it out. Thanks!
