### ISSUE TITLE
ValidationMessage to include relative position of validation error

### ISSUE THREAD

**Issue by Abhitheja-Pinnadari** [networknt/json-schema-validator#245]
Just like any other XSD validator which was giving row and column index for the validation error. This will help in showing the visual guidance on the editors upon validation. Please let me know if any such feature is already there.

**Comment by stevehu** [comment]
No. It is not there yet. I think it would be a fantastic feature if we can implement it.

**Comment by handrews** [comment]
@stevehu note that draft 2019-09 provides a recommendation on what data to collect for output / error conditions, and recommends some formats to improve interoperability.  I'm not sure what "row and column" means here, as we focused on URI and/or JSON Pointer representations of static and runtime schema locations, as well as the instance location.

**Comment by stevehu** [comment]
@handrews My understanding of row and column is the exact location where the error occurs. In my opinion, it is very hard to capture the context information like row and column in the JSON data as none of the JSON parser does. What we can do is capturing the JSON pointer in the context and assisting users to identify the location of the issue. 

I will review the guide in the following link again and adjust the error message whenever necessary. 

https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.10.3.4

**Comment by handrews** [comment]
@stevehu sounds good.  We would love to hear any feedback on that section.  The reason that there are several different recommended formats is that there wasn't consensus on the best option, so we're interested in seeing if one emerges as preferred across implementations.

**Comment by stevehu** [comment]
@handrews Sure. Will do. @Abhitheja-Pinnadari I saw you have updated the title to clarify the issue. Let's keep this issue open so that we can find resources to address it based on the JSON schema core.
