### ISSUE TITLE
Multiple type property fail on the first type not match in case of failfast set to true

### ISSUE THREAD

**Issue by o-b-one** [networknt/json-schema-validator#246]
## Description

When `failFast` set to `true` the schema validation process is not checking all of the types, instead, first failure will fail the entire validation flow.

### Schema

`
        
     {
    "type": "object",
    "title": "test",
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "required": [],
    "properties": {
        "test": {
            "type": [
                "null",
                "string",
                "number"
            ],
            "minimum": 
            "maxLength": 10,
            "minLength": 1,
            "exclusiveMaximum": 5
        }
    },
    "$vocabulary": {
        "https://json-schema.org/draft/2019-09/vocab/core": true,
        "https://json-schema.org/draft/2019-09/vocab/format": false,
        "https://json-schema.org/draft/2019-09/vocab/content": true,
        "https://json-schema.org/draft/2019-09/vocab/meta-data": true,
        "https://json-schema.org/draft/2019-09/vocab/applicator": true,
        "https://json-schema.org/draft/2019-09/vocab/validation": true
    },
    "additionalProperties": false
    }

### Resource

   {
     "test": "test"
   }

### Fix 

On `UnionTypeValidator` Class update the validate method to catch exceptions

`
      
        public Set<ValidationMessage> validate(JsonNode node, JsonNode rootNode, String at) {
        this.debug(logger, node, rootNode, at);
        JsonType nodeType = TypeFactory.getValueNodeType(node);
        boolean valid = false;
        Iterator var6 = this.schemas.iterator();
        while(var6.hasNext()) {
            JsonValidator schema = (JsonValidator)var6.next();
            Set<ValidationMessage> errors;
            try{
              errors = schema.validate(node, rootNode, at);// this line throwing an error
            } catch( JsonSchemaException error){
                 errors = error.getValidationMessages();
            }
            if (errors == null || errors.isEmpty()) {
                valid = true;
                break;
            }
        }
        return !valid ? Collections.singleton(this.buildValidationMessage(at, new String[]{nodeType.toString(), this.error})) : Collections.emptySet();
    }

**Comment by stevehu** [comment]
The fail fast is not working properly and it needs more work to be done. There are several other issues reported by users at https://github.com/networknt/json-schema-validator/issues/209

We need to have a redesign to resolve the issues.

**Comment by Dukejung** [comment]
I recently experienced the same problem. Are there any updates or plans to address this in the future? It seems that #209 recently resolved at version 1.0.84 and closed but this issue still exists.
Thank you for your contribution.
