### ISSUE TITLE
Customize Validation Messages

### ISSUE THREAD

**Issue by stevensouza** [networknt/json-schema-validator#250]
Is there a way to replace your standard ValidationMessages?  I would like to make them more consumable by non-technical users.

And also thanks for your great project. Keep up the good work...

Steve

**Comment by stevehu** [comment]
@stevensouza The error message is defined in ValidatorTypeCode.java and it can be customized there. If there are a lot of people who require the customization, we might need to externalize the error message to a config file.

**Comment by stevensouza** [comment]
@stevehu So you are saying I can change that file, recompile and use that jar?  

If you guys decide to make this change, one thought is that it might be good to keep your message (getMessage), but allow developers to add their own messages too. For example, adding an additional messages capability.  I'm not sure if that is useful or not but throwing that out there.

**Comment by stevehu** [comment]
Yes. That is the idea. If we ever open this to the users, it would be a mechanism to overwrite the default one with additional configuration. For your changes, could you please give us more information? If it makes sense, we are going to change the default error message to make it more accurate. Thanks.

**Comment by stevensouza** [comment]
Not sure what you are asking from me?  Implementation ideas? Or just examples?

Here is an example. Your message is:     PATTERN("pattern", "1023", new MessageFormat("{0}: does not match the regex pattern {1}"), PatternValidator.class, 15),

This lists the regex pattern.  Let's say it was a zip code regex.  Instead of saying something like  'does not match the regex pattern {^\d{5}(?:[-\s]\d{4})?$', I would like to return a message such as 'invalid zip code'.  Ideally there wouldn't be one message for all regex's and I could taylor it in some way like that.   But if that solution would be too complex then maybe just replace or give an additional user message.  The idea would be to return end-user (not developer) acceptable messages.  It would be nice if the json schema api let you override the error message as part of the json schema document or if you do nothing then use the default.

**Comment by stevensouza** [comment]
Example:
 ```
           "zip": {
              "type": "string",
              "pattern": "^[0-9]{5}$",
              "$errorMessage": "Invalid zip code format"
            }
```

If the developer doesn't provide "$errorMessage" or something similar then a default message would be used.  

I realize this may not be a great solution as it is not part of the json schema standard, but would be a nice improvement if possible.  Maybe something similar is already a part of the standard or could be introduced?

**Comment by stevehu** [comment]
@stevensouza I understand your ideas and we can do something to a certain extent. However, we do have some generic validators like format and pattern, etc. cannot be handled this way. In my opinion, the error message from the API should be translated before showing it to the end-users and it should be as specific as possible. This will assist the API consumer to correctly implement the application. There are three types of consumers: internal, partner and public. If a public consumer builds an app to access open banking API and receives "invalid zip code format", what he/she should do?

**Comment by stevensouza** [comment]
<< If a public consumer builds an app to access open banking API and receives "invalid zip code format", what he/she should do?>>
I have a use case where our business managers and project managers tell us what the error messages should be.  I have no control over that.  'Invalid zip code format' is just an example.  Zip code is a relatively simple regex, but still none of our end users have ever heard of a regex and so the default message would be gibberish to them.  'Most users would prorbably know what Invalid zip code format' meant or if not we may need to change that message too.  In the end the user will have to read our message and correct the data on the web app input screens.  They don't know that behind the scenes they are getting a json schema error message.  
 
Another example is that the front end uses picklists to for example let a user enter a US state (OH, VA, MD, etc).  If a front end developer sends our backend the wrong data then we want to send some message back.  Say it is 'Your state selection is invalid'.  However, we wouldn't want to display the default enum error that lists all 50 states to the user.  

So the general idea is that as developers we are told what our error messages should be and they will most always not be the default ones returned by the json validator code.

**Comment by stevehu** [comment]
@stevensouza I understand your use case and the best way to handle that would be a message translation at the UI level. This is what I do most of the cases. The error message for UI developer and the error message to the end-user should be different. In Canada, the UI message must be in both English and French.

**Comment by stevehu** [comment]
Based on the conversation above, we still need to figure out if we can enhance the library to provide a way to customize the error messages. This is not a high priority through as the caller is translating the messages in most of the cases. Let's keep this issue open for a while to see if we can find a concrete solution.

**Comment by Kingnaoufal** [comment]
Hi,
Im interested on this feature as the current messages are unclear for the end user when using complexe logic.
I guess having a message validation on property definition or in the allOff, anyOff can be really helpful otherwise the validation will fail without giving any clear message where the JSON provided is correct.

**Comment by stevehu** [comment]
There are two distinct issues that we need to work with. First, we need to review the current messages to ensure it clearly shows the exact error with proper context information. Second, we need to find a way to ensure that users are capable of providing customized error messages to display to the end-users. I am open to all recommendations.

**Comment by Kingnaoufal** [comment]
Hi,

I was having a discussion on slack channel of JsonSchema and they suggest to choose a library that implement 2019-09 specification in order to extend the language and provide a way to customize the library by adding a plugin on it
As an example: https://github.com/epoberezkin/ajv-errors
