### ISSUE TITLE
Validating against a definition in a schema

### ISSUE THREAD

**Issue by KevinMitchell** [networknt/json-schema-validator#251]
My schema includes a large number of definitions.  I can successfully validate a JsonNode against the whole schema retrieved via a URL.  But now I have a need to validate against some of the named definitions.  I could split the schema into lots of schemas, each one corresponding to a definition in the original source.  But that would be harder to maintain, require multiple round trips to access all the definitions etc.  So is there a way to validate against a definition?  I thought there might be a way to take a JsonSchema, extract a definition from the instance, and be able to view it as another JsonSchema and validate against it.  But the API doesn't look like it works like this.  So is there another way to achieve this goal without having to split the schema into lots of sources?

Thanks
Kevin

**Comment by stevehu** [comment]
@KevinMitchell The API accepts a schema and an input JSON object. If you want to only validate one of the definitions, you can parse the schema and extract the definition and call the schema validator.

**Comment by KevinMitchell** [comment]
Thanks for the suggestion.  Just to be clear, I'm not trying to validate a definition.  I'm trying to validate a Json object against a definition in the schema, rather than against the whole schema.  It's true I could download the whole schema, parse it, build another schema with the chosen definition as the root, build a JsonSchema object from that, and then use it to validate a Json object.  But that feels time-consuming compared to just being able to validate the JsonObject against a definition in the schema, rather than the schema root.  Particularly as internally such functionality must exist whenever a $ref to the definition appears in the schema.  But maybe I've just misunderstood your suggestion?

**Comment by stevehu** [comment]
Once a schema is parsed, it would be very easy to locate the definition you mentioned and use it as the parameter to call the validation would be the fastest. You have to ensure that the schema and the JSON object are matched.
