### ISSUE TITLE
NOT validator is not working as it should?

### ISSUE THREAD

**Issue by raulcuth** [networknt/json-schema-validator#253]
I was testing the NOT validator, i want a value to not be in an enum. I have this piece of the schema:
`{
  "definitions": {
    "TypeDetails": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "category": {
          "type": "string",
          "not": {
            "enum": [
              "AUTHENTICATION",
              "AUTHORIZATION"
            ]
          }
        }
      }
    }
  }
}`

When i validate it online(for example here: [http://json-schema-validator.herokuapp.com/]) it works, but when i validate it using the library, it still requires a value that is present in the enum.

If I pass the value "WHATEVER", it throws the following error: 
`does not have a value in the enumeration [AUTHENTICATION, AUTHORIZATION]`

If i pass the value present in the enum("AUTHENTICATION"), the following error occurs: 
`should not be valid to the schema "not" : {"enum":["AUTHENTICATION","AUTHORIZATION"]}`

Is this not supported yet? Or am I doing something wrong?

**Comment by stevehu** [comment]
The NOT validator is supported a long time ago but I don't know if there is a defect in the implementation. I will create a separate test case from the [standard test suite](https://github.com/networknt/json-schema-validator/blob/master/src/test/resources/draft2019-09/not.json) and debug into it. I am busy today and will take a look at the weekend. Thanks for raising it. 

BTW, if you are interested, you can create a new test case called something like notEnum.json  and debug into it.

**Comment by raulcuth** [comment]
After further investigation I found out this **only** happens if i set `failFast` to true.
What i think is happening is that it checks first if the value is in the enum and it fails(because it is not) and if you put the value that is in the enum, the NOT validator applies afterwards. So it is something about ordering? the order in which the validators apply?
I can also make a pull request for the `notEnum.json` test if it helps

**Comment by stevehu** [comment]
The failfast is an experimental feature and it doesn't work with complex scenarios. Please don't use it until it is refactored. Since we have found the root cause, there is no need to create another test case. Thanks a lot for the clarification.

**Comment by raulcuth** [comment]
Ok, got it. Thanks a lot for your time. I think this issue can be closed then.
