### ISSUE TITLE
Forward references

### ISSUE THREAD

**Issue by KevinMitchell** [networknt/json-schema-validator#254]
Hi,
Does the validator support forward references in the schemas?  My example schema appears to be valid according to the various online checkers, but the library complains about a forward reference, i.e. a $ref to a definition later in the file.  Are such forward references supported by the library?  Do I have to change some setting to enable this?

Thanks

**Comment by stevehu** [comment]
@KevinMitchell It is supported and most of the OpenAPI specifications have the definition at the end of the files. Could you please give us more detail about your scheme and the error message? It would be great if you could create a PR with a test case for us to debug into it. Thanks.

**Comment by KevinMitchell** [comment]
Hi Steve,

Thanks for the confirmation that forward  references work. I’ve now tracked down where the error is coming from, and I think the problem is due to how I was trying to use your API.

So in my example the code successfully built the schema. I then executed
```
JsonNode refSchemaNode = rootSchema.getRefSchemaNode("#/definitions/foo”);
JsonSchema refSchema = factory.getSchema(refSchemaNode);
```
And it’s this second call to build a schema that produces the error about the reference.  The intention was to build another version of the original schema, but where the root was a reference to one of the definitions, `foo` in this case.

Now the problem in my code seems obvious.  The `refSchemaNode` instance isn’t connected to the original schema, and so the reference can’t be resolved when trying to build `refSchema`.  

So I think I understand why it was failing, but I’m not sure how to build the new JsonSchema instance efficiently using the API without copying all the definitions.

Cheers

Kevin

**Comment by stevehu** [comment]
As you are using a subschema to do the validation, you must de-reference and copy all the definitions into the subschema. Or you just create smaller schema files with remote references.

**Comment by KevinMitchell** [comment]
OK, thanks for the suggestions.  I think using remote references is the simplest solution for now.  So if I create JsonSchema instances for lots of small schema files containing just a remote reference to different definitions in the same base schema does the library copy all the definitions into each JsonSchema, or does the "base" schema just get built once and is then shared by all the JsonSchema instances that reference it?  If they each get a copy then providing a validation method that can take a local reference as a starting, rather than the root, would seem a worthwhile addition to improve efficiency by avoiding all the copying/duplication?

Thanks for your help
Kevin

**Comment by stevehu** [comment]
You can put all the definitions into one shared remote schema and break you big schema to smaller schemas that match the data you are trying to validate. These schemas will have reference to the remote shard schema.
