### ISSUE TITLE
Macro support

### ISSUE THREAD

**Issue by SridharSubramaniam** [networknt/json-schema-validator#256]
Hi,

Is there a way to do something equivalent to macro in ajv? Ability to provide a dynamic schema on a keyword.

https://ajv.js.org/custom.html

**Comment by stevehu** [comment]
The library is based on Java which is a static compiled language. Unlike Javascript that you can dynamically add new functions or new validators, we can only add this first and make the function or validator available during the runtime.

**Comment by SridharSubramaniam** [comment]
Hmm. The schema is known upfront. It's more preprocessing that makes it available - isn't it?

Ability to return altered schema pre-validation? No?

**Comment by stevehu** [comment]
I don't think it is pre-processing. All the extension must be compiled and made available to invoke like all validators.
