### ISSUE TITLE
How to add default values from JSON schema to a document

### ISSUE THREAD

**Issue by kkamenev** [networknt/json-schema-validator#257]
I need to add default values defined in the schema if the values are missing in the given document. Is there a way to do that with this library?

**Comment by stevehu** [comment]
@kkamenev Sorry. Could you please clarify what you want to do? If possible, could you please give us an example schema and data as well as the reference document of JSON schema?

**Comment by kkamenev** [comment]
@stevehu Here's what I'm trying to do. I'm typing it off the top of my head, so it might be not totally correct, but you should get the idea.

Schema:
`{
  "type": "object",
  "properties": [
    "productName": {
	  "type": "string"
	},
	"productVersion": {
	  "type": "string",
          "default": "1.0"	  
	}
  ],
  "required": ["productName"]
}`

Input document:
`{
  "productName": "A"
}`

Expected transformed document:
`{
  "productName": "A",
  "productVersion": "1.0" // default value from the schema
}`

I thought that should be quite a common use case - why have default values if there's no way to incorporate them into your document - but I found surprisingly little info on that. Am I trying to do something totally wrong?

**Comment by stevehu** [comment]
Default is a keyword of JSON schema designed for JSON processing but it is not for validation. 

https://json-schema.org/understanding-json-schema/reference/generic.html

**Comment by kkamenev** [comment]
I understand. I just hoped that there would be some way in this library to achieve that. Are you aware of some tool that would apply the transformation I need?

**Comment by stevehu** [comment]
Sorry. I don't know any tool that is working with the default keyword. There is a list of tools on the json-schema website and you might find something useful.

**Comment by kkamenev** [comment]
Thanks for your help anyway
