### ISSUE TITLE
Making getValidators method public on JsonSchema class.

### ISSUE THREAD

**Issue by prashanthjos** [networknt/json-schema-validator#269]
We wanted to make getValidators method public on JsonSchema.java. We have a use case where we want to get all RefValidators for given JSON Schema and run through them to write our Own custom logic.

**Comment by stevehu** [comment]
I don't think there is an issue to expose the method. Please make the change in the same PR. Thanks.

**Comment by prashanthjos** [comment]
Sure. Also I see the newSchema method is private in JsonSchemaFactory. It would be helpful if this method is protected so that we can create our own subclasses of JsonSchema class and override or add our own behaviour.

**Comment by prashanthjos** [comment]
@stevehu PR is updated with changes.

**Comment by stevehu** [comment]
Resolved in this PR https://github.com/networknt/json-schema-validator/pull/268
