### ISSUE TITLE
Docs: 404 Validators Usage Reference

### ISSUE THREAD

**Issue by darivs** [networknt/json-schema-validator#270]
Aloha,

The provided link (https://github.com/networknt/json-schema-validator/blob/master/src/test/resources/tests/if.json) to the test cases in your [validator docs](https://github.com/networknt/json-schema-validator/blob/master/doc/validators.md) seems to be outdated.

Have a nice day!

**Comment by stevehu** [comment]
@darivs Thanks a lot to raise it. I will take a look and get it fixed.

**Comment by darivs** [comment]
At the bottom of your validator docs (https://github.com/networknt/json-schema-validator/blob/master/doc/validators.md) which are linked in the README.md (https://github.com/networknt/json-schema-validator#validators)

**Comment by stevehu** [comment]
@darivs Thanks a lot for raising it. It is fixed with the latest official test cases.
