### ISSUE TITLE
Parameterized JSON Schema

### ISSUE THREAD

**Issue by prashanthjos** [networknt/json-schema-validator#271]
Are there any initiatives or future enhancements to support parameterized JSON Schema’s. For example the length of a specific JSON Node of type string is determined dynamically at runtime by the application rules rather than defining statically or a $ref attribute is determined at runtime. We want to pass such parameters or variables at runtime and generate the schema dynamically with this parameters replaced. 

For example a parametrized  JSON schema might look like this where maximumLength is a variable passed at runtime.

{
   .....
  maxLength: ${maximumLength}
}

**Comment by stevehu** [comment]
This has been discussed in this issue. 

https://github.com/json-schema-org/json-schema-spec/issues/826

**Comment by prashanthjos** [comment]
Got it. Thank you.
