### ISSUE TITLE
RequiredValidator possibly returning wrong path

### ISSUE THREAD

**Issue by ThanksForAllTheFish** [networknt/json-schema-validator#278]
First of all, please apologies if this is the wrong channel for what it might turn out to be a question more than an issue. I was struck by `RequiredValidator` and the way it associated `ViolationMessage` is built.

tl;dr: Given a sample schema like

```
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "title": "Sample",
  "description": "Sample",
  "type": "object",
  "properties": {
    "field": {
      "description": "A field",
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        }
      },
      "required": [
        "label"
      ]
    }
  }
}
```

a json body like

```
{ 
  "field":{}
}
```

when calling `schema.validate(json)` the violation message path is `$.field`. This is of course correct, but wouldn't it be more precise to have `$.field.label`? I checked the implementation at https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/RequiredValidator.java#L52 at `label` is passed as arguments because the corresponding was missing, but that is a given considering the validation fails on a required field. Am I missing something?

*Context*

To give a bit more context, I am trying to use json schema to validate api calls in a Spring project, and I need path in order to provide a meaningful message for the caller of my api. I feel in the case described the right path is `$.field.label`, so that an hypothetical ui could exactly pinpoint the input text that was not filled

**Comment by stevehu** [comment]
@ThanksForAllTheFish This issue has been discussed on this [issue](https://github.com/networknt/json-schema-validator/issues/245). We need to find a better solution to resolve all related issues together.

**Comment by ThanksForAllTheFish** [comment]
Oh sorry, I am new to json schema and though I went through existing issues (the title at least) before opening this one I did not realise they were related. Thanks for the quick feedback.

**Comment by stevehu** [comment]
I am open to all recommendations and there is an issue to make the error message customized.
