### ISSUE TITLE
EmailValidator use ValidatorTypeCode Datetime

### ISSUE THREAD

**Issue by avan2s** [networknt/json-schema-validator#281]
Hi,

i saw that the [EmailValidator](https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/format/EmailValidator.java) class is instantiated as ValidatorTypeCode.DATETIME. Is there a reason why it is not ValidatorTypeCode.FORMAT? From my understanding it should be format, because we write in our json schema:
`
{
  "properties": {
    "email": {
      "type": "string",
      "format": "email"
    }
  }
}
`
If i'am right please change it to ValidatorTypeCode.FORMAT please. Otherwise the validation messages will have a confusing type in my opinion.

Best regards,
Andy

**Comment by stevehu** [comment]
@avan2s The EmailValidator is borrowed from Sandeep and I didn't pay attention to the usage at the time. What do you mean instantiated as a DATETIME? Could you please point me out the line of the code? Thanks.

**Comment by avan2s** [comment]
Hi @stevehu 

it is in line 139 in the constructor of the EmailValidator, when super method is called. 
`super(schemaPath, schemaNode, parentSchema, ValidatorTypeCode.DATETIME, validationContext);`
This is causing that whenever i type in an invalid email, the created Validation message will be of type "DATETIME" instead of "FORMAT". But a wrongly formatted email should be of type "ValidatorTypeCode.FORMAT".

Thanks and best regards
Andy

**Comment by stevehu** [comment]
@avan2s Thanks a lot for pointing it out. This a bug and I will get it fixed ASAP.

**Comment by stevehu** [comment]
I have changed it to format and the error message will be something like this.

```
$: does not match the 2962 pattern email
```

**Comment by stevehu** [comment]
@avan2s Again, thanks a lot for your help. I have released 1.0.38 and the following is the release note.

https://github.com/networknt/json-schema-validator/releases/tag/1.0.38

**Comment by avan2s** [comment]
Thank you @stevehu for the fix :-)

best regards
