### ISSUE TITLE
Unclear on how to use this validator

### ISSUE THREAD

**Issue by sharonoc** [networknt/json-schema-validator#284]
I am new to json validation.  I am not finding documentation that makes the usage of this validator very clear.
I have the following schema:
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "object",
  "properties": {
    "trackingEvent": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^FOO$"
        }
      }
    }
  }
}

And I am trying to validate the following data:
{
  "name": "DETAILS_SEEN"
}

This should fail but it does not.  Here is my code.
ObjectMapper objectMapper = new ObjectMapper();
            try {
                JsonNode jsonInput = objectMapper.readTree(input);
                System.out.println(jsonInput);

                JsonSchemaFactory factory = JsonSchemaFactory
                        .builder(JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V201909))
                        .objectMapper(objectMapper)
                        .build();

                System.out.println(schemaURL);
                String schemaJson = new String(Files.readAllBytes(Paths.get(schemaURL)));
                JsonSchema schema = factory.getSchema(schemaJson);
                System.out.println(schema);
            } catch (JsonProcessingException e)
            {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }

I would appreciate any help in understanding the correct implementation of using this validator.
Thank you.

**Comment by stevehu** [comment]
@sharonoc There are test cases in the source code to demonstrate how to use the library. Thanks.
