### ISSUE TITLE
Document schema compatibility matrix

### ISSUE THREAD

**Issue by pradeepsixer** [networknt/json-schema-validator#288]
Currently, to check whether this library supports validation of a keyword as defined in one of the schemas, we have to create a program to do it.

Creating a document that lists the compatibility with different schema versions would make this easier.

**Comment by stevehu** [comment]
The information can be found in the following java file and the last number indicate which version of specs is supported. 

https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/ValidatorTypeCode.java

To interpret the versions, take a look at this document. 

https://github.com/networknt/json-schema-validator/blob/master/doc/specversion.md

I do agree that creating a separate document will be much better and I would be so happy to accept a PR.

**Comment by pradeepsixer** [comment]
Thanks @stevehu . I'll create a PR for this. 🙂
