### ISSUE TITLE
Unable to validate JSON Schema of type String

### ISSUE THREAD

**Issue by JosephCavanaghTR** [networknt/json-schema-validator#290]
The JsonSchema validate method requires a JSONNode is passed in. This leaves a gap in validation when the schema specifies a type of String.

Example Schema
```
{"$schema":"http://json-schema.org/draft-07/schema#","$id":"https://example.com/gcs.encoder.object.json","type":"string"}
```
Example valid json
```"2020-10-09"```

There is no way to create a JSONNode out of this valid json string.

**Comment by stevehu** [comment]
@JosephCavanaghTR I agree with you that both the schema and the string are valid; however, I don't think users will use a library like this to validate a string only. In my opinion, I don't think we should consider this edge case. If you know any use cases, please let us now and a PR is always welcomed.

**Comment by JosephCavanaghTR** [comment]
@stevehu  Thanks for the quick response.

After digging more, we found that it is an issue with escaping the json. The validator does appear to work with the instance, but the string needs to be
```
String sampleString = "\"2020-10-09\""
```
Effectively, this makes it a JSON string. I am closing this issue.
