### ISSUE TITLE
Validation of anyOf is schema order dependant in some cases

### ISSUE THREAD

**Issue by soinio** [networknt/json-schema-validator#295]
Schema:

```
{
  "id": "classpath:/schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "oneOf": [
    {
      "required": [
        "requiredprop"
      ],
      "properties": {
        "requiredprop": {
          "type": "string"
        }
      }
    },
    {
      "properties": {
        "forbiddenprop": {
          "type": "null"
        }
      }
    }
  ]
}
```

Document: `{ "other": "stuff" }`

This should be accepted with the second oneOf alternative. It is accepted if I reverse the order of oneOf array members in the schema. But with the stated schema, validation fails with message `$.requiredprop: is missing but it is required`.

Complete test program attached. There is similar existing issue #209 but that blames failFast which is not the case here.

[json-validate-test.zip](https://github.com/networknt/json-schema-validator/files/4688163/json-validate-test.zip)

**Comment by soinio** [comment]
Sorry for typos in original text and program, should all be fixed now. It should probably be noted, that if I set the "forbiddenprop" explicitly to null in the document then validation succeeds with either schema oneOf order.

**Comment by soinio** [comment]
The issue persists even if I replace the somewhat dubious null-type schema with more explicit "property must be missing or null" schema below. In this case also the validation succeeds if I but this before the requiredprop-schema or if I set the property to null value in the document, but fails if the document is missing the "forbidden" property altogether.

```
    {
      "not": {
        "required": ["forbiddenprop"],
        "not": {
          "properties": {
            "forbiddenprop": {
              "type": "null"
            }
          }
        }
      }
    }
```

**Comment by stevehu** [comment]
@soinio I missed this issue until today when I review the closed issues for the next release. Any findings recently? I will take a look when I have some free cycles. Thanks for raising it.

**Comment by soinio** [comment]
No I do not have any further info. We modified our schemas to use "oneOf" ordering that seems to work, but are naturally still eagerly waiting for a real fix. Thank you.

**Comment by anagrius** [comment]
We are seeing issues with oneOf aswell.

This https://www.jsonschemavalidator.net/s/jGsTwlzm should be a valid document, yet networknt does not accept it, giving the error: 

$.sharedTimeInterval.end: is missing but it is required

and according to the schema, end is only required when isLive=false
