### ISSUE TITLE
validation of subschema for draft7 is being skipped

### ISSUE THREAD

**Issue by tukaram57** [networknt/json-schema-validator#296]
Hello,

I have below object structure
```
class A{
int d;
B b;
}
class B{
int c;
}
```
for which, below json schema is being generated
```
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "definitions" : {
    "B" : {
     "type" : "object",
      "properties" : {
        "c" : {
          "type" : "number"
        },
"A" : {
     "type" : "object",
      "properties" : {
        "d" : {
          "type" : "number"
        },
    "b":{
"$ref": "#/definitions/B"
}
},
"anyOf" : [ {
    "$ref" : "#/definitions/A"
  }]
}
```
When I try to validate it for Draft 7, it never validate inner object B definition. Whats going wrong here? 
```
JsonSchemaFactory factory = JsonSchemaFactory.builder(JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V7)).objectMapper(mapper).build();
    JsonSchema schema = factory.getSchema(schemaContent);
 Set<ValidationMessage> errors = schema.validate(node);
```

**Comment by stevehu** [comment]
I am trying to reproduce the issue but it looks like the schema is not a valid JSON. Would you be able to submit a PR with a test case to reproduce the issue? Thanks.

**Comment by tukaram57** [comment]
> I am trying to reproduce the issue but it looks like the schema is not a valid JSON. Would you be able to submit a PR with a test case to reproduce the issue? Thanks.

I just added it for demo purpose. Will add exact one soon if you need so.

**Comment by stevehu** [comment]
Yes. Please. Both the JSON and Scheme are not valid above and I don't want to guess your use case. Thanks.

**Comment by tukaram57** [comment]
It was because of "anyOf" tag in schema. sorry for the confusion.

**Comment by tukaram57** [comment]
Hi, Sorry to reopen this thread bu this seems related. 
- How I can convert **anyOf** to **allOf** in generated Schema.

**Comment by stevehu** [comment]
What do you mean to convert? They are two different keywords. For details, please refer to the specification.
