### ISSUE TITLE
"ValidationContext" using is not correct in UUIDValidator

### ISSUE THREAD

**Issue by qiunju** [networknt/json-schema-validator#297]
https://github.com/networknt/json-schema-validator/blob/cf3b4fe8f52817d0686892f20ecbfca04d7aff5f/src/main/java/com/networknt/schema/UUIDValidator.java#L36

Hi, @stevehu 
I guess what we want to verify here is _UUID_, so it should be _**ValidatorTypeCode.UUID**_.
I created a PR for it: https://github.com/networknt/json-schema-validator/pull/298/files
Please correct if I'm wrong. Thanks!

**Comment by stevehu** [comment]
@qiunju Yes. It is a copy/paste error. Thanks a lot for fixing it.
