### ISSUE TITLE
Coverage ?

### ISSUE THREAD

**Issue by pgKuantic** [networknt/json-schema-validator#3]
Hi @stevehu , 
I am interested by using your project. 
Can you give me more information about the current status of this project ? 
What is working, not working, known issues, missing features ...
Thanks, 

Paul

**Comment by stevehu** [comment]
@pgKuantic I have update the test suites from official site and rerun the tests and found four issues that are documented in readme.md. This library has been used in light-java(https://github.com/networknt/light-java) microserices framework. And as a standalone library, it validates json shemas for hundreds APIs on production now. Let me know if you have specific concerns.
