### ISSUE TITLE
How to use to validate real data for Draft-07

### ISSUE THREAD

**Issue by pjain287074** [networknt/json-schema-validator#300]
Hi 
I am new to maven. 
Can you please help to understand how can i use this project to validate my JSON. I Want maven to  fail if any parameter of my JSON is not as per the  Defined JSON schema(or DraftV7)

**Comment by stevehu** [comment]
You can use any build tool like Maven or Gradle. Choose whichever you like.

**Comment by pjain287074** [comment]
Do i need any plugins to use this in maven pom....
Does it validate Draftv7 schema?

**Comment by stevehu** [comment]
If you are preferring javac, then you don't even need Maven. Yes. it validates draftv7 schema.

**Comment by pjain287074** [comment]
Happy to hear this but i have a mvn based project. Could you please please
help how can i integrate this with my existing project?

As of now i am using json schema validator  plugin in my maven project
which does not support Draftv7. Refer below refrence project

https://github.com/groupon/json-schema-validator/blob/master/README.md

Its validating schema based on draftv4.but not validating if-then-else
which is added in Draftv7

Although i tried and added all dependancies which are specified in your
repo in pom.xml of my maven project.But some how it doesn't worked for me.
It did not validated
 if-then-else that i have defined in json schema or may be i have done
something wrong.

**Comment by stevehu** [comment]
The project is just a library and like other dependencies, you need to add it to the pom.xml file first. Then you need to add the code to validate. Take a look at the test cases and you can find the examples on how to use it.
