### ISSUE TITLE
Unable to use $data reference

### ISSUE THREAD

**Issue by avan2s** [networknt/json-schema-validator#302]
Hello,
i try to use the [$data reference](https://github.com/json-schema-org/json-schema-spec/issues/51) in order to read some data from the validated json. I have the following jsonschema [(coming from this example)](https://ajv.js.org/#data-reference)

> {
>   "properties": {
>     "smaller": {
>       "type": "number",
>       "maximum": { "$data": "1/larger" }
>     },
>     "larger": { "type": "number" }
>   }
> }

and this valid json to validate:

> {
>   "smaller": 1,
>   "larger": 2
> }

it is giving me this error:

> java.lang.RuntimeException: maximum value is not a number

is $data supported in this library? Are there any ideas how to make it work? Expected behaviour would be, that it will set the maximum value dynamically to the value located under "larger".

I would be glad for your help or any ideas.

Thanks a lot and best regards
Andy

**Comment by stevehu** [comment]
I don't think $data is in the latest JSON schema. Could you please point me out the right document? Thanks.
