### ISSUE TITLE
How to fail on unkown properties ?

### ISSUE THREAD

**Issue by r0main** [networknt/json-schema-validator#303]
Hi,

Is it possible to fail the schema validation on unknown properties ?

Let's say you have this schema :
```
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "name",
    "age"
  ],
  "properties": {
    "name": {
      "$id": "#/properties/name",
      "type": "string"
    },
    "age": {
      "$id": "#/properties/age",
      "type": "integer"
    }
  }
}
```

And you validate this JSON against the previous schema :
```
{"name":"Romain", "age":32, "age2":32}
```

Is it possible to fail the validation because `age2` is unknown in the schema.

Thank you.

Best regards,
Romain.

**Comment by stevehu** [comment]
https://json-schema.org/understanding-json-schema/reference/object.html

```
"additionalProperties": false
```

**Comment by r0main** [comment]
Hi Steve,

This works like a charm, thanks a lot for the quick reply !

Best regards,
Romain.
