### ISSUE TITLE
strong type support?

### ISSUE THREAD

**Issue by samw2008** [networknt/json-schema-validator#304]
I would like you to support strong type verification. e.g. any field which is not in schema will be failed in verification. This can be changed in  SchemaValidatorsConfig and PropertiesValidator files.

**Comment by stevehu** [comment]
@samw2008 Could you please elaborate a little bit more? Is this covered by the additional properties like this issue?

https://github.com/networknt/json-schema-validator/issues/303

**Comment by samw2008** [comment]
I give an example to explain what I mean,  
    schema :
                {
                        a:{
                        
                        },
                        b:{

                        }
                }

    json:    
                {
                        a:{

                        },
                        b:{

                        },
                        c:{
                          
                        }
                }
In your implement, "c" field will be allowed.  But we would like to not allow "c" field. 
This feature can be option which is defined in SchemaValidatorsConfig.  
Thanks!

**Comment by stevehu** [comment]
add additional properties to false and it will work.

**Comment by samw2008** [comment]
Thanks!
