### ISSUE TITLE
Make runtime dependency to org.jruby.joni:joni optional

### ISSUE THREAD

**Issue by Buuhuu** [networknt/json-schema-validator#307]
In an OSGI context json-schema-validator requires the following package imports to be resolved:

```
com.fasterxml.jackson.databind,version=[2.10,3)
com.fasterxml.jackson.databind.node,version=[2.10,3)
org.apache.commons.lang3,version=[3.5,4)
org.jcodings
org.jcodings.specific
org.joni
org.joni.exception
org.slf4j,version=[1.7,2)
```
where all but `org.jcodings`, org.jcodings.specific`, `org.joni` and `org.joni.exception` are available as OSGI bundles publicly. `org.jruby.joni:joni` unfortunately is not archived as OSGI bundle and so requires a custom rewrapping.

From [doc/ecma-262.md](https://github.com/networknt/json-schema-validator/blob/master/doc/ecma-262.md) I understood that the default is java.util.Regex anyway so the import of packages provided by `org.jruby.joni:joni` can be marked optional for resolution and can be provided when necessary.

**Comment by stevehu** [comment]
I am not familiar with OSGI but will try my best to support it as there are some users who are using it. I am going to upgrade the Jackson to 2.10.4 and release another version soon. Thanks a lot for your help.

**Comment by Buuhuu** [comment]
Hey and thanks for merging that quickly. Unfortunately that was not the whole story. While working well in an integration test I was facing errors on an actual environment. This is because the now optional declared classes are in fact loaded by the PatternValidator. In created #311 which splits the PatternValidator into 2 classes, one for Java and one for ECMA262, loading o nly the one necessary per configuration.

**Comment by Buuhuu** [comment]
Hey, do you plan to cut `1.0.42` sometimes soon? I'm asking as the latest change unfortunately didn't made it in `1.0.41`.

**Comment by stevehu** [comment]
1.0.42 has been released. Sorry, I was extremely busy the last several days.
