### ISSUE TITLE
How remove case sensitive for JSON keys

### ISSUE THREAD

**Issue by chandrahasan** [networknt/json-schema-validator#31]
Schema mentioned:  {"name" : ...} 
Passing payload : {"Name": ...}

Error showing currently : 
1. "name" is required 
2. "Name" not allow additional property 

Kindly advise any option to ignore only case validation. I want to allow all case should accept(camel,mix,small) ,make in-case sensitive for JSON keys.

**Comment by stevehu** [comment]
@chandrahasan JSON is case sensitive and the validator is implemented that way based on spec. I am wondering if you could share your use case that requires case insensitive JSON keys.

**Comment by chandrahasan** [comment]
@stevehu Hi, its a requirement to allow case insensitive JSON keys. Any possible to do that

**Comment by stevehu** [comment]
César Dragunsky is working on the spi_architecture branch to enable customization for the validators from users. Once that feature is completed, it should be easy to add your own replacement for the default validator in the classpath. Meanwhile, you can clone and build your own jar with customized implementation. Thanks.

**Comment by cesarulo** [comment]
Hey guys,

  correct, I was working on it. I took a little time off but I should be back to it in the next day or two. I'll try my best to be expeditive about it, I'll work with Steve on it and we'll let everyone know when it's ready.

**Comment by chandrahasan** [comment]
@cesarulo Any updates on this case

**Comment by stevehu** [comment]
I don't think we should break the rule to implement something like this.
