### ISSUE TITLE
[Discussion] Source code target version is 1.6. Any plan to switch to 1.8?

### ISSUE THREAD

**Issue by Subhajitdas298** [networknt/json-schema-validator#310]
The existing source code target is 1.6. While test target version is 1.8.  Also, to note, this library supports Java 8 (1.8) and up at the moment. There can be several code structuring improvement to be had, if witch to 1.8. Is there any plan to change target version to 1.8?

**Comment by stevehu** [comment]
@Subhajitdas298 Some users are developing on an older version of Andriod and only Java 6 is supported. This is why the released target is based on 1.6 JDK. Some of the test cases were using Java 8 features before but I think I have converted them to Java 6 already. Let's keep the Java 6 until the older version of Andriod is phasing out. Thanks.

**Comment by Subhajitdas298** [comment]
> @Subhajitdas298 Some users are developing on an older version of Andriod and only Java 6 is supported. This is why the released target is based on 1.6 JDK. Some of the test cases were using Java 8 features before but I think I have converted them to Java 6 already. Let's keep the Java 6 until the older version of Andriod is phasing out. Thanks.

Ok. Test cases can be kept 8 without interfering, right?

**Comment by stevehu** [comment]
So far, I don't see any issue; however, I have changed a lot of them to Java 6 already. Some users might have running the test from the IDE with Java 6 if there are Java 8 test cases. There is a lot of extra work to support different environments at the same time; however, this is a community-driven project and we want to cover everybody if possible.

**Comment by Subhajitdas298** [comment]
Ok. Also on a side note, the library can be structured with more sub packaging. The project currently has 69 classes/interfaces in it's root package. Is there any issue, if restructured?

**Comment by stevehu** [comment]
I don't have any issues with restructuring at all. It was started with a small footprint and grow to the current size. I think at least we should move all validators to a separate package at the moment. If you have any further suggestions, please let us know.
