### ISSUE TITLE
implement propertyNames validator for v6, v7 and v2019-09

### ISSUE THREAD

**Issue by anagrius** [networknt/json-schema-validator#315]
```
{
  "$schema": "https://json-schema.org/draft-07/schema",

  "properties": {
    
    "filters": {
      "type": "object",
      "propertyNames": {
        "maxLength": 100,
        "minLength": 1
      }
    }
  }
}
```

Should not accept:
```
{
    "filters": {
     "": "123" 
    }
}
```

But the validation passes.

Here is an example of it failing in another implementation: 

https://www.jsonschemavalidator.net/s/cvPIboX7

**Comment by stevehu** [comment]
@anagrius I think the minLength is to validate the property value instead of the property name. The JSON should be written like this.

```
{
    "filters": {
     "123": "" 
    }
}
```

**Comment by anagrius** [comment]
Not when used inside propertyNames

**Comment by anagrius** [comment]
The goal here is to limit the length of the property name not the values. The linked implementation does it correctly.

**Comment by stevehu** [comment]
I got it. I will take a look. Thanks a lot for raising it.

**Comment by stevehu** [comment]
@anagrius The propertyNames wasn't implemented before as nobody in the team is using it. Could you please review the newly added validator and see if there are any issues? Thanks.
