### ISSUE TITLE
Can JSON schema enums be case insensitive?

### ISSUE THREAD

**Issue by HemantMJain** [networknt/json-schema-validator#33]
Is there an elegant way to make the enum case-insensitive?

**Comment by stevehu** [comment]
I am in a process to change the validator loading to SPI and might add a config file for these validators. I have a config module from light-4j framework that can load .yml config file which can be used to control behaviour of each validators. I cannot promise the time as there are too many projects are going on at the same time. Stay tuned.

**Comment by stevehu** [comment]
@BalloonWen @jiachen1120 We have a config file already and I am wondering if we should put this into the config to control the case-insensitive?

**Comment by Tryking** [comment]
@stevehu  Hi, Any update of controlling the case-insensitive?

**Comment by stevehu** [comment]
@Tryking @HemantMJain As this is an exceptional feature in the library and there is no demand from other users, I am wondering if you could help to submit a PR for the feature.

**Comment by piyushkumar13** [comment]
@stevehu I also have a requirement for having enums, constants as case insensitive.

**Comment by stevehu** [comment]
As this is not standard in the spec., we can only implement it with a configuration like `enum_const_insentive: true` or something like that. It would be very helpful if someone can submit a PR for it.

**Comment by stevehu** [comment]
Given there is no interest in this feature, this issue is closed.
