### ISSUE TITLE
Improve type validation of numeric values

### ISSUE THREAD

**Issue by oguzhanunlu** [networknt/json-schema-validator#334]
**Issue**
TypeFactory uses `jackson-databind`'s `JsonNode.isIntegralNumber` and `JsonNode.isNumber` to see if the node's type is integer or number, respectively. This result is used when comparing node type and schema type which is not precise enough in some cases.

https://github.com/networknt/json-schema-validator/blob/4ba09d5f978508f7bc9e96087252333ebe90e22a/src/main/java/com/networknt/schema/TypeFactory.java#L72-L75

**Scenario**
Assume that we have a schema where a property's type is `integer`.
Given a `DecimalNode(v)` where `v` is a value that can fit into `Long`, json-schema-validator thinks that node type is `number` and this results in [type failure](https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/ValidatorTypeCode.java#L63) as `number found, integer expected`

**Proposal**
Update line 72-73 in the snippet above as following (`canConvertToLong()` is defined for `DecimalNode` at `jackson-databind`)
```java
if (node.isIntegralNumber() || node.canConvertToLong())
    return JsonType.INTEGER; 
```

so that we can have a validator with better precision

**Comment by stevehu** [comment]
@oguzhanunlu Thanks a lot for raising the issue and provide a solution. Let me add some background information here so that others can see where this issue is from and why we should adopt your solution as a Java-specific implementation. 

```
Warning

The precise treatment of the “integer” type may depend on the implementation of your JSON Schema validator. JavaScript (and thus also JSON) does not have distinct types for integers and floating-point values. Therefore, JSON Schema can not use type alone to distinguish between integers and non-integers. The JSON Schema specification recommends, but does not require, that validators use the mathematical value to determine whether a number is an integer, and not the type alone. Therefore, there is some disagreement between validators on this point. For example, a JavaScript-based validator may accept 1.0 as an integer, whereas the Python-based jsonschema does not.

Clever use of the multipleOf keyword (see Multiples) can be used to get around this discrepancy. For example, the following likely has the same behavior on all JSON Schema implementations:

{ "type": "number", "multipleOf": 1.0 }
```
Given the above quote from the official site, I think we should leverage the Java language feature to support the Long type; however, the change might make the validator different than the Javascript implementation. As this is a community-driven implementation, I want to know the opinion of @everybody. The best solution is to support both and use the configuration to differentiate it. We just need to make the decision of which implementation is the default.

**Comment by oguzhanunlu** [comment]
Thanks for the quick response @stevehu !

Looking at [the implementation of `DecimalNode.canConvertToLong`](https://github.com/FasterXML/jackson-databind/blob/640f9982bd7ea84b271cb2b6ae9d3f4708cf7e9e/src/main/java/com/fasterxml/jackson/databind/node/DecimalNode.java#L64-L66) in jackson-databind, it seems that floating values smaller than maximum long, e.g. `1.4`, will be considered as `integer`, if we use the proposal I shared above, which would be wrong, so we need to use a better condition to check if the node value can fit into a Long and it doesn't have a fractional value.

Instead of the initial proposal, perhaps something as following:
```java
if (node.isIntegralNumber() || (node.canConvertToLong() && !node.asText().contains('.')))
    return JsonType.INTEGER; 
```

**Comment by oguzhanunlu** [comment]
Hi @stevehu , is there any update on this one? Or is there anything I can do to proceed here?

**Comment by stevehu** [comment]
@oguzhanunlu I think we should go ahead with the implementation.  Just make sure to keep the existing behaviour as default and the new feature can be enabled from the configuration. Could you submit a PR for this? Thanks.

**Comment by oguzhanunlu** [comment]
sure @stevehu , I'll open a PR, thanks!

**Comment by oguzhanunlu** [comment]
hey @stevehu , fyi, I just opened [the PR](https://github.com/networknt/json-schema-validator/pull/343) and wanted to share here as well in case you don't get notified

**Comment by stevehu** [comment]
@oguzhanunlu Thanks a lot for your help. I am working with customers these days and very busy. I am reviewing in my spare time and it will take a bit longer.

**Comment by oguzhanunlu** [comment]
I understand it @stevehu , no worries at all! I hope jackson-databind publishes 2.12.0 in the meantime.
