### ISSUE TITLE
NullPointerException at com.networknt.schema.JsonSchema.validate(JsonSchema.java:213)

### ISSUE THREAD

**Issue by kmalski** [networknt/json-schema-validator#335]
Hi, I am getting NullPointerException during parallel processing.
```
java.lang.NullPointerException
        at com.networknt.schema.JsonSchema.validate(JsonSchema.java:213)
        at com.networknt.schema.BaseJsonValidator.validate(BaseJsonValidator.java:100)
```
After some research, I found that it is probably about not set field `protected Map<String, JsonValidator> validators` in `JsonSchema`.
I think it is coming from this place in `JsonSchemaFactory`:
```java
public JsonSchema getSchema(final URI schemaUri, final SchemaValidatorsConfig config) {
        
            ...
            if (uriSchemaCache.containsKey(mappedUri))
                return uriSchemaCache.get(mappedUri);

            try {
                inputStream = this.uriFetcher.fetch(mappedUri);
                final JsonNode schemaNode = mapper.readTree(inputStream);
                final JsonMetaSchema jsonMetaSchema = findMetaSchemaForSchema(schemaNode);

                JsonSchema jsonSchema;
                if (idMatchesSourceUri(jsonMetaSchema, schemaNode, schemaUri)) {
                    jsonSchema = new JsonSchema(new ValidationContext(this.uriFactory, this.urnFactory, jsonMetaSchema, this, config), mappedUri, schemaNode, true /*retrieved via id, resolving will not change anything*/);
                } else {
                    final ValidationContext validationContext = createValidationContext(schemaNode);
                    validationContext.setConfig(config);
                    jsonSchema = new JsonSchema(validationContext, mappedUri, schemaNode);
                }
                uriSchemaCache.put(mappedUri, jsonSchema);
                jsonSchema.initialize();

                return jsonSchema;
            } 
            ...
    }
```
The initialization of the jsonSchema happens after putting it to cache. Another thread finds that it is in cache, tries to use it, schema is not initialized yet and exception it thrown. It is pretty unlucky scenario but this is my only idea.

Is it made on purpose that the schema is first put to the cache and then initialized? I thought that `JsonSchemaFactory` is thread safe, is it true? Thank you in advance for your help.

**Comment by stevehu** [comment]
@kmalski Thanks a lot for raising and analyzing the issue. Your analysis makes perfect sense. I remember the initialize was changed this way to resolve one of the issues and it might be the root cause. Have you tried to put it into the cache after initialize() is called?

**Comment by kmalski** [comment]
This is more complicated than I thought. Changing this order causes fail of test for mentioned by you issue #258. This looks like a bad design, because caching not ready to be used objects is not the best idea. Fixing this requires reading the old issue and taking into consideration current issue. Moreover I can still imagine creating same schema many times when many threads will find this condition ` if (uriSchemaCache.containsKey(mappedUri))` as `false` - this is not critical and should not be an error but still can be done better.

**Comment by mweber03** [comment]
I think I just saw this error in my code too. I'm using 1.0.47.

**Comment by mweber03** [comment]
I think it might be a concurrency issue. Can those maps become `ConcurrentMap`?

**Comment by mweber03** [comment]
Made a pull request with a fix: https://github.com/networknt/json-schema-validator/pull/377

**Comment by stevehu** [comment]
This has final completed with support for both lazy loading and eager loading depending on the use cases. The last piece is done in #406 to allow users to explicitly initialize all validators with a method call.

**Comment by flozano** [comment]
We are having trouble with `$ref` and latest implementation with initializeValidators:
```
java.lang.StackOverflowError
	at com.networknt.schema.JsonSchema.initializeValidators(JsonSchema.java:426)
	at com.networknt.schema.RefValidator.preloadJsonSchema(RefValidator.java:154)
	at com.networknt.schema.JsonSchema.initializeValidators(JsonSchema.java:427)
	at com.networknt.schema.BaseJsonValidator.preloadJsonSchemas(BaseJsonValidator.java:175)
	at com.networknt.schema.AllOfValidator.preloadJsonSchema(AllOfValidator.java:104)
	at com.networknt.schema.JsonSchema.initializeValidators(JsonSchema.java:427)
	at com.networknt.schema.RefValidator.preloadJsonSchema(RefValidator.java:154)
	at com.networknt.schema.JsonSchema.initializeValidators(JsonSchema.java:427)
	at com.networknt.schema.BaseJsonValidator.preloadJsonSchemas(BaseJsonValidator.java:175)
	at com.networknt.schema.PropertiesValidator.preloadJsonSchema(PropertiesValidator.java:140)
(...)
```
will try to set up a reproducing test later.
