### ISSUE TITLE
Switch to Jsoniter from Jackson?

### ISSUE THREAD

**Issue by stevehu** [networknt/json-schema-validator#34]
In my other projects, I am gradually moving away from Jackson to Jsoniter due to huge [performance difference](https://dzone.com/articles/is-protobuf-5x-faster-than-json). As many people are using this library with Jackson, I am wondering if we should support both or just discard Jackson as Jsoniter is very small and not depending on anything else. What do you think? Thanks.

**Comment by xaviarias** [comment]
Maybe should be supported as per #9.

**Comment by stevehu** [comment]
Yes. that is the desired approach if it is doable. However, the difference between DSL/Joniter and old style JSON parsers are too big. I am afraid that it is too hard to do. Will try it out first with a factory approach to start. It has to be done gradually as most of my projects are tied to Jackson at the moment and almost all my clients are using Jackson.

**Comment by xaviarias** [comment]
I ignore the internals of JSON parsers, but maybe worth give it a try and see if it's possible. I am also using Jackson and moving from `JsonNode` to other classes (e.g. Jasonite's `Any`) to validate data could be an issue. Thanks @stevehu !

**Comment by stevehu** [comment]
Yes. Will try that once the spi architecture is completed.

**Comment by stevehu** [comment]
More and more users are using this library with Jackson and it looks we have no choice to keep using Jackson.
