### ISSUE TITLE
propertyNames not work with enum or not enum

### ISSUE THREAD

**Issue by GuanDong** [networknt/json-schema-validator#342]
schema:
{"type": "object", "patternProperties": { "": { "enum": [1,2] } }, "propertyNames": { "enum":  ["a"] } }

data:
{"a": 1, "abc": 2, "abcd": 3}

validate with SpecVersion.VersionFlag.V201909 get errors:
$.abcd: does not have a value in the enumeration [1, 2]

**Comment by stevehu** [comment]
@GuanDong Good catch. The propertyNames only supports limited validation today based on the official test cases and we have another issue to add more validations against it. This should be addressed at the same time. 

https://github.com/networknt/json-schema-validator/issues/326
