### ISSUE TITLE
How turn off to many DEBUG logs

### ISSUE THREAD

**Issue by alexei-28** [networknt/json-schema-validator#349]
I use yaml to validate my json.

build.gradle

   
```
   implementation 'org.slf4j:slf4j-api:1.7.30'
    implementation 'ch.qos.logback:logback-classic:1.2.3'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.10.3'
    implementation 'org.apache.commons:commons-lang3:3.11'
    implementation("com.networknt:json-schema-validator:1.0.43");
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.11.3'


```
Nice it's work fine
smt like this:

```
init {
            val objMapper = ObjectMapper(YAMLFactory())
            val factory = JsonSchemaFactory.builder(JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V7)).objectMapper(objMapper).build()
            storesJsonSchema = factory.getSchema(FileUtils.readFileToString(File("myValidator.yml"), Charsets.UTF_8))
        }

   fun validateStore(storeJsonNode: JsonNode): Set<ValidationMessage>? {
            return storesJsonSchema!!.validate(storeJsonNode)
        }

```
Nice. 

But it's generate to many logs like this:

```
17:32.160 [qtp181078353-37] DEBUG com.networknt.schema.RequiredValidator - validate( {"name":"zapo"...
17:41:32.160 [qtp181078353-37] DEBUG com.networknt.schema.RefValidator - validate( {"en":"Eco...

```

How I can turn off this DEBUG logs?

**Comment by stevehu** [comment]
The library is using Logback and you can change the logging level with logback.xml in your application.

**Comment by BoDING1007** [comment]
I have similar issue, however our application is also using Logback to log our application level debug message, so we do not want to disable logging level. Any alternative solution to disable just validation debug message?

**Comment by stevehu** [comment]
@BoDING1007 @alexei-28 If I understand it correctly, you do want to turn on the debug for want to suppress the validation logging. Do you think it will work to change the logging level to trace for the detailed validation logs?

**Comment by BoDING1007** [comment]
> @BoDING1007 @alexei-28 If I understand it correctly, you do want to turn on the debug for want to suppress the validation logging. Do you think it will work to change the logging level to trace for the detailed validation logs?

@stevehu  Yes, I don't want to change my whole application log level, but only disable debug logs from validator. my application is a realtime acquisition, json message come in high frequency up to 10hz, we validate each message, but do not want to have this debug log every message appear in container. Any solution to change logging level only for validation logs

**Comment by stevehu** [comment]
A simple solution is that you create a logback.xml and set the logging level to info for com.networknt.schema package. I am guessing you have logback.xml already, then just add an entry to disable the debug for this package.

**Comment by BoDING1007** [comment]
> A simple solution is that you create a logback.xml and set the logging level to info for com.networknt.schema package. I am guessing you have logback.xml already, then just add an entry to disable the debug for this package.

Nice! thank you!
