### ISSUE TITLE
IF-THEN-ELSE Conditional with properties attribute (Draft 7)

### ISSUE THREAD

**Issue by serebro** [networknt/json-schema-validator#357]
For a case that is described here 
https://json-schema.org/understanding-json-schema/reference/conditionals.html 
I did not found test case and as I understand this was not implemented because the validator ignores `properties` attribute.
Could it be implemented? Or give me please an example how to use it.
Thank you.

**Comment by stevehu** [comment]
The use cases you mentioned are not in the official test suite. Could you please create a PR with test cases to produce the issue? It will help others to pick it up and get it implemented if it is not working. Thanks.

https://github.com/networknt/json-schema-validator/blob/master/src/test/resources/draft7/if-then-else.json

**Comment by gareth-robinson** [comment]
Is there an issue here? The test case that was added passes.

**Comment by stevehu** [comment]
@gareth-robinson I don't think we have any issue here. The fix is merged but we forgot to close the issue I guess.
