### ISSUE TITLE
Is your library the right choice for me?

### ISSUE THREAD

**Issue by FWiesner** [networknt/json-schema-validator#359]
Hi guys,

your library looks extremely promising to me, but I wonder whether it is the right choice for my project. I would really appreciate if you could give me a hint.

I'm seeking a solution that allows me verifying whether JSON Schemas (Draft 7) are valid and all `$ref` entries can be resolved and recursively are valid JSON Schemas as well. The JSON Schemas for me act as meta model definitions and are used for code generation, but they don't get used to validate JSON documents at runtime. Think of my service as being a schema repository.

The key requirements for me are:
1. Support for schemas that have no properties, but only `definitions`. Used for `$ref` usage elsewhere
2. Support for `$ref` resolution to other schemas  `other-schema.json#/definitions/OtherType`
3. Ability to register a custom URI resolver with dynamic inventory of schemas. Essentially I need to be able to delegate all schema resolutions for `$ref` to my resolver and I cannot have a catalog enumerating all schemas upfront. The inventory could change at any time.

Ideally the library would also be able to identify when there are ambiguity issues, say with `oneOf` and candidate definitions that overlap.

Is your `json-schema-validator` usable like that?

Thanks in advance a lot!

**Comment by FWiesner** [comment]
I guess I've found the answers myself. Here is what I did - and I hope I didn't forget anything.

1. validating a schema with only definitions does not seem to cause validation to happen on the definitions, as there is no validation root. But, creating an extra root schema that just has the boilerplate and the `$ref` to my root resource in the `definitions` section of my other schema file does seem to do the trick.
2. seems to work, see 1
3. I've created a custom `java.net.URLStreamHandler` for a custom URL scheme and adding a corresponding custom `com.networknt.schema.uri.URIFactory` and a `com.networknt.schema.uri.URIFetcher` appears to make it work

**Comment by stevehu** [comment]
@FWiesner I am glad you have found the answer yourself. Let us know if you have further questions or requirements. This is a community-driven project and we can gradually implement all features if they make sense and useful for the community. Thanks.

**Comment by FWiesner** [comment]
Hi @stevehu,

one more question I have. When I have one schema that references another schema, how can I enable that the other schema is also validated and not just parsed? In particular I have one schema referencing a definition in another schema. When there is no match under under `definitions` in the referenced schema, the validation passes, although it should fail.

Florian

**Comment by stevehu** [comment]
All $ref will be resolved recursively and validated at the same time. We also support local file system references and there are document links on the README.

**Comment by FWiesner** [comment]
the custom protocol approach allows me using the library with a database and it works like a charm - thank you!
Btw what I realized is that the schema under validation is not automatically part of the cyclic dependency check. I'm simply providing it as part of the protocol handler as well now. My scenario is A (under verification and not yet stored) -> B (stored and not yet valid) -> A. In this case A and B get both loaded once from the backend although A should be in memory already. Minor thing - I already have a solution for this, but I just thought I'd let you know

**Comment by stevehu** [comment]
I haven't seen the issue you mentioned. I am wondering if you could submit a PR with the issue reproduced. It will help developers to get it fixed. Thanks.

**Comment by FWiesner** [comment]
hope I can do so, once I'm back from Christmas vacation
