### ISSUE TITLE
Validation that schemas can be loaded

### ISSUE THREAD

**Issue by FWiesner** [networknt/json-schema-validator#365]
Hi all,

I have the the need to validate the JSON Schemas being correct and loadable (especially `$ref` resolution). So, I've added two step validation to my app.

**Step 1: validate schema syntax**
here I use the json schema draft 7 meta schema JSON as downloaded from json-schema.org. This ensures that my schema documents are syntactically correct.

**Step 2: validation of the schema being loadable correctly**
Here I load the JSON schema that is sent to my service via `JSONSchemaFactory#getSchema`. Then I use `validate` with the loaded schema and a dummy document to validate.

**_Step 3 is to persist the schema being validated in the previous two steps._**

Now, here's the problem I have. I need all `$ref` values to be resolved by `json-schema-validator` and that is the sole purpose of my validation step 2.
As long as none of my schemas uploaded have a `required` declaration, the validation passes, even when I just pass in `{}` as document to validate. But, as soon as I have a `required` declaration, things get nasty. I don't plan generating dummy documents on the fly, but if I don't, I only have two options to check my `$ref` resolution.

**option 1**: filter the the `ValidationMessage` set. My gut feeling is that this approach could be highly error-prone and could impose risks on library upgrades
**option 2**: trigger the `$ref` resolution in a different way. To me it would be awesome if there was a flag to `JsonSchemaFactory#getSchema` to eagerly fetch and load the main and referenced schemas.

So, my question is whether I have a chance to get around option 1...

Happy new year in advance!

**Comment by stevehu** [comment]
I wouldn't recommend option 1 as it is not the ValidationMessage was designed for. I am wondering if you want to pre-process the $ref for your schema before calling this library. Take a look at this project and see if you can use the idea. 

https://github.com/networknt/openapi-bundler

**Comment by FWiesner** [comment]
not sure I understand your proposal. What I try doing is building a JSON Schema document store with the ability to then refer to individual schemas and their `#/definitions` as a repository. So, I cannot have a code generation step as all the schema processing happens at runtime. I will later have the ability to check individual payloads against the inventory of schemas which could comprise of hundreds to thousands of schema documents, but for now I focus on storing JSON schemas after validating their content and their references to other schemas on the same service. I don't plan supporting external schemas for now and enforce this by only allowing relative URLs and absolute URLs specifying my in-memory protocol schema.

Btw your library is fantastic in what it can do for me. I see complex graphs of schema inter-dependencies get properly resolved. So, if I have several schemas all referencing their definitions from each-other, the validation of the schemas works perfectly - I of course get exceptions in the case, when a schema element reference cannot be resolved, but functionally that is fine.

**Comment by stevehu** [comment]
@FWiesner Have you tested the latest version 1.4.x? Please reopen it if the issue still exists.
