### ISSUE TITLE
Is there a way I can get a dereferenced/resolved schema using this library

### ISSUE THREAD

**Issue by mohitpali** [networknt/json-schema-validator#371]
Do we have a way we can get a dereferenced schema out of a schema - something like this library (https://github.com/APIDevTools/json-schema-ref-parser)

I looked at walkers but did not fully understand if we have a way to do this

Input :

```
{   "$id": "https://example.com/arrays.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "A representation of a vegetables, company",
    "type": "object",
    "properties": {
        "vegetables": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/veggie"
            }
        }
    },
    "definitions": {
        "veggie": {
            "type": "object",
            "properties": {
                "veggieName": {
                    "type": "string"
                }
            }
        }
    }
}
```

Output :
```
{
    "$id": "https://example.com/arrays.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "A representation of a vegetables, company",
    "type": "object",
    "properties": {
        "vegetables": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "veggieName": {
                        "type": "string"
                    }
                }
            }
        }
    }
}
```

**Comment by stevehu** [comment]
Is there any reason you want to do that?

**Comment by mohitpali** [comment]
Yeah, we have a requirements to resolve/dereference schemas in order to check if two schemas are the same/similar or not.

**Comment by stevehu** [comment]
The internal structure will have all references resolved in the refValidator as I remember. However, there is no method that you can compare it with another schema. If you want you can debug into it and see if you could create two schemas and add a new method to compare between them.

**Comment by prashanthjos** [comment]
@mohitpali we do this and we use walkers to do this. You just need to add a “keyword” Walker on $ref and replace the $ref with the actual definition  inside the walk method. Please look at the walker documentation.

**Comment by mohitpali** [comment]
> @mohitpali we do this and we use walkers to do this. You just need to add a “keyword” Walker on $ref and replace the $ref with the actual definition inside the walk method. Please look at the walker documentation.

Alright, thanks, I am looking into the walker documentation. Would you have some sample example code that you could share ?

**Comment by prashanthjos** [comment]
Hi @mohitpali please refer to the following testcase.

https://github.com/networknt/json-schema-validator/blob/master/src/test/java/com/networknt/schema/JsonWalkTest.java
