### ISSUE TITLE
Question: is the JsonSchema class thread safe?

### ISSUE THREAD

**Issue by yokeho** [networknt/json-schema-validator#39]
We are using the library in a web service to validate incoming requests against a schema. The application is by nature multi-threaded so there may be multiple validations going at the same time. 

Is the JsonSchema class and the validate() method thread safe? Can I create and cache/share one instance of the JsonSchema and have all requests use it, or should I instantiate a new JsonSchema for each request?

**Comment by stevehu** [comment]
I am using it the same way like yours in my frameworks [light-4j](https://github.com/networknt/light-4j) and [light-rest-4j](https://github.com/networknt/light-rest-4j) and the library is thread safe. The same schema will only be parsed once and cached and there should be only one instance of JsonSchema available as it is created from the factory. If you are interested, take a look at how I use it in my [swagger-validator](https://github.com/networknt/light-rest-4j/tree/master/swagger-validator). Let me know if you have further questions. Thanks and happy coding...

**Comment by yokeho** [comment]
Awesome, thank you. And thanks for the great work on this library.
