### ISSUE TITLE
MinLength and MaxLength validator failed in official test suites due to Java string Unicode handling "\uD83D\uDCA9\uD83D\uDCA9"

### ISSUE THREAD

**Issue by stevehu** [networknt/json-schema-validator#4]
The following test failed as Java string length function returns 4 instead of 2 for those special characters. Similar test in MinLength failed too. 

[
    {
        "description": "maxLength validation",
        "schema": {"maxLength": 2},
        "tests": [
            {
                "description": "two supplementary Unicode code points is long enough",
                "data": "\uD83D\uDCA9\uD83D\uDCA9",
                "valid": true
            }
        ]
    }
]

**Comment by dola** [comment]
Have a look at `String.`

**Comment by stevehu** [comment]
@dola Thank you so much for pointing me to the right direction. I have updated the code and added back the test cases. Works perfectly. Will have another release shortly.
