### ISSUE TITLE
Add Custom message

### ISSUE THREAD

**Issue by swarooppallapothu** [networknt/json-schema-validator#40]
How to add custom message for validators. below is my sample schema.

{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {},
    "properties": {
        "active": {
            "type": "boolean"
        },
		"name": {
            "type": "string",
			"requiredErrorCode": "name is required"
		}
	},
	"required": ["name"]
}

**Comment by stevehu** [comment]
The current implementation doesn't support customized error message. Is requiredErrorCode defined in the spec? Could you please provide a link?

**Comment by lakshmi088** [comment]
There is no spec for requiredErrorCode. i created this attribute based on enumErrorCode.

**Comment by lakshmi088** [comment]
There is no spec for requiredErrorCode. i created this attribute based on enumErrorCode.

**Comment by swarooppallapothu** [comment]
There is no spec for requiredErrorCode. i created this attribute based on enumErrorCode.
