### ISSUE TITLE
Support for IRI and IRI Reference

### ISSUE THREAD

**Issue by stevespringett** [networknt/json-schema-validator#402]
I need to be able to validate iri and iri-reference. It doesn't look like the library supports it currently.

This ticket is to request support for iri and iri-reference.

In the meantime, is there a workaround to add support for it myself?

**Comment by stevehu** [comment]
@stevespringett As I understand, there are two steps to support the iri and iri-reference. The first step is two support the format and the second is to support the reference and loading etc.

The second part is not finalized yet per this opened [issue](https://github.com/json-schema-org/json-schema-spec/issues/59)

To support the format, it is much easier and the only class that you might need to update is the format template. 

https://github.com/networknt/json-schema-validator/tree/master/src/main/java/com/networknt/schema/format

**Comment by stevespringett** [comment]
Hi @stevehu. Yes, I'm primarily interested in supporting format in order to properly validate. I didn't see an easy way to provide my own format (or add to existing formats) without forking the project and making the changes locally. I need to avoid modified forks. Any guidance on how this can be achieved without modifying the library?

**Comment by stevehu** [comment]
To support the format, we can just add the template for the iri and iri-reference to the library with a PR. This validation should be standard for all users and there is no need to fork and customize.

**Comment by fdutton** [comment]
Resolved in #766 and #768
