### ISSUE TITLE
Behavior change of $ref resolution

### ISSUE THREAD

**Issue by jorcasso** [networknt/json-schema-validator#406]
In our system we support some well known URNs that our clients can use in their schema definitions, using the `$ref` keyword, for example:

```
{
    "properties": {
        "someField": {
            "$ref": "urn:my-company:my-custom-type"
        }
    }
}
```

We use a custom `URNFactory` and works great.

But we have observed the way of the URN resolution has changed as of release `1.0.49`. Previously, if a schema contained an unknown URN the call to `JsonSchemaFactory.getSchema(...)` failed with a `JsonSchemaException`. Now it does not fail in that moment but later, when calling to `JsonSchema.validate(...)`. I suspect this change could be due to https://github.com/networknt/json-schema-validator/pull/377.

Is is possible to recover the old behavior and resolve the `$ref` keywords when getting the schema? that way we would ensure the schema instantiated is valid, or at least would it be possible to provide a way to load the `$ref` schemas eagerly after getting the schema instance?

**Comment by stevehu** [comment]
@jorcasso This is a dilemma we are facing. The #377 fixed a defect for parallel processing with lazy loading. The only option I can think of is to create a configuration flag. By default, it should be lazy loading; however, with the parallel processing flag is false, we can eagerly load the schemas. I didn't read the code but I am guessing we can also fix the loading with the synchronous keyword. I will leave it to you to choose one of the above options. Thanks.

**Comment by flozano** [comment]
IMHO having a flag for keeping previous behaviour would be enough. Eventually if someone can figure out a better fix for initialize() that allows parallelization, that would be better, but a flag seems immediately easier?

**Comment by stevehu** [comment]
@flozano I agree with you. Option 1 would be much simpler to implement.

**Comment by FWiesner** [comment]
Is somebody actively working on this? It is affecting us as well and I could take a look into the implementation if nobody already has done work

**Comment by flozano** [comment]
We planned to, but haven't started working on this yet because of bandwidth constrains, sorry... reverted to older version for now instead
