### ISSUE TITLE
Need support for case insensetive lookup

### ISSUE THREAD

**Issue by bpanigrahi** [networknt/json-schema-validator#407]
I have a project need to lookup for specific skills without considering case insensetive.  There are around 10 values

For ex: itSkill, itskill, ITSKILL as value for my use case.

I am unable to use `enum` or `oneOf`. Can you please suggest what is the best way to achieve my requirement.

**Comment by stevehu** [comment]
@bpanigrahi I don't know which validator you are talking about. Could you please provide a schema and a JSON data string to explain what is your requirement? Thanks.
