### ISSUE TITLE
With #409 http://json-schema.org/draft-07/schema# is not accepted as valid schema anymore

### ISSUE THREAD

**Issue by FWiesner** [networknt/json-schema-validator#411]
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "...": "..."
}
```
now leads to

```
$.$schema: does not match the uri pattern ^([A-Za-z][A-Za-z0-9+.-]+):(\/\/([^@]+@)?([A-Za-z0-9.\\-_~]+)(:\\d+)?)?((?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&'()*+,;=:@])+(?:\/(?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&'()*+,;=:@])*)*|(?:\/(?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&'()*+,;=:@])+)*)?(\\?(?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&'()*+,;=:@]|[/?])+)?(\\#(?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&'()*+,;=:@]|[/?])+)?$
```

**Comment by FWiesner** [comment]
@vmaurin could you please have a look?

**Comment by vmaurin** [comment]
Sure. When did you get the issue ? I run my own test with json schema 7 and I didn't got the problem. Could you provide a java code snippet leading to this error ?

**Comment by FWiesner** [comment]
load the JSON Schema Draft 7 meta schema from json-schema.org and then validate itself against it

**Comment by vmaurin** [comment]
Ok according to the RFC, empty fragment is allowed https://datatracker.ietf.org/doc/html/rfc3986/#appendix-A , the regexp I used is bugged in this regard. I will open a PR for the fix

**Comment by FWiesner** [comment]
thanks!

**Comment by vmaurin** [comment]
Empty query string also might be allowed, I will try too

**Comment by vmaurin** [comment]
@FWiesner The PR I have opened should fix the issue (and also probable one with empty query string). Could you test with it ?

**Comment by stevehu** [comment]
@vmaurin @FWiesner Thanks a lot for your effort. I have merged the PR. Once you guys confirm it is working I will release another version.

**Comment by FWiesner** [comment]
@stevehu @vmaurin we currently test it

**Comment by FWiesner** [comment]
@stevehu please release - it is working now

**Comment by vmaurin** [comment]
@FWiesner it has been released here https://github.com/networknt/json-schema-validator/releases/tag/1.0.55
