### ISSUE TITLE
Stackoverflow on format `uri` validation

### ISSUE THREAD

**Issue by vmaurin** [networknt/json-schema-validator#413]
I ran into an other problem with the regex I commit for URI validation. It is using a lot of `|` that are quite intensive regarding the text evaluation. As java Pattern class seems implemented with recursion, it can quickly fill the stack and one might run into Stackoverflow errors while evaluating an URI relatively large (thousand of chars)

@stevehu @FWiesner You are probably interested on this issue too. I will try to quickly rework again the regular expression, to have something that might be more tolerant, but with lower impact on the call stack (avoiding all `|`)

**Comment by stevehu** [comment]
@vmaurin Thanks for the findings. This is the way we make the library more useful for all users. Iterative refinement is the key to make this library grow.

**Comment by vmaurin** [comment]
@stevehu I have opened the PR, I have left as comment the process of though to rework the regexp, not sure if it is useful, let me know on the PR

**Comment by ruseinov** [comment]
https://github.com/jonckvanderkogel/java-tail-recursion may be of use

**Comment by stevehu** [comment]
@ruseinov Thanks for the link. Interesting example.

**Comment by vmaurin** [comment]
Fixed in https://github.com/networknt/json-schema-validator/releases/tag/1.0.56
