### ISSUE TITLE
When typeLoose set to true, validation convert integers/string to array

### ISSUE THREAD

**Issue by MarinaRappoport** [networknt/json-schema-validator#415]
According to documentation typeLoose is used to allow sending string as integers/numbers ("When typeLoose is true, the validator will convert strings to different types to match the type defined in the schema"), but in fact it effects other types validation - not only number/integers.
In my example the schema has array of integers and array of objects:
```
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "properties": {
    "array_of_integers": {
      "$id": "#/properties/array_of_integers",
      "type": "array",
      "items": {
        "type": "integer"
      }
    },
    "array_of_objects": {
      "$id": "#/properties/array_of_objects",
      "type": "array",
      "items": {
        "type": "object"
      }
    }
  }
}
```

The following json pass validation (when typeLoose = true):
```
{
  "array_of_integers": 1,
  "array_of_objects": {}
}
```

I expect it to fail (like when typeLoose = false):
```
$.array_of_integers: integer found, array expected
$.array_of_objects: object found, array expected
```

**Comment by stevehu** [comment]
@MarinaRappoport Thanks for raising a separate issue. Will take a look at this once we have free cycles.
