### ISSUE TITLE
maxLength and minLength do not work when a number with a zero decimal is used.

### ISSUE THREAD

**Issue by mohsin-sq** [networknt/json-schema-validator#446]
According to the json spec 

1.0 and 1 are both considered integers, however the method used in max/minLength validations `isIntegralNumber` does not return true for 1.0. This has caused us some headaches as we are using proto3 to go from json -> proto3 and are running into the issue where when we set  maxLength value to be 2, it get converted to 2.0 and does not get evaluated by the validators: https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/MaxLengthValidator.java#L36

There was a recent issue where in jackson-databind which addressed this `isIntegralNumber` method and an `canConvertToExactIntegral` method was created for this exact purpose which should return true for both 2.0 and 2. 

We propose updating the validators (something i can also do and send a pull request) where isIntegralNumber is used in the length validators (7 locations: https://github.com/networknt/json-schema-validator/search?q=isIntegralNumber)

References:
https://json-schema.org/understanding-json-schema/reference/numeric.html
https://github.com/FasterXML/jackson-databind/issues/2885

**Comment by stevehu** [comment]
@mohsin-sq  I agree with you to consider 2.0 as 2 in the maxLength and minLength validators. Would you be able to summit a PR to get it implemented? Thanks.

**Comment by mohsin-sq** [comment]
I have created a PR: https://github.com/networknt/json-schema-validator/pull/450

**Comment by mohsin-sq** [comment]
Thanks for merging that @stevehu! 

When do you think it'll make it into maven central?
