### ISSUE TITLE
Is there a way to dynamically update enum value defined in schema?

### ISSUE THREAD

**Issue by ivyxiao123** [networknt/json-schema-validator#453]
Hi, 
I'm looking for a solution that can dynamically update the allowed enum value list, is it possible to do that? Or is there a way to generate the entire schema dynamically then use it for validation?

Right now I'm defining the schema in a file then load the file into memory for validation.

Thanks

**Comment by stevehu** [comment]
@ivyxiao123 I think you can do that. Dynamically create the schema and pass it to the library to do the validation.

**Comment by ivyxiao123** [comment]
Hi @stevehu, so do I just create the schema in inputsteam and pass it into schema factory to generate?

**Comment by stevehu** [comment]
The schema can be a static string or file or stream and it just needs to be supplied to the library. You can generate anything as a string or stream before you call the schema validator.
