### ISSUE TITLE
Get Schema with $ref resolved

### ISSUE THREAD

**Issue by palwe-prafulla** [networknt/json-schema-validator#455]
I am using json schema to define my REST API input payloads and have structured the schemas into multiple common schemas and using $ref accordingly.
These schemas will be used by users to send payloads accordingly.
I have implemented get schema apis so users can retrieve schemas and integrate to send payloads accordingly.
However when I retrieve JsonSchema from validator the schema is returned as is with $ref as is.
All the schemas are internal so there is no external references i.e. all $refs are using "resource: .."

Is there any way to retrieve schemas with $ref resolved automatically so that users dont have to retrieve multiple schemas to figure out definitions referred everywhere? I am also trying to avoid writing custom code to parse the $ref and replce with actual definitions from common schemas.

I couldnt find anything to do this in the validator once schemas are loaded.
Any pointers?

**Comment by stevehu** [comment]
$ref can be resolved automatically always and this is how we use the library to validate requests based on the OpenAPI specification in the light-4j frameworks.

**Comment by palwe-prafulla** [comment]
@stevehu Thanks for your reply.
May be I did not explain the use case clearly.
Here is more detailed explanation of the use case.

So I am using JsonSchemaFactory.getSchema() method to get the JsonSchema from inputStream as below:

```
        JsonSchemaFactory factory = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V7);
        InputStream inputStream = Thread.currentThread().getContextClassLoader().getResourceAsStream(schemaFile);
        return factory.getSchema(inputStream);
```

Then I am using getSchemaNode() method to get the JsonNode for the JsonSchema and using internal util to convert JsonNode to JsonObject and returning this as REST API output for getSchema API.

   ```
JsonObject getAndBuildReqRespJsonSchemaObject(String reqSchemaTypeStr, String respSchemaTypeStr) {
        JsonObjectBuilder objBuilder = Json.createObjectBuilder();
        try {
            JsonObject reqObj = null;
            JsonObject respObj = null;
            if (schemaTypeJsonSchemaMap.get(reqSchemaTypeStr) != null)  {
                reqObj = JsonUtil.convertJsonNodetoJsonObject(schemaTypeJsonSchemaMap.get(reqSchemaTypeStr).getSchemaNode());
                objBuilder.add(SchemaPayloadType.REQUEST.toString(), reqObj);
            }
            if (schemaTypeJsonSchemaMap.get(respSchemaTypeStr) != null)  {
                respObj = JsonUtil.convertJsonNodetoJsonObject(schemaTypeJsonSchemaMap.get(respSchemaTypeStr).getSchemaNode());
                objBuilder.add(SchemaPayloadType.RESPONSE.toString(), respObj);
            }
        } catch (Exception ex) {
            LOGGER.error("Exception caught:", ex);
        }
        return objBuilder.build();
    }
```

Basically I am getting and converting the original schema read from file from  JsonSchema-->JsonNode-->JsonObject 
and what I am getting is the result same as original jon schema file I have.
This is good and expected.

However, what I am trying to figure out is that is there any way I can get the original schema with $ref resolved with actual definitions referred from different schema file i.e. replace $ref with actual def from other schema file.

Example:
Original Schema:

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://abc.com/schema/request_schema.json",
  "type": "object",
  "properties": {
    "name": {
      **_"$ref": "resource:com/schema/common/common_defs_schema.json#/defs/NameDef"_**
    },
    "description": {
      "type": "string"
    },
  },
  "required": [
    "name",
    "description"
  ],
  "additionalProperties": false
}
```

common schema with def references in above schema:

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://abc.com/schema/common/common_defs_schema.json",
  "type": "object",
  "defs": {
    **_"NameDef": {
      "type": "string",
      "pattern": "(?=^.{1,128}$)[^&<>! \"]+$"
    },_**
    "emptyStringDef": {
      "type": "string",
      "enum": [
        ""
      ]
    },
    "nonEmptyStringDef": {
      "type": "string",
      "minLength": 1
    }
  }
}
```

What I am trying to get is the original schema with $ref resolved/replaced with actual def referred as below:

{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://abc.com/schema/request_schema.json",
  "type": "object",
  "properties": {
    "name": {
       **_"type": "string",
      "pattern": "(?=^.{1,128}$)[^&<>! \"]+$"_**
    },
    "description": {
      "type": "string"
    },
  },
  "required": [
    "name",
    "description"
  ],
  "additionalProperties": false
}

**Comment by bartoszm** [comment]
What you are trying to achieve, I guess, is called `dereference` by this library https://apitools.dev/json-schema-ref-parser/docs/ref-parser.html#dereferencepath-options-callback. You could use walker to achieve what you want. Below very rudimental example of the approach, but:
* you probably should not change the schema on the fly, but rather use collectors
* there might be some corner cases example is not handling 
*
```
@Test
    public void testWalker() throws Exception {
        var testCaseFile = "draft2019-09/xx.json";
        final URI testCaseFileUri = URI.create("classpath:" + testCaseFile);
        var svc = new SchemaValidatorsConfig();
        svc.addKeywordWalkListener("$ref", new JsonSchemaWalkListener() {
            @Override
            public WalkFlow onWalkStart(WalkEvent walkEvent) {
                return WalkFlow.CONTINUE;
            }

            @Override
            public void onWalkEnd(WalkEvent we, Set<ValidationMessage> validationMessages) {
                var ref = we.getSchemaNode().get("$ref").asText();
                var parent = we.getParentSchema().getCurrentUri();
                var target = we.getCurrentJsonSchemaFactory().getUriFactory().create(parent, ref);
                var schema = we.getRefSchema(target);
                var sn = (ObjectNode) we.getParentSchema().getSchemaNode();
                var field = fieldName(we.getSchemaPath());
                sn.set(field, schema.getSchemaNode());
            }

            private String fieldName(String schemaPath) {
                int idx = schemaPath.lastIndexOf("/");
                if(idx >= 0 && idx < schemaPath.length() - 1) {
                    return schemaPath.substring(idx + 1);
                }
                return null;
            }
        });

        var schema = validatorFactory.getSchema(testCaseFileUri, svc);
        schema.walk(null, false);
        System.out.println(schema.getSchemaNode().toPrettyString());

    }
```

**Comment by palwe-prafulla** [comment]
Thanks @bartoszm For reply.
Yes, this is exactly what I needed - dereference all the $ref and get plain JsonSchema with $ref resolved.
I thought the networknt schema validator may have this implemented to get JsonSchemas with $ref resolved so wanted to check here.
But I can certainly try the walker recursively to get all the defs into Json Schema but thought this would be helpful feature to have since its very common to have multiple references to internal/external file and it would make life easier for Users (API/GUI) to get the plain json schema with everything resolved and not figure out every reference.

**Comment by palwe-prafulla** [comment]
@bartoszm Thanks for more info on this. 
I am using JsonSchema.getSchemaNode() once the schema is read and it returns the schema in original format with $ref as is.
This lead me to think that the JsonSchema is stored as is (without resolving $ref when its read) and I was wondering when validate api is called with payload, how is it validating the json objects which are originally defined as $ref to some def in another schema.
I was guessing that, its probably dynamically going to validate against the schema used in $ref.
I understand based on your comments that this is probably not a significant performance issue as such as you mentioned where all the schemas are cached/loaded so its just a matter of retrieving the $ref schema from cache/memory and validating against that Vs if it was a plain json schema with object defs already resolved in place.

I totally understand that we should not change original schema as such and can store it as is once read.
However, it would be nice to have api to retrieve the schema with $ref resolved/dereferenced for use cases where users would like to  just get the schema with plain object defs without any $refs.

I understand this is probably not a priority use case as such and devs can easily write their own tool/api to resolve $refs or merge the external $defs into original schema as needed.

**Comment by stevehu** [comment]
The $ref always working and the standard test suite covers it. Has anybody found it is not working or am I missing something?

**Comment by Aravinda93** [comment]
@stevehu 

I have a doubt related to `$ref` with reference to local JSON Schema file instead of the remote URL file. I have a JSON Schema file `json-schema1.json` which has a reference to a remote URL something like this:

`"$ref": "https://example.org/sample/json-schema.json",`

This works fine and I able to validate the JSON document against the schema. But If I copy the contents from the URL and place it into the same folder as `json-schema1.json` and then reference it:

`"$ref": "./json-schema.json",`

Then I get the error:
```
Exception occurred during validation against JSON schema : Cannot invoke "com.networknt.schema.JsonSchemaRef.getSchema()" because "this.schema" is null
	at io.validation.json.JsonSchemaValidator.lambda$validateAgainstCaptureSchema$0(JsonSchemaValidator.java:73)
```

NetworkNT JSON Schema Validator not being able to load a schema file with a local JSON schema reference in $ref could be related to how the $ref keyword is handled by the validator. 

I have not made any changes to the files or validation, just changed the $ref to local file instead of the remote URL. How to ensure Network-Nt validates the JSON against the JSON Schema when using the $ref with local file instead of the remote file?
