### ISSUE TITLE
Compatibility with older Jackson versions ?

### ISSUE THREAD

**Issue by sergehuber** [networknt/json-schema-validator#457]
Hi, 

I'd love to use the latest and greatest version of this library (which is great btw) but I can't use it with Jackson 2.12.2 because of other dependencies that are pulling older versions of Jackson (Apache CXF). Would it be possible to make the lib compatible with Jackson 2.10.5.1 ?

Best regards,
  Serge...

**Comment by stevehu** [comment]
@sergehuber Jackson is kind of a pain for us as there are so many security vulnerabilities for older versions. The library has a transitive dependency on 2.12.2 but you can always overwrite it with your 2.10.5.1 in your project pom.xml file.
