### ISSUE TITLE
Support for default and new function applyDefaultsAndValidate

### ISSUE THREAD

**Issue by SiemelNaran** [networknt/json-schema-validator#458]
Looks like json-schema-validator does not support the "default" keyword.  Is it possible to have a new function applyDefaultsAndValidate that applies the default and validates the schema?

As for tests we may need
1. Test where "foo" of type "int" is required and default is 5, and object to validate has no value for "foo", but validation passes.  Also, the object to validate is changed in place, and the test asserts "foo" exists and is equal to 5.
2. Test where "foo" of type "int" is required and default is "five", and object to validate has no value for "foo", and validation fails with error message that foo has the wrong type (the usual error message), or even better default value for foo has the wrong type.  In theory this should handle all validations, like minValue, maxValue, so no more tests are needed.

There is one thing though.  Suppose we are applying defaults and validating a big json and somewhere in the middle it fails fast.  Then the json is partially changed.  Maybe then we can just Javadoc this behavior and provide support for a listener.

I'm willing to work on this.

Thoughts?

**Comment by stevehu** [comment]
There are two main functions for this library: Validating and Walking. From a validation perspective, it is following the specification and the test cases were in default.json for each spec version. For walker listeners, I don't know how the default keyword is handled. I am guessing you are talking about the walker enhancement to apply the default values for your JSON input based on the specification. If this is the case, I would recommend exploring the walker code and add the future there. Let me know if I am off track.

**Comment by SiemelNaran** [comment]
Yeah, that's correct.  The use case is something like this.  Someone changes the schema to add a new attribute with default value.  Then if you validate an existing json object that does not have this new attribute, it ought to pass.  Furthermore, it would be nice to get an updated json object that has the default values filled in.

The other use case is that you already have json objects that passed the schema and saved to the database, and now you add a new attribute with default to the schema.  Unless you re-validate the json object with the new schema, it will not get the defaults.  So my approach of filling in default values will not help in that use case.

There's talk about this at https://python-jsonschema.readthedocs.io/en/stable/faq/ "Why doesn’t my schema’s default property set the default on my instance?".  Though I want to default validator to be the first one, so that the default value itself gets validated.

So my plan is something like this:
- Create a new validator class called something like ApplyDefault.  Even though it extends JsonValidator, it is not a validator.
- Only when someone calls applyDefaultsAndValidate then install this validator into the JsonMetaSchema.   Others "default" will continue to be a NonValidationKeyword.
- Arrange things so that JsonSchema.getValidators returns ApplyDefault first.  That function currently returns a HashMap, so we probably want a SortedMap.

It may be nice to do this in a way of hooks, so that customers can add this behavior.

**Comment by SiemelNaran** [comment]
It seems easier to do without creating a listener on the "default".  Instead I added a variable shouldApplyDefaults (but then turned it into a class so that you can apply property defaults or array defaults).  See https://github.com/networknt/json-schema-validator/pull/468/files.

**Comment by fdutton** [comment]
This was resolved in pull-request #477
