### ISSUE TITLE
Should ValidationMessage.getArguments() be public?

### ISSUE THREAD

**Issue by ehrmann** [networknt/json-schema-validator#46]
I think this was just an oversight, and I'm happy to open a PR for it, but before I open the PR, I figured I'd ask.

In `ValidationMessage`, `getArguments()` has default access, but `setArguments()` has public access. Was this an intentional design choice, or were they just flipped by mistake?

[Relevant code](https://github.com/networknt/json-schema-validator/blob/046d082/src/main/java/com/networknt/schema/ValidationMessage.java#L48-L54)

**Comment by stevehu** [comment]
I don't remember if it is designed this why for some reason. But for consistency we need to make it work the same way like other field. I have merged you pull request and will have a release shortly. Thanks a lot.
