### ISSUE TITLE
Since 1.0.58 some date-time are not valid anymore

### ISSUE THREAD

**Issue by guillomep** [networknt/json-schema-validator#466]
Hello,

I have a JSON  schema that defined the following properties

```json
{
  "time": {
    "type": "string",
    "format": "date-time"
}
```

And the following JSON to validate
```json
{
  "time": "2021-03-11T09:00:00Z"
}
```

With the validator in version 1.0.57, the JSON is valid but in 1.0.58 and above the date time is invalid:
`$.time: 2021-03-11T09:00:00Z is an invalid date`

But, it is a valid date for the RFC so it should be valid.

**Comment by stevehu** [comment]
@guillomep Thanks a lot for the clarification.
