### ISSUE TITLE
Property Keyword Walk Listeners Invoked Too Often Since 1.0.59

### ISSUE THREAD

**Issue by tomdeering-wf** [networknt/json-schema-validator#467]
Consider the following schema:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "default_schema",
  "description": "Default Description",
  "properties": {
    "tags": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    }
  }
}
```
A walk listener configured with `config.addKeywordWalkListener(ValidatorTypeCode.PROPERTIES.getValue(), jsonSchemaWalkListener);` is only expected to be invoked when `"tags"` is walked since that is the only property defined in the schema, but in 1.0.61 it is invoked for:
`tags`
`$.properties.tags.items`
`$.properties.tags.items[0]`
The latter two invocations are unexpected, since those are not properties.

**Comment by stevehu** [comment]
@prashanthjos Would you be able to comment on it?

**Comment by tomdeering-wf** [comment]
Likewise, adding a listener with `config.addPropertyWalkListener` collects even more unexpected things:
```
org.opentest4j.AssertionFailedError: 
Expected :[$.properties.tags]
Actual   :[$.properties.tags.type, $.properties.tags.items, $.properties.tags.items[0].type, $.type, $.$schema, $.description, $.title, $.properties]
```
