### ISSUE TITLE
JsonNode.canConvertToExactIntegral not work

### ISSUE THREAD

**Issue by wyjie0** [networknt/json-schema-validator#469]
method "canConvertToExactIntegral()" can not be found in class "JsonNode", but it is called in class "MinItemsValidator"

**Comment by caseycrites** [comment]
(I'm a co-worker of @achen118)

This is due to having an older version of `jackson-databind` installed in our project. We currently have `2.10.4,` but need at least `2.12.1`. After upgrading that dependency, the error goes away.
