### ISSUE TITLE
Behavior of the NotValidator is incorrect when using the walk method.

### ISSUE THREAD

**Issue by Kordalien** [networknt/json-schema-validator#484]
Given:
{"not":{"type":"string"}}
and
"test"

I expect
schema.walk(data, true)
Should return a validation error. It does not.

Similarly, given the sample:
123
or
{"foo":1}
I expect it to not return a validation error.
However, the validationResult comes back with a validation set containing `$: integer found, string expected`.

This is caused by the implementation of Walk in NotValidator which fails to invert the results of the subschema.

**Comment by Kordalien** [comment]
I'd be  happy to pick up the work of fixing this case, but have some concerns over expected behavior given the changes made in the last patch to the NotValidator

(call delegating to NotValidator.validate() was reomoved, which makes sense for accelerating behavior, but logic wasn't duplicated correctly)


This calls for a larger discussion, which would be does it make sense to make validate strictly be a delegate of walk to avoid incorrect duplications from popping up.

**Comment by stevehu** [comment]
@Kordalien I am not very familiar with the walk feature. @prashanthjos Do you have any comments on this issue? Thanks.
