### ISSUE TITLE
URI validation does not allow relative reference

### ISSUE THREAD

**Issue by nnrudakov** [networknt/json-schema-validator#486]
Validating property of type string with format uri only allows absolute uri.

Why #23 is closed? Bug is still present. [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986#section-4.2) allows such links. But code and [tests](https://github.com/networknt/json-schema-validator/blob/master/src/test/resources/draft2019-09/optional/format/uri.json#L79) restrict that.

**Comment by stevehu** [comment]
I haven't looked into it but it is from the official test suite. 

https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/master/tests/draft2019-09/optional/format/uri.json#L77

**Comment by nnrudakov** [comment]
For relative URI can use `uri-reference`.
