### ISSUE TITLE
V2019-09 $ref cannot be resolved in array 'additionalItems'

### ISSUE THREAD

**Issue by carolkao** [networknt/json-schema-validator#493]
Hi, I encounter a reference problem in array 'additionalItems'. Here is my schema:

```
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "parameters": {
      "type": "array",
      "uniqueItems": true,
      "items": [
        {
          "type": "object",
          "required": [
            "name",
            "value"
          ],
          "properties": {
            "name": {
              "const": "param-required"
            },
            "value": {
              "anyOf": [
                {
                  "$ref": "#/$defs/test-ref1"
                },
                {
                  "$ref": "#/$defs/test-ref2"
                }
              ]
            }
          }
        }
      ],
      "additionalItems": {
        "oneOf": [
          {
            "type": "object",
            "required": [
              "name",
              "value"
            ],
            "properties": {
              "name": {
                "const": "param-optional"
              },
              "value": {
                "anyOf": [
                  {
                    "$ref": "#/$defs/test-ref1"
                  },
                  {
                    "$ref": "#/$defs/test-ref2"
                  }
                ]
              }
            }
          }
        ]
      },
      "minItems": 1,
      "maxItems": 2
    }
  },
  "$defs": {
    "test-ref1": {
      "type": "string",
      "pattern": "^\\{\\{.+\\}\\}$"
    },
    "test-ref2": {
      "type": "integer"
    }
  }
}
```

When I try to validate the following data:
```
{
  "parameters": [
    {
      "name": "param-required",
      "value": 123
    },
    {
      "name": "param-optional",
      "value": "{{test}}"
    }
  ]
}
```

I got the exception:
```
com.networknt.schema.JsonSchemaException: anyOf/$ref: Reference #/$defs/test-ref1 cannot be resolved
	at com.networknt.schema.RefValidator.<init>(RefValidator.java:48)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
```

Seems when looping to 'findAncestor' from `"$ref": "#/$defs/test-ref1"`, the 'root' is 'additionalItems' but not the root of the whole document. All reference works fine in 'items' section, only fails at 'additionalItems'. May I know if it is a bug? Or I need to copy all the '$defs' into 'additionalItems'?

**Comment by stevehu** [comment]
@carolkao I think it is very likely a bug. The use case you have is much more complicated than the official test suite and that is why the bug is not identified so far. Could you please add your test case and try to get it resolved? As you said, the issue might be in the additionalItems. Thanks a lot for raising this issue.

**Comment by carolkao** [comment]
@stevehu Thank you for your reply. Unfortunately, I haven't find the root cause of this problem and don't know how to resolve it so far. If you can give me some clue or hint will be appreciated, and I'm willing to contribute it.

**Comment by carolkao** [comment]
Hi @stevehu ,
I've created a PR : https://github.com/networknt/json-schema-validator/pull/497 for fixing the issue. Please help to review and let me know if there exists any problem. Thank you!

**Comment by stevehu** [comment]
@carolkao Thanks a lot for your help. I will schedule a release soon.

**Comment by carolkao** [comment]
@stevehu Appreciate your review, I'm looking forward to having the new version. Since the PR is merged already, I can close this issue. Thanks again.

**Comment by carolkao** [comment]
Hi @stevehu,

May I know the schedule of the next release? Thank you.

Best regards,
Carol

**Comment by stevehu** [comment]
We have several pending PRs in the pipeline. Once they are merged and tested, I will release another version. Stay Tuned. Thanks.

**Comment by carolkao** [comment]
Got it. Thank you.
