### ISSUE TITLE
additionalProperties: false used to work

### ISSUE THREAD

**Issue by huubfleuren** [networknt/json-schema-validator#498]
Hi, recently we've upgraded the validator in our  project from 1.0.44 to 1.0.65.

Apperently the AdditionalPropertiesValidator behaves differently. 

in version 1.0.44 the validator correctly produced an error if a property was not in the list, ut now it finds too many properties.

This appears to be the case where a `OneOf` schema is in the play

I didn't really look into it: the new version creates a list of errors some of which are correct and others (where a OneOf is involved) are not. But this entire list of erorrs is never in the endresult.

The sample schema below goes wrong:

Property 'stuff' of some Chemical  would have to be either Stuff or StuffCategory but it says for instance that stuff.CASnumber is additional.

```e,.g

   Chemical:
      properties:
        stuff:
          $ref: '#/components/schemas/StuffOrStuffcategory'

    StuffOrStuffcategory:
      oneOf:
        - $ref: '#/components/schemas/Stuff'
        - $ref: '#/components/schemas/StuffCategory'

    Stuff:
      type: object
      **additionalProperties: false**
      properties:
        CASnumber:
          type: string
        chemicalName:
          type: string
        name:
          type: string
        UNnumber:
          type: string

    StuffCategory:
      type: object
      **additionalProperties: false**
      properties:
        categorieName:
          type: string
        chemicalName:
          type: string

**Comment by stevehu** [comment]
Some changes recently might break the additionalProperties. You only provide the schema. Could you please create a test case and submit a PR?

**Comment by huubfleuren** [comment]
Thanks Steve, for the reply.
Allthough I managed to prepare a testcase in JsonScheema I did not see this again after deleting a piece of code we added in 1.44.0. So maybe I will return to this later.
Great lib. Complicated matter too, so respect.

**Comment by stevehu** [comment]
As the PR is merged, I am closing this issue.
