### ISSUE TITLE
$recursiveRef Incorrect For Draft 2019-09

### ISSUE THREAD

**Issue by tomdeering-wf** [networknt/json-schema-validator#507]
It looks like `$recursiveRef` does not correctly resolve to a `$recursiveAnchor` with Draft 2019-09. Consider the 2019 metaschema with its vocabulary references inlined into the schema (the recommended way using `$defs`):

[2019-09.txt](https://github.com/networknt/json-schema-validator/files/7989366/2019-09.txt)  (.txt extension because GitHub doesn't support .json)

Attempting to load this schema yields the following exception:
`com.networknt.schema.JsonSchemaException: anyOf/$ref: Reference #/$defs/simpleTypes cannot be resolved`

But this `$recursiveRef` should resolve without issue.

**Comment by stevehu** [comment]
@tomdeering-wf We have a community PR to get the $recurisiveRef implemented but I am guessing there might be some gaps left. I am wondering if you could create a test case and debug into it to find the root cause and get it resolved. Thanks.
