### ISSUE TITLE
Embedded schema error - Failed to load json schema!

### ISSUE THREAD

**Issue by tthapa-incomm** [networknt/json-schema-validator#513]
Trying this library for new project. I got this error while using embedded schema. Shouldn't it fetch from embedded schema? Am I missing some configurations or doing it wrong?

**09:30:05.674 [main] ERROR com.networknt.schema.JsonSchemaFactory - Failed to load json schema!
java.io.FileNotFoundException: https://abc.com/schemas/name.schema.json**

Data:
```
{
  "name": {
    "first-name": "abc",
    "last-name": "xyz"
  }
}
```
Schema:
```
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://abc.com/schemas/parent.schema.json",
  "type": "object",
  "required": [
    "name"
  ],
  "properties": {
    "name": {
      "$ref": "/schemas/name.schema.json"
    }
  },
  "$defs": {
    "https://abc.com/schemas/name.schema.json": {
      "$schema": "https://json-schema.org/draft/2019-09/schema",
      "$id": "https://abc.com/schemas/name.schema.json",
      "type": "object",
      "properties": {
        "first-name": {
          "type": "string"
        },
        "last_name": {
          "type": "string"
        }
      }
    }
  }
}
```

**Comment by stevehu** [comment]
I don't think this abc.com is valid. Try to access it directly and nothing returned. Could you please double-check?

**Comment by tthapa-incomm** [comment]
Hi @stevehu

Yes abc.com is not valid.  Since I embeded ``name.schema.json`` within parent under ``$defs`` with proper base URI, I was expecting `` "$ref": "/schemas/name.schema.json" `` to refer to the embedded schema instead of making network call. For example if I use same schema in online validator https://www.jsonschemavalidator.net/ it properly validates the data.

**Comment by stevehu** [comment]
$ref support both local reference and remote reference and your syntax is definitely remote. That is why the library is trying to access the remote site. If you want to use your local reference, make the update in your schema. Thanks.

**Comment by tthapa-incomm** [comment]
@stevehu I know you closed this but just for context I was trying to bundle schema as described here - https://json-schema.org/blog/posts/bundling-json-schema-compound-documents so that I can distribute and use it offline without network call. Thanks anyway.
