### ISSUE TITLE
fix the additionalProperties in oneOf failed test cases

### ISSUE THREAD

**Issue by stevehu** [networknt/json-schema-validator#516]
These test cases were submitted by @huubfleuren and I just market them as disabled for now. Our developers can pick them up and get them fixed. 

@huubfleuren Have you tested under version 1.0.44? Are they fail as well in 1.0.44? Thanks.

**Comment by huubfleuren** [comment]
Good one. Thanks. I did n**o**t test it on 1.0.44, but nowIi have and results differ. It is not flawless either, but where there is ambivalence this is acceptable of course.



||AdditionalPropertiesOneOfFailsTest||
|---|---|---|
|test|master|1.0.44|
|heightIsNotMissingNotOnceAndNotTwice()|v|v|
|chemicalCharacteristicNameIsAdditional()|-|-|
|chemicalCharacteristicCategoryNameIsDefined()|v|v|
|heightWrongType()|-|-|
|depthIsAdditional()|-|-|
|weightIsMissingOnlyOnce()|-|v|
|toxicIsAdditional()|-|v|

**Comment by stevehu** [comment]
@huubfleuren Thanks a lot for your detailed comparison. I think we need a code analysis between the two versions to see what has been changed for the part.

**Comment by fdutton** [comment]
#720
