### ISSUE TITLE
Preserving suffix `#` during metachema URI normalization

### ISSUE THREAD

**Issue by pondzix** [networknt/json-schema-validator#518]
In [iglu-client](https://github.com/snowplow/iglu-scala-client) we use version of 1.0.39 java-schema-validator. In the code we define meta [schema](https://github.com/snowplow/iglu-scala-client/blob/e9b8b9c2718a45da0ce4c25d50cea54bdac5dfcf/modules/core/src/main/scala/com.snowplowanalytics.iglu/client/validator/CirceValidator.scala#L183): 

`http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#`

We're blocked with upgrade to newer version, because of URI normalization. Issue is described in detail [here](https://github.com/snowplow/iglu-scala-client/issues/136).

The case of `http` normalization can be easily fixed with disabling `forceHttps` flag introduced in [PR](https://github.com/networknt/json-schema-validator/pull/400), but the problem with trimming `#` is still present.

#### Proposed solution

Similar to `forceHttps` flag, we could introduce boolean option like `removeEmptyFragmentSuffix` which would be used in normalization. When enabled - remove `#`, when disable - leave `#`. Be default it would be enabled to preserve backward compatibility

I prepared [PR](https://github.com/networknt/json-schema-validator/pull/519) containing implementation of proposal. First [commit](https://github.com/networknt/json-schema-validator/pull/519/commits/c65900c4e968206c4abf343ee64067d293100218) contains test reproducing the issue. 

@stevehu Let me know what you think 🙂

**Comment by stevehu** [comment]
@pondzix Thanks a lot for your help. It is a nice fix that preserves backward compatibility.

**Comment by pondzix** [comment]
Awesome @stevehu and thank you for a quick response!
