### ISSUE TITLE
Json Schema Question

### ISSUE THREAD

**Issue by ohadabraham** [networknt/json-schema-validator#548]
Hi ,
would like to ask 2 questions 
1. where can i see all the properties and their values  i can set in the json schema to make validation  ? ( i.e int, string, obj  and check positive negative etc... )
2. can i make validation that say : this property is optional but if i get it i need to make vlidation ( and if it is not exists all ok )\
thank u

**Comment by chrswk** [comment]
Not sure if this answers your first questions, but I personally find the official site quite good:

https://json-schema.org/understanding-json-schema/reference/index.html

Regarding 2: Yes, this is possible, see [anyOf](https://json-schema.org/understanding-json-schema/reference/combining.html#anyof) (or oneOf, depending on your exact needs).

**Comment by ohadabraham** [comment]
Thank u ! I think i was misunderstood...
if i have this Schema for example :

{
  "$schema": "https://json-schema.org/draft/2019-09/schema#",
  "required": [],
  "properties": {
    "name": {
      "type": "string",
      "description": "Painting name",
      "maxLength": 10,
    }
}

i would like to name only if i got it in the request json ,
i.e. : 
valid : 
{
  "name": "Mona"
}
valid : 
{

}
non valid : 
{
  "name": "Mona Lisa 12345"
}

meaning validate if and only if i got it....

**Comment by ohadabraham** [comment]
any idea?

**Comment by chrswk** [comment]
It should work fine. This schema:

```
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "object",
    "additionalProperties": false,
    "required": [],
    "properties": {
        "name": {
            "type": "string",
            "description": "Painting name",
            "maxLength": 10
        }
    }
}
```

Is valid against:

```
{}
```

And:

```
{"name": "Hello"}
```

But fails with `$.name: may only be 10 characters long` for:

```
{"name": "Hello World"}
```

**Comment by ohadabraham** [comment]
you are right - thank u for the help !!!

**Comment by stevehu** [comment]
@ohadabraham It looks like you have the answer already. Thank you @chrswk for your help. I am closing this issue.
