### ISSUE TITLE
[Question] Does this tool provide Schema path?

### ISSUE THREAD

**Issue by ymszzq** [networknt/json-schema-validator#550]
I see ValidationMessage provide the path to the input json. I couldn't find the path to schema at where the error throws.

Can you please confirm if I understand it correctly?

Are there any plans to support this? I think it is quite important.

**Comment by ymszzq** [comment]
I can submit a PR

**Comment by stevehu** [comment]
@ymszzq Thanks a lot for your help. The PR is merged and will be in the next release.

**Comment by ymszzq** [comment]
My pleasure!

When will you release next time?

Thanks

**Comment by stevehu** [comment]
The PR was merged in April, and we have released several versions since then.
