### ISSUE TITLE
default as null is not being set

### ISSUE THREAD

**Issue by harishvashistha** [networknt/json-schema-validator#553]
Hi Team,

if schema definition specifies that `"default":null ` when that property is not specified in json resource then why there is this check in code which sets default values only when those values are non-null. You are requested to please think about below section of code when we want default = null should be set when no value is provided explicitly. e.g.

```
"schema": {
      "properties": {
        "values": {
          "type": "string",
          "nullable": true,
          "default": null
        },
       "id":{
           "type": "string",
          "nullable": true,
          "default": "US-12"
        }
      }
    }
```
Resource to be created:

```
"data":{

}
```
we want `public ValidationResult walk(JsonNode node, boolean shouldValidateSchema)` in `JsonSchema.class` should result into this:

```
"data":{
   "values": null,
   "id":"US-12"
}
```
But it actually returns this:
```
"data":{
   "id":"US-12"
}
```

which is not acceptable when this payload is provided to those languages where having null value has different meaning than having non existence of key altogether. You are requested to please help here. As this code is affecting us:

```
private void applyPropertyDefaults(ObjectNode node) {
        for (Map.Entry<String, JsonSchema> entry : schemas.entrySet()) {
            JsonNode propertyNode = node.get(entry.getKey());

            if (propertyNode == null || (applyDefaultsStrategy.shouldApplyPropertyDefaultsIfNull() && propertyNode.isNull())) {
                JsonSchema propertySchema = entry.getValue();
                JsonNode defaultNode = propertySchema.getSchemaNode().get("default");
                if (defaultNode != null && !defaultNode.isNull()) {
                    // mutate the input json
                    node.set(entry.getKey(), defaultNode);
                }
            }
        }
    }
```

in propertiesValidator.java file

**Comment by stevehu** [comment]
Please take a look at this class. 

https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/ApplyDefaultsStrategy.java

**Comment by harishvashistha** [comment]
@stevehu I have set this configuration for `SchemaValidatorsConfig` :

```
@Bean
    public SchemaValidatorsConfig schemaValidatorsConfig() {
        ApplyDefaultsStrategy applyDefaultsStrategy =
                new ApplyDefaultsStrategy(true, true, true);
        SchemaValidatorsConfig schemaValidatorsConfig = new SchemaValidatorsConfig();
        schemaValidatorsConfig.setTypeLoose(false);
        schemaValidatorsConfig.setApplyDefaultsStrategy(applyDefaultsStrategy);
        return schemaValidatorsConfig;
    }
```

I have put and verified with debug points in json-schema-validator code. This is the behavior it is showing:

if default value in schema definition is not null, then only default value is set in the resource when `ApplyDefaultStrategy` has `applyPropertyDefaults` parameter as true. because of this code:

```
if (propertyNode == null || (applyDefaultsStrategy.shouldApplyPropertyDefaultsIfNull() && propertyNode.isNull())) {
                JsonSchema propertySchema = entry.getValue();
                JsonNode defaultNode = propertySchema.getSchemaNode().get("default");
                if (defaultNode != null && !defaultNode.isNull()) {
                    // mutate the input json
                    node.set(entry.getKey(), defaultNode);
                }
            }
```

under method `private void applyPropertyDefaults(ObjectNode node)`. Here it is checking if default value is null then don't set the node with key and value rather set it only when default value is not null. what configuration I can further provide.

**Comment by stevehu** [comment]
The release 1.0.69 is published. Thanks, @harishvashistha and @SiemelNaran for your help to make this happen.
