### ISSUE TITLE
Support both Java 8 and Java 11

### ISSUE THREAD

**Issue by stevehu** [networknt/json-schema-validator#562]
We have a PR for upgrading to Java 11 at https://github.com/networknt/json-schema-validator/pull/403

I am opening this issue to discuss the solutions. I am thinking to move the current codebase to 1.0.x branch and use the master branch for Java 11 in the future with 2.0.x tag for releases. New PRs will go to the master branch for Java 11 implementation and only bug fixes go to Java 8 branch 1.0.x. What do you guys think?

**Comment by fdutton** [comment]
I have a few thoughts on this:
- I like the idea of using Java 11's module support to separate the public API from the implementation. Many of the changes I'm making would be easier if I knew that client's have not subclassed an implementation class.
- Starting work on 2.0 allows make some improvements to the API and possibly add a SPI.
- Maintaining two versions would be difficult even if it is just bug fixes. I would not start this effort until all the JSON Schema Test Suite checks pass.

**Comment by stevehu** [comment]
We can have two branches, 1.0.x for Java 8 and the master branch for 2.0.x tags in Java 11. For Java 8, we don't add new features but only bug fixes so that we can encourage users to move to Java 11 as fast as possible. Let's do that once we have all the tests passed. Thanks.
