### ISSUE TITLE
Allow specifying custom message at the attribute level

### ISSUE THREAD

**Issue by Tim-fors** [networknt/json-schema-validator#563]
Continuation of discussion from https://github.com/networknt/json-schema-validator/pull/440#issuecomment-1050048438

The[ custom message feature ](https://github.com/networknt/json-schema-validator/blob/master/doc/cust-msg.md) allows a user to specify a custom validation message based on the type of validation.  However, this is limited in that you can only have one message per type. 

It would be nice if it was possible to specify this at each attribute, for example 
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "firstName": {
      "type": "string",
      "description": "The person's first name.",
      "message": {
        "type": "Invalid type, should be string"}
    },
    "foo": {
      "type": "array",
      "maxItems": 3,
      "message": {
        "maxItems" : "MaxItem must be 3 only",
        "type" : "Invalid type, should be array"
      }
    }
  }
}
```

**Comment by stevehu** [comment]
@Tim-fors While thinking about it, it is not easy to do to cover all the scenarios. Also, I think this should be a joint effort with the spec team. As of now, they don't want to define the messages in the schema but I think it would be a good option. Do you want to open a discussion over there to see what is the response from the spec team? Thanks.

**Comment by stevehu** [comment]
We have some validators that support this feature. If this is not enough, please let us know. Thanks.
