### ISSUE TITLE
Major performance regression caused by unevaluatedProperties

### ISSUE THREAD

**Issue by dreis2211** [networknt/json-schema-validator#564]
Hi,

I've seen an internal customer project being on an ancient version (0.1.3) and wanted to upgrade things. After the update to 1.0.69 (latest at the point of writing) things still seem to work, but show a major performance regression.

A little microbenchmark that validates a typical json for us shows the following numbers:
**1.0.69**
```
Benchmark                         Mode  Cnt      Score     Error  Units
MyBenchmark.testValidate          avgt   10  46884,301 ± 764,721  ns/op
```

**1.0.67**
```
Benchmark                         Mode  Cnt      Score     Error  Units
MyBenchmark.testValidate          avgt   10  26214,556 ± 425,732  ns/op
```

**0.1.3**
```
Benchmark                         Mode  Cnt      Score     Error  Units
MyBenchmark.testValidate         avgt   10  14705,189 ± 986,189  ns/op
```

The regression between 1.0.67 and 1.0.69 can be largely traced back to the work on unevaluated properties in #534 & #544 , I think. Ideally, when the schema doesn't contain this keyword - like in our case - this overhead should be avoided.

The regression between 0.1.3 and 1.0.67 is probably caused by numerous things, but one bigger portion is likely driven by the `CollectorContext` infrastructure and its repeated `Map.get` calls. This is also why the unevaluated properties is so expensive I think.

The purple highlights in the following (reversed) flamegraph of 1.0.69 show the `CollectorContext` being one of the main drivers.
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/6304496/165903194-6f7ade47-f832-4586-b17a-f69221bbbc78.png">

For 1.0.67 it shows the following - less but still a significant time is spent on the  `CollectorContext`.
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/6304496/165903692-f396b129-486f-41ab-a232-cf30e810d1d9.png">

Cheers,
Christoph

**Comment by stevehu** [comment]
@dreis2211 I have rerun the performance test and successfully reproduced what you have observed. Thanks a lot for raising it and I will try to get it fixed.

**Comment by prashanthjos** [comment]
Hi @dreis2211 thank you for bringing this up I will take a look into this. I think we can avoid multiple calls to the `CollectorContext` by a simple check like `hasEvaluatedProperties`, this check is similar to `hasRequiredProperties` method in `JsonSchema.java`.

@stevehu is there anyway I can run the performance test setup you already have. I want to check the perf tests after I have fixed this issue.

Thanks in advance.

**Comment by dreis2211** [comment]
As shown above the unevaluatedProperties optimization only reduces things, but networknt has not the fastest schema validator anymore even if this is fixed. Feel free to repurpose this ticket to apply some more general performance work or create a new ticket for further work and keep this focussed at the the unevaluated properties stuff.

**Comment by dreis2211** [comment]
@prashanthjos I guess @stevehu just ran https://github.com/networknt/json-schema-validator-perftest . Although it's not a perfect benchmark it shows the regressions as well.

**Comment by stevehu** [comment]
we have a performance test repo that I am currently working on to upgrade to the latest and hooked with JProfiler. Please be aware that the test case was focused on V4 only as other libraries won't support the latest version of the specifications. 

I am going to remove the Fge as it is not active anymore and the developer has given up the repo. Also, I will upgrade the test to V7 as the everit supports up to [V7](https://github.com/everit-org/json-schema/issues/441). 

Once we finish this upgrade, we might add other active libraries. 

https://github.com/networknt/json-schema-validator-perftest

**Comment by stevehu** [comment]
I have updated the perftest repo and rerun the tests in both IDE and java -jar. The following is the link to the test result. 

https://github.com/networknt/json-schema-validator-perftest#results-2022-05-02

I have no idea why the networknt validator is twice as fast as running with java -jar.

**Comment by ThanksForAllTheFish** [comment]
> I am going to remove the Fge as it is not active anymore and the developer has given up the repo. Also, I will upgrade the test to V7 as the everit supports up to [V7](https://github.com/everit-org/json-schema/issues/441).

Hopefully it does not sound too blunt, but what is the purpose of comparing performance for v7? There are 2 drafts after that, which puts (imo) v7 in the realm of legacy. I understand advertisement, I guess, but if that is the reason I would focus on supporting draft2020 and be the [first one in java](https://json-schema.org/implementations.html#validators) (might be a weaker claim, since other libs can catch up, but for people like me who look at the latest it could mean I know where to look when the next json schema drafts come out)

**Comment by fdutton** [comment]
@dreis2211 Please try 1.0.81 and let us know how we are doing.
