### ISSUE TITLE
date-time fields with valid negative offsets are marked as invalid - need to upgrade com.ethlo.time:itu to version 1.7.0

### ISSUE THREAD

**Issue by jody-mcdonnell** [networknt/json-schema-validator#575]
Using version 1.0.69 of json-schema-validator, date-time values with certain valid negative offsets (for example, "2022-05-25T08:27:53-02:30", Newfoundland time) fail validation.

The problem is with the com.ethlo.time:itu library. If this library is updated from version 1.5.1 to version 1.7.0, this problem goes away. We have been overriding this dependency in our applications to avoid this issue, but it would be better if json-schema-validator did the upgrade itself.

**Comment by stevehu** [comment]
@jody-mcdonnell Thanks a lot for pointing this out. Would you be able to submit a PR to get it fixed? Thanks.
