### ISSUE TITLE
Generate Sample Json from the given schema

### ISSUE THREAD

**Issue by sangeet123** [networknt/json-schema-validator#577]
I am wondering if there is a way to generate a sample Json document from the given schema document. For Example for the following schema

```
{
  "properties": {
    "pizzaType": {
      "description": "The pizza type",
      "type": "string"
    },
    "size": {
      "description": "The pizza size",
      "type": "integer"
    }
  }
}
```

something like this
```
{
"type": ""
 "size":0
}
```

**Comment by stevehu** [comment]
It is not easy as there might be millions of different JSON nodes that match a schema. However, if you only want to generate a default JSON, it is doable. Take a look at the [walker feature](https://github.com/networknt/json-schema-validator/blob/master/doc/walkers.md) and how it set the default value along with walking.

**Comment by sangeet123** [comment]
thanks that resolves my concern
