### ISSUE TITLE
Use JSON Pointer for ValidationMessage.path()

### ISSUE THREAD

**Issue by ehrmann** [networknt/json-schema-validator#58]
Currently, paths are built in a format like `$.foo.bar[0]`. It's almost like `jq`, but not quite.

What are your thoughts on using an [RFC-6901 JSON Pointer](https://tools.ietf.org/html/rfc6901) instead? The format looks more like `/foo/bar/0`. It's [supported out-of-the-box by Jackson](https://fasterxml.github.io/jackson-databind/javadoc/2.3.0/com/fasterxml/jackson/databind/JsonNode.html#at(com.fasterxml.jackson.core.JsonPointer)), and it resolves ambiguities with characters like `[` and `.` being in field names.

It's something I can open a PR for, but I wanted to ask your opinion before doing the work.

**Comment by stevehu** [comment]
@ehrmann It is JSONPath format and I think it is more powerful than JSON Pointer at the moment. In my light-bot project I am building test integration test cases and use JSON Path to assert the error messages. There is no RFC for JSONPath but I think it is used more often than JSON Pointer at the moment. In my opinion, we should support both and let end user to choose which format they want in the ValidationMessage. To ensure that the current users won't be impacted, let's make the JSONPath as default. Here is a link that is discussing these two.

https://www.tbray.org/ongoing/When/201x/2017/04/14/JsonPath-Needs-Work

**Comment by ehrmann** [comment]
Supporting both is reasonable enough. The only thing with JSONPath is that you don't actually need the flexibility here. Validation errors happen on nodes that can be accessed just by index and property. Index slicing, relative paths, and filters don't help much, here. That's also the reason JSON Pointer hasn't seen much use; it doesn't really do much.

**Comment by stevehu** [comment]
I am planning to refactor this library with [config](https://doc.networknt.com/concern/config/) and [service](https://doc.networknt.com/concern/service/). Once it is done, it will be very easy for users to replace any implementations in service.yml config file. Not just for the path builder but also validators etc. The only problem with me is there is no time :)
