### ISSUE TITLE
[Question] Is there a way to validate the 'schema' is valid or not?

### ISSUE THREAD

**Issue by carolkao** [networknt/json-schema-validator#581]
Hi,
I'm wondering if this library provide a way to know the 'JsonSchema' is a valid schema or not. Like in the following code snippet:
```
JsonSchema schema = factory.getSchema(jsonSchemaString);
schema.validate(node)
```
A `JsonSchemaException` will be threw during 'validate' method call if the schema has something wrong (ex: $ref path not exist). Is there a way to know the problem earlier like during building the JsonSchema object? 

Thanks,
Carol

**Comment by stevehu** [comment]
You can use the right version meta schema to validate your schema.

**Comment by carolkao** [comment]
However, in the case of "$ref not exist" cannot be reported during the validation. For example, I have a schema
```
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "object",
  "required": [
    "prop1"
  ],
  "properties": {
    "prop1": {
      "$ref": "not-exist-path"
    }
  }
}
```

I built the JsonSchema with "https://json-schema.org/draft/2019-09/schema" and do the validation. There is no ValidationMessage returned. 
```
JsonSchema schema = factory.getSchema(new URI("https://json-schema.org/draft/2019-09/schema"));
Set<ValidationMessage> set = schema.validate(jsonSchemaNode);
// set is empty
```
The exception will be threw when I use this schema to validate another node with "input" property. So I'm wondering if there is some way to notice this kind of error earlier.

Thank you!

**Comment by stevehu** [comment]
We have some issues loading the 2019-09 meta schema as it has some new keywords that we don't support. It has been discussed in other issues that we should manually construct a meta schema and save it locally with all the references resolved. It is still not done yet due to resource limitations.

**Comment by carolkao** [comment]
Thanks for your reply. Currently, I just catch the 'JsonSchemaException' when doing validation and handling it as my workaround. I can close the case, thank you again.
