### ISSUE TITLE
Json Schema order is not maintained for Schema's with multiple object

### ISSUE THREAD

**Issue by sabarinathan590** [networknt/json-schema-validator#584]
Order of Schema validation message with in a object is maintained. However when a schema with multiple object (group of fields) is validated. Each object is validated with out any order and hence the message is are coming without any order.

On first level analysis, I have noticed that the schema is iterated and stored in HashMap where the order of the schema object is lost. Can we change it to Linked Hashmap. So that the order can be preserved.

Note: This is useful in case of UI form validation where toggling of error fields can be done based on the error message received.

groupId : com.networknt
artifactId : json-schema-validator
version : 1.0.70
Class: com.networknt.schema.PropertiesValidator
Location: Line number 32.

**Comment by stevehu** [comment]
@sabarinathan590 Thanks for raising this issue. It makes sense to change it to LinkedHashMap to reserve the order. Would you please submit a PR to get it fixed? Thanks.

**Comment by sabarinathan590** [comment]
Hi @stevehu , Can we close this issue as the PR is already merged to master ?
