### ISSUE TITLE
[FR] Remove commons lang as dependency

### ISSUE THREAD

**Issue by agentgt** [networknt/json-schema-validator#595]
See #594 

For our company to use this project we would like Commons Lang to not be a dependency as none of our projects use it anymore.

If there was extensive use of the library I would not have bothered but I looked it appears just `StringUtils.isBlank` and `StringUtils.equals` was used.

Thus I went ahead via the above PR and implemented the changes which were fairly trivial.

However downstream projects will still have to exclude the commons lang dependency but at least it will run without it.

**Comment by stevehu** [comment]
Thanks @agentgt. It makes perfect sense to reduce the dependencies to make our users' lives easier.

**Comment by fdutton** [comment]
@stevehu Since the PR was merged, should this issue be closed?
