### ISSUE TITLE
Simple, non-array dependencies don't work

### ISSUE THREAD

**Issue by ehrmann** [networknt/json-schema-validator#60]
It [looks like](https://github.com/networknt/json-schema-validator/blob/3008efb2c375f2708bdcaf990b2cdb07181100cb/src/main/java/com/networknt/schema/DependenciesValidator.java#L34-L49) only full schemas and arrays of properties are supported. Single property dependencies don't validate correctly.

Doesn't work:
```
{
    "dependencies": {
        "a": "b",
    }
}
```

Works:
```
{
    "dependencies": {
        "a": ["b"],
    }
}
```

**Comment by stevehu** [comment]
@ehrmann Frankly, I never use the dependencies in json schema although my frameworks all depending on the this library. Here is the spec copied/pasted and it looks like the key is a string and value is an array. Do you have other information regarding to the first case? Thanks.

```
                <section title="dependencies">
                    <t>
                        <cref>
                            Now that "if", "then", and "else" are keywords, it is not clear whether
                            there is any benefit in keeping the schema form of "dependencies".
                            It is frequently misunderstood, and having a form that takes a subschema
                            as well as a form that takes a primitive value is particularly
                            confusing.  And it seems to be rarely used.  Depending on feedback
                            with "if", "then", and "else", the schema form of this keyword may
                            well be removed in a future draft.  Current thought is that the string
                            form (giving property names in an array) is a useful shortcut.
                        </cref>
                    </t>
                    <t>
                        This keyword specifies rules that are evaluated if the instance is an object and
                        contains a certain property.
                    </t>
                    <t>
                        This keyword's value MUST be an object. Each property specifies a dependency.
                        Each dependency value MUST be an array or a valid JSON Schema.
                    </t>
                    <t>
                        If the dependency value is a subschema, and the dependency key is a property
                        in the instance, the entire instance must validate against the dependency value.
                    </t>
                    <t>
                        If the dependency value is an array, each element in the array,
                        if any, MUST be a string, and MUST be unique. If the dependency key is
                        a property in the instance, each of the items in the dependency
                        value must be a property that exists in the instance.
                    </t>
                    <t>
                        Omitting this keyword has the same behavior as an empty object.
                    </t>
                </section>

```

**Comment by ehrmann** [comment]
`"dependencies": { "a": "b" }` means that if the property `a` is present, `b` must be present.

`"dependencies": { "a": ["b", "c"]}` means that if the property `a` is present, `b` and `c` must be present.

`"dependencies": { "a": { <schema> }}` means that if the property `a` is present, it (the parent of a) must validate against the given schema.

e.g.
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "dependencies": {
    "a": {
      "properties": {
        "b": {
          "type": "number"
        }
      }
    }
  }
}
```

valid: ```{ "b": true }```
valid: ```{ "a": true, "b": 10}```
invalid: ```{ "a": true, "b": true}```
invalid: ```{ "a": true}```

The rest of the commentary is on how `dependencies` doesn't make as much sense in the new json schema version.

**Comment by stevehu** [comment]
@ehrmann The spec is changing all the time and the library was built with v4 and there are a lot of community enhancements in the last few months. At this moment, it is a mix of spec between v4 and v6. I am planning to refactor this library to allow users to choose which version of spec or even customize each validators. Meanwhile, would you be able to update this handler and submit a pull request? As this is an enhancement, I don't think it will break existing customers. Thanks.

**Comment by stevehu** [comment]
This should have been resolved by v6/7/2019-09.
