### ISSUE TITLE
18 out of 61 2019-09 offical tests are disabled

### ISSUE THREAD

**Issue by anthonyleonard** [networknt/json-schema-validator#601]
18 out of 61 of the offical 2019-09 tests are disabled in this project.

https://github.com/networknt/json-schema-validator/blob/master/src/test/java/com/networknt/schema/V201909JsonSchemaTest.java

I am writing up pros and cons of different Java libraries for my organisation. Though this library scores highly for being the most actively maintained, this level of non-compliance for a 3 year old draft seems very high.

**Comment by fdutton** [comment]
@anthonyleonard You can track our progress in two places:
- [Compliance with the JSON Schema Test Suite](https://github.com/networknt/json-schema-validator/blob/master/doc/compatibility.md)
- [What is currently disabled](https://github.com/networknt/json-schema-validator/blob/master/src/test/java/com/networknt/schema/JsonSchemaTestSuiteTest.java)

As you can deduce from the second link, we have some work to do when it comes to resolving references. The delay comes from identifying how to implement the specification without breaking existing clients and doing so without sacrificing performance.
