### ISSUE TITLE
Validate the request body against OpenAPI schema

### ISSUE THREAD

**Issue by parameshjava** [networknt/json-schema-validator#610]
I need to build an API to validate the request body against the registered schema for the respective `type` & `subType`.

API Contract:

```json
{
	"id": "<any-uuid>",
	"type": "<some-type>",
	"subType": "<some-sub-type>",
	"data": {
		
	}
}
```

Here, OpenAPI schema will be fetched based on the `type` and `subType` and then need to validate the `data` element against the respective OpenAPI schema.

Wrote the below snippet:

```java
Map<String, Object> data = //get the data object from API request body;
JsonSchemaFactory jsonSchemaFactory = JsonSchemaFactory.getInstance(VersionFlag.V7);
ObjectMapper objectMapper = new ObjectMapper();
JsonNode node = objectMapper.convertValue(data, JsonNode.class);
String schemaJson = // fetch the registered schema for type and subtype
JsonSchema schema = jsonSchemaFactory.getSchema(schemaJson);
Set<ValidationMessage> errors = schema.validate(node);

// Throw exception when errors present in the Json Payload
if (errors.size() > 0) {
    // throw the exception with errors
}
```

This code is working, when the schema don't have:
1. Few elements such as `openapi`, `paths`, `info`, `components`.
2. When one object not referring other. 

* API Schema in our database as follows:

```json
{
  "openapi": "3.0.0",
  "paths": {},
  "info": {
    "title": "Patient Info API",
    "version": "v0.1.0"
  },
  "components": {
    "schemas": {
      "Data": {
        "type": "object",
        "required": [
          "action",
          "patient"
        ],
        "properties": {
          "action": {
            "type": "string",
            "enum": [
              "ADMIT",
              "DISCHARGE",
              "TRANSFER"
            ]
          },
          "patient": {
            "$ref": "#/components/schemas/Patient"
          }
        }
      },
      "Patient": {
        "type": "object",
        "required": [
          "firstName",
          "lastName"
        ],
        "properties": {
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

* The `data` element in the API request body looks like this.

```json
{
    "action": "ADMIT",
    "patient": {
        "firstName": "John",
        "lastName": "Doe"
    }
}
```

Can [json-schema-validator](https://github.com/networknt/json-schema-validator) can help to achieve this?

**Comment by stevehu** [comment]
This is the main use case this library addresses. We are using it to validate the request and response in the restful API framework light-rest-4j. Here is the class that might help. 

https://github.com/networknt/light-rest-4j/blob/master/openapi-validator/src/main/java/com/networknt/openapi/RequestValidator.java

Also, here is another project that is used for other frameworks. 

https://github.com/mservicetech/openapi-schema-validation

**Comment by pietro-saccani** [comment]
Sorry if I comment here, but I need to do this too and I feel like using this library would be "cleaner" over using the "openapi-schema-validation" one. But maybe I'll have to switch.  
  
In the `RequestValidator` class you linked, you're using your own classes like `com.networknt.oas.model.Parameter` which can already easily let you retrieve the schema of a specific property, when you need to validate it.  
How would I do that if I'm using another web framework like Jersey (which will be replaced by Spring MVC, later), which isn't compatible with that class?  
  
I thought that after parsing my yaml schema into a `JsonSchema` object I would be able to extract "sub-schemas" of specific parts of it, like the descriptor of a certain parameter for a certain API endpoint, to "manually" validate that parameter in my code. But I didn't find how to do that. Is there an example somewhere?  
Do I have to parse the yaml as a `JsonNode` first, then extract the one sub-node I need and parse it as a schema? Or what?  
  
Thanks for the help.

**Comment by stevehu** [comment]
Both projects are open source, and you can read the code to understand how we treat the open API specification.
