### ISSUE TITLE
Handle multiple schemas with remote relative reference

### ISSUE THREAD

**Issue by slimakanzer94** [networknt/json-schema-validator#611]
Hello, I encountered with problem handling $ref for multiple schemas. My aplication needs to download schemas from external resource and validate some data against those schemas, the problem is that this schemas contains remote relative reference (not URL), for instance `{
  "$ref": "subSchemas.json#/definitions/example"
}` 
I figured out the only way how to solve it, download those schemas and store it in runtime, make $ref to reference to a local fil in the system `{
  "$ref": "file:subSchemas.json#/definitions/example"
}`
I'm wondering are there another way to handle it? Using $ref as reference to external server resource (URL) is not possible
Thanks in advance!

**Comment by stevehu** [comment]
The reference must be resolvable in your JSON file. subschema.json cannot be resolved within an URL context.
