### ISSUE TITLE
Object defined in array items is not properly validated

### ISSUE THREAD

**Issue by fuchsst** [networknt/json-schema-validator#621]
The following Json should fail but the validation succeeds:

Json:
```json
{
  "id" : "sdrn:spid.no:user:7593764",
  "additionalIds" : [ {
    "id" : "sdrn:messaging:user:123321"
    "someUnknownAttribute": "abc"
  } ],
  "$schema" : "https://schema.mydomain.com/objects/Actor.json"
}
```

Schema:
```json
{
  "$id" : "https://schema.mydomain.com/objects/Actor.json",
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "title" : "Actor",
  "type" : "object",
  "additionalProperties" : false,
  "properties" : {
    "id" : {
      "pattern" : "^sdrn:([^:]+):(user):(.*)$",
      "type" : "string"
    },
    "additionalIds" : {
      "type" : "array",
      "items" : {
        "required" : [ "id", "component" ],
        "type" : "object",
        "additionalProperties" : false,
        "properties" : {
          "id" : {
            "pattern" : "^sdrn:([^:]+):(user):(.*)$",
            "type" : "string"
          },
          "component" : {
            "type" : "string"
          }
        }
      }
    }
  }
}
```

It should fail as the `component` field in the items object of the array `additionalIds` is required but missing as well as there is an undefined property provided but additionalProperties is set to `false`, but it passes the validation.

The schema factory is initilized as follows:
```kotlin
  JsonSchemaFactory
      .builder()
      .objectMapper(mapper)
      .defaultMetaSchemaURI(JsonMetaSchema.getV202012().uri)
      .addMetaSchema(JsonMetaSchema.getV202012())
      .addUrnFactory(
          // redirects all remote $schema/$ref to local resource
          URNFactory { urn ->
              val absoluteURL = ClasspathURLFactory.convert(
                  ClasspathURLFactory().create("resource:/$urn")
              )
              ClasspathURLFactory.SUPPORTED_SCHEMES
              return@URNFactory absoluteURL.toURI()
          }
      )
      .build()
```

looks like the validator does not consider the items of a list properly? or do i do something wrong (other examples, including other invalid ones, are validated as expected)?

**Comment by thibautsacreste** [comment]
I just encountered this bug as well. Just to add to the report, it only seems to affect Draft 2020-12 but not Draft 07

Json:
```json
[ { "id": 1 } ]
```

Draft 07 Schema fails validation as expected with message `$[0].name: is missing but it is required`
```json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "array",
  "items": {
    "type": "object",
    "required": [ "id", "name" ],
    "properties": {
      "id": { "type": "integer" },
      "name": { "type": "string" }
    }
  }
}
```

Draft 2020-12 Schema passes validation
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "required": [ "id", "name" ],
    "properties": {
      "id": { "type": "integer" },
      "name": { "type": "string" }
    }
  }
}
```

**Comment by thibautsacreste** [comment]
I just found a workaround which might hint at the issue in Draft 2020-12. Setting the new `prefixItems` keyword to an empty array seems to fix the issue.

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "prefixItems": [],
  "items": {
    "type": "object",
    "required": [ "id", "name" ],
    "properties": {
      "id": { "type": "integer" },
      "name": { "type": "string" }
    }
  }
}
```

That's obviously not ideal, but it works. The JSON Schema spec explicitly says that `prefixItems` should not be empty:
https://json-schema.org/draft/2020-12/json-schema-core.html#section-10.3.1.1

**Comment by stevehu** [comment]
I think 2020-12 has changed items to prefixItems. There are a lot of changes in 2020-12 that reuse existing keywords. I might be wrong.

**Comment by thibautsacreste** [comment]
> I think 2020-12 has changed items to prefixItems. There are a lot of changes in 2020-12 that reuse existing keywords. I might be wrong.

`prefixItems` only replaces `items` for tuple validation. Both keywords can be used independently or in conjunction as described here:
https://json-schema.org/understanding-json-schema/reference/array.html

**Comment by jbaimoz** [comment]
I ran into the same issue for the version draft 2020-12 and noticed the following in the console log : 

`Unknown keyword items - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword`

Although it is stated [here](https://json-schema.org/understanding-json-schema/reference/array.html) that the keyword `items` is valid it seems that is not handled properly for this version (with the 2019-09 version there is no problem)

**Comment by aznan2** [comment]
This issue seems to be the same as #587.

**Comment by FrogDevelopper** [comment]
no update on this issue ?

**Comment by stevehu** [comment]
More people are not using the new specification 2020-12 yet. With the reuse of the keyword, we still need to find out how to support it within the same codebase. I am open to any PR to get this feature implemented. Thanks.

**Comment by stevehu** [comment]
This has been fixed by @fdutton.
