### ISSUE TITLE
Code example for meta-schema validation

### ISSUE THREAD

**Issue by manuelwaltschek** [networknt/json-schema-validator#622]
I do have the use case as well where I would like to validate custom schemas against draft 2019.

I saw that this topic was discussed in a few other issues, but I don't really know how to do it.
I understand, that I could use the schema as a JsonNode as a schema and then validate the custom schema against it by using it as the data object.

`        JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V201909)
            .getSchema(metaSchema)
            .validate(customSchema)
`

I still don't know how I can retrieve the value of `metaSchema`.
I've seen that in other issues it is mentioned, that it would be a possible solution to merge the vocabularies into a single file and then use it from the resource folder. 

I've seen that there is an implementation for JsonMetaSchema for version 2019. I was expecting this class to be able to perform validation, but I don't understand how to use the API.

I thought I could use 

`com.networknt.schema.JsonMetaSchema#newValidator`

for this task.

So my questions are:

Is it possible to perform meta-schema validation with the existing API without having to read in the meta-schema from a resource? (I understand that some keywords are ignored but this would not bother me too much for now)

@stevehu would it be possible that you could give me a code example on how meta schema validation should be done?

I am thinking about taking over this task of merging the resource file from the vocabularies but I don't understand how I would use it then.

**Comment by manuelwaltschek** [comment]
I've seen 
https://github.com/networknt/json-schema-validator/issues/581#issuecomment-1148239432
 would this be the correct way to do it for now?

**Comment by stevehu** [comment]
@manuelwaltschek Thanks a lot for your answer. I have created a doc based on your answer.
