### ISSUE TITLE
custom message from schema doesn't work for date format

### ISSUE THREAD

**Issue by andrew-lazovik** [networknt/json-schema-validator#627]
The custom message doesn't work for the date format
for example, json-schema:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "value": {
      "type": "string",
      "format": "date"
    }
  },
 "message": {
    "format": "Keep date format yyyy-mm-dd"
  },
  "required": [
    "value"
  ]
}
```

invalid json 
```
{
    "value": "2022-07-33"
}
```

after validation, I get the error message from the library:
`$.value: 2022-07-33 is an invalid date`

How can I create a custom error message from the schema for date format?

**Comment by vickyrathod** [comment]
@andrew-lazovik https://github.com/networknt/json-schema-validator/pull/632 opened PR for this issue.

**Comment by andrew-lazovik** [comment]
> @andrew-lazovik #632 opened PR for this issue.

Thank you
