### ISSUE TITLE
Make the API more extensible

### ISSUE THREAD

**Issue by mjburghoffer** [networknt/json-schema-validator#63]
I am trying to use this library, and have run into the following design issues:

- `JsonSchemaFactory` is a non-final class, but its only constructor is private
  - please make the constructor protected
- `JsonSchema` is a non-final class, but its useful constructors are all package private
  - make the constructors protected
  - extract an interface so consumers can customize behavior
- `JsonSchemaFactory.Builder` requires an instance of `JsonSchemaFactory` to instantiate - it seems silly to need to create an instance of a factory to create the builder of a new factory just to throw away the first initial factory.

In general, this library is great, but ultimately is unusable except for exactly how it was programmed.  A little bit of extenisbility would go a long way.

**Comment by stevehu** [comment]
@mjburghoffer You have a lot of good recommendations and I do realize that some sort of refactors need to be done. I have mentioned it in the following post. Just need to find two or three days to do it. 

https://github.com/networknt/json-schema-validator/issues/54

**Comment by mjburghoffer** [comment]
@stevehu thanks for responding so quickly!  Let me know if you'd like me to make a PR.

**Comment by stevehu** [comment]
Yes. Please. Just make sure that we keep the JsonSchemaFactory for now until we have a major release. There are a lot of people using this library and we cannot force them to make change. Thanks a lot for your help.

**Comment by nvdgit** [comment]
Any timeframe for this issue to be resolved, also referenced issue stackOverflowError loading schema file #96.

**Comment by stevehu** [comment]
I think the private constructor issue has been resolved already. For the circular dependency issue, we need more time to refactor it. I have already done that for openapi-parser but his library has not been done.

**Comment by stevehu** [comment]
I think most of the issues mentioned have been resolved. Closing it and will open individual issues if there is still a gap.
