### ISSUE TITLE
How to validate the items of a array?

### ISSUE THREAD

**Issue by j-d-o** [networknt/json-schema-validator#633]
Hi there,

Im pretty sure Im doing something stupid here, but I just dont see it. I have a schema that defines the type of JSON array entries and it seems that the validation just doesnt work.

The simple case:

var schema = "{\n" +
                    "  \\"$schema\\": \\"http://json-schema.org/draft/2020-12/schema#\\",\n" +
                    "  \\"type\": \\"array\\",\n" +
                    "  \\"items\\": [\n" +
                    "    {\n" +
                    "      \\"type\\": \\"integer\\"\n" +
                    "    }\n" +
                    "  ]\n" +
                    "}";

var input = "[true,false,{},\"foo\"]";

var factory = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V202012);
var jSchema = factory.getSchema(schema);
var errors = jSchema.validate(new ObjectMapper().readTree(input));
System.out.println("Errors: '"+errors.stream().map(ValidationMessage::getMessage).collect(joining(", ")) +"'");

Does not fail the validation. I stepped a bit into it with the debugger and it seems the validator is happy as the schema wants an array and the input value is an array .. it doesnt seem to validate the nested type definition.

I'm using **_com.networknt.json-schema-validator  v1.0.76_**

See same issue raised in https://stackoverflow.com/questions/75063085/how-to-validate-array-item-types-with-networknt-json-schema-validator

Thanks a lot !

**Comment by stevehu** [comment]
I think 2020-12 has change items to something else and it is not supported yet.

**Comment by j-d-o** [comment]
Ok, thanks I see. With "http://json-schema.org/draft-07/schema" and "VersionFlag.V7" it start working.
It would be handy if the JsonSchemaFactory would "meta-validate" my custom schema and warn me, that I'm trying to use unsupported syntax :)

**Comment by tongyuwang** [comment]
I ran into the same issue, and switching to V201909 fixed the problem. I initially thought it was a defect but turns out to be unsupported feature.

@stevehu is there a list of supported vs unsupported features for each version of the JSON Schema specifications available somewhere?

Thanks!
