### ISSUE TITLE
How can I get the validation results in German language?

### ISSUE THREAD

**Issue by CodeSmolder** [networknt/json-schema-validator#652]
Hi,

I found out, that there is a German translation of validation messages available.

But I still get English validation messages, even if I set the locale to German.

```
Locale.setDefault(new Locale("de", "DE"));
JsonSchemaFactory factory = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V201909);
JsonSchema jsonSchema = factory.getSchema(configSchema.getInputStream());
Set<ValidationMessage> schemaValidationErrors = jsonSchema.validate(newMetadata);
```

What am I doing wrong? Does anyone have an idea?

Thanks.

**Comment by stevehu** [comment]
@CodeSmolder I cannot find any documents on how to use other languages in the [doc](https://github.com/networknt/json-schema-validator/tree/master/doc) folder. The best way to find out how to use it is the walk through the issues related to translations and the test cases. Once you find out how to use it, could you please add a document? Thanks.

**Comment by basmussen** [comment]
@CodeSmolder it works, the important thing to know is that the translation for German was added with version 1.0.67 only. For older versions there is a fallback to English. 

https://github.com/networknt/json-schema-validator/tree/1.0.67/src/main/resources 

I use it like this:

```
Locale.setDefault(Locale.GERMAN);
JsonSchemaFactory jsonFactoryInstance = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V202012);
JsonSchemaFactory schemaFactory = JsonSchemaFactory.builder(jsonFactoryInstance).build();
```
Hope this helps.

**Comment by stevehu** [comment]
@basmussen Thanks a lot for your answer. I have created a doc file based on your answer here. Please let me know if there are areas that need to be improved.

https://github.com/networknt/json-schema-validator/blob/master/doc/multiple-language.md
