### ISSUE TITLE
Document which tests are removed

### ISSUE THREAD

**Issue by Relequestual** [networknt/json-schema-validator#654]
Based on reports from users and what I can see here, it looks like you removed some tests.
Specifically, at least, `minContains` and `maxContains`.
Could you document which tests you have removed from the official test suite please?
Thanks.

If you need support or have questions on implementation, feel free to join the JSON Schema slack server.

**Comment by stevehu** [comment]
This is a good idea. I will try to create a document for this. Thanks.

**Comment by stevehu** [comment]
This can be easily identified with the following test file. Thanks @fdutton 

https://github.com/networknt/json-schema-validator/blob/master/src/test/java/com/networknt/schema/JsonSchemaTestSuiteTest.java
