### ISSUE TITLE
Incorrect work of custom message for schema validation

### ISSUE THREAD

**Issue by andreid911** [networknt/json-schema-validator#655]
When I tried to use custom message feature I found that it works incorrect in parametrized tests where I validate json few times with schema. Seems like the problem is that custom message field located in ENUM and every new field with the same type (like string, number, enum etс...) overwrites previous value of custom message. As a result it works fine for the first validation, but If we validate the next json the custom error message is not appropriate, it is from the last field with this type (for example string).
I've created some example to show how to reproduce this issue. Please let me know if it is not a bag and I use validator in wrong way.
```
public class CustomMessageBugRunner {

    private static final String schemaExampleJsonString = """
            {
                "$schema": "https://json-schema.org/draft/2020-12/schema",
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "maxLength": 8,
                        "message": {
                            "maxLength": "first_max"
                        }
                    },
                    "second": {
                        "type": "string",
                        "maxLength": 8,
                        "message": {
                            "maxLength": "second_max"
                        }
                    }
                }
            }
            """;

    private static final String exampleJson = """
            {
              "name": "Exceed_length",
              "second": "correct"
            }
            """;

    public static void main(String[] args) throws JsonProcessingException {
        ObjectMapper objectMapper = new ObjectMapper();
        JsonSchema jsonSchema = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V202012).getSchema(schemaExampleJsonString);
        JsonNode jsonNode = objectMapper.readTree(exampleJson);

        for (int i = 0; i < 3; i++) {
            Set<ValidationMessage> errors = jsonSchema.validate(jsonNode);
            System.out.println(errors);
        }

    }
}
```

Actual result is:
```
[first_max]
[second_max]
[second_max]
```

But expected result is:
```
[first_max]
[first_max]
[first_max]
```

**Comment by stevehu** [comment]
I think it is a bug. We need to clear the state when start to validate the next JSON. Do you know where the issue is in the code? Could you please submit a PR to fix it? Thanks.

**Comment by andreid911** [comment]
> I think it is a bug. We need to clear the state when start to validate the next JSON. Do you know where the issue is in the code? Could you please submit a PR to fix it? Thanks.

Hi, thank you for the answer. 
As I see the problem is that field is taken from enum ValidatorTypeCode, because enum is static in java.
I am working on it, looking for a best way to fix it. Will open PR when it is ready, next week I think.

**Comment by andreid911** [comment]
Found that this problem is already fixed in https://github.com/networknt/json-schema-validator/pull/634. But this code is not in the latest release version yet.
@stevehu do you have plans for the next release?
