### ISSUE TITLE
How validate single inner objects?

### ISSUE THREAD

**Issue by dermoritz** [networknt/json-schema-validator#657]
i have a schema specifying nested objects. I have a json of one of these nested objects.
Is there a way to validate only this nested object  against the correct part in schema (specified nested in #defs part)?

Or do i need to put this part into a separate schema to validate single objects?

**Comment by stevehu** [comment]
You can do both. Just make sure that the schema and the JSON object matched.

**Comment by dermoritz** [comment]
It is not working for me. The inner object only exists as reference in schema. if i try to validate such an object i get error that required fields of parent object are missing.

I am new to json schema, probably i have to put my object also on top level? or is there a way to tell the validator to validate against a specific part of the schema?

**Comment by stevehu** [comment]
Once you load the schema or the JSON object that needs to be validated, you can get all the different parts for your validation.

**Comment by dermoritz** [comment]
thanks for this hint, is there a sample in docs somewhere? otherwise i will find - IDE will tell i guess :-)
