### ISSUE TITLE
support customer error message for required

### ISSUE THREAD

**Issue by wangguofeng1923** [networknt/json-schema-validator#658]
is there any way to set customer error message for required keyword? like bellow
 {
	"properties":{
		"firstName":{
			"description":"The person's first name.",
			"message":{
				"type":"wrong type"
			},
			"type":"string"
		}
	},
	"type":"object",
	"required":[
		"firstName"
	],
	"message":{
		"type":"should be an object",
		"required":{
			"firstName":"first name required"
		}
	}
}

or
 {
	"properties":{
		"firstName":{
			"description":"The person's first name.",
			"message":{
				"type":"wrong type",
              "required": "first name required"
			},
			"type":"string"
		}
	},
	"type":"object",
	"required":[
		"firstName"
	],
	"message":{
		"type":"should be an object"
	}
}

**Comment by stevehu** [comment]
I don't think we need a customized error message for the required. It is always "something is required"
