### ISSUE TITLE
The SchemaPath of allOf type validation message is wrong?

### ISSUE THREAD

**Issue by htdan** [networknt/json-schema-validator#664]
Just an simple example, when validate empty json with the following schema.

`{
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "allOf": [
    {
      "required": [
        "name"
      ]
    }
  ]
}`

In the validation message returned, we have the schemaPath "allOf/required". Should it be "#/allOf/0/required".

It seems when generating validation message behind allOf, the schemaPath is always partial and starts from allOf keyword only.

**Comment by stevehu** [comment]
We might not trace the element's position in the code. Could you please debug it and submit a PR to fix it?

**Comment by htdan** [comment]
> We might not trace the element's position in the code. Could you please debug it and submit a PR to fix it?

Sure, can you give me access to the repo?

**Comment by stevehu** [comment]
@htdan You can fork this repo into your org and then submit a PR from your repo. Thanks.

**Comment by htdan** [comment]
PR created @stevehu. Please check
