### ISSUE TITLE
Add support for translating URIs before fetching the schema.

### ISSUE THREAD

**Issue by fdutton** [networknt/json-schema-validator#677]
There is already support for mapping one URI to another. However, this is only useful when one knows ahead-of-time the complete set of URIs that may be addressed.

In my organization, we id our schemas using the URL of our public schema catalog (e.g., https://schemas.acme.org/...). This catalog contains our published schemas. When we are testing changes, however, we use a schema catalog that contains unpublished schemas (e.g., https://test-schemas.acme.org/...). We need a way to translate schemas.acme.org to test-schemas.acme.org using the environment's configuration.

In my opinion, the best way to do this is to replace the Map provided by SchemaValidatorsConfig with a Function. The default implementation of this Function could simply use the Map to maintain backwards compatibility. Clients can replace that Function when needed.

**Comment by stevehu** [comment]
How would you like to replace the function? We can use Java Service Provider Interface, which doesn't require an additional dependency.

**Comment by fdutton** [comment]
Originally, I was proposing replacement of Map<String, String> with Function<URI, URI> but that did not work well when combining two sources (e.g., SchemaValidatorsConfig and JsonSchemaFactory) so I submitted a PR with a formal interface and some implementations.

**Comment by stevehu** [comment]
There is another pending PR. Once it is merged, I will release a new version. Thanks a lot for your help.
