### ISSUE TITLE
Get errors when in json has more data

### ISSUE THREAD

**Issue by jsunsoftware** [networknt/json-schema-validator#68]
I want to get error when in json has data which doesn't have in schema for example I have schema like this:
```JSON
{
  "type": "object",
  "id": "urn:jsonschema:com:xxx:xxx:Student",
  "properties": {
    "name": {
      "type": "string"
    }
  }
}
```

and json:
```JSON
{
  "name": "Smith",
  "lastName": "Smithyan"
}
```
When I give the json to validate I want to get error that the "lastName" isn't defined in json schema.

**Comment by stevehu** [comment]
@jsunsoftware Here is an example on how to do it. 

https://stackoverflow.com/questions/27224310/json-schema-validation-do-not-allow-fields-other-than-those-declared-in-schema

**Comment by jsunsoftware** [comment]
@stevehu  Thanks!
