### ISSUE TITLE
Distinguish json schema lint error from validation error

### ISSUE THREAD

**Issue by Zane-XY** [networknt/json-schema-validator#680]
Lint errors and validation errors are two kind of errors. Lint error means the schema syntax is invalid. But currently, it seems both kinds of errors are aggregated in the same Set<com.networknt.schema.ValidationMessage>, you can not distinguish them from each other.

for example, given an invalid json schema definition:

```
{
  "type": "Object", <-- notice O is uppercase here
  "$schema": "https://json-schema.org/draft/2019-09/schema",
   ...
```
There should be a way to detect this error, before validate against the input.

![image](https://user-images.githubusercontent.com/2939476/227433504-67ec6389-28e0-406b-8605-514ed7743143.png)

**Comment by stevehu** [comment]
We expect the user to provide a valid schema as the input; if you are unsure, you can use the meta schema to validate your schema before using it. If the schema is not valid, we cannot currently separate the error from the JSON object error. I am open to suggestion on how to handle it. Thanks.
