### ISSUE TITLE
Using `failFast` makes validation slower

### ISSUE THREAD

**Issue by caseycrites** [networknt/json-schema-validator#685]
We're using this library in a high volume service that needs to validate a steady stream of incoming events against schemas as quickly as possible. In searching for ways to speed things up, we came across the `failFast` config that can be set as part of the `SchemaValidatorsConfig`. We added that and ran some benchmarks locally and noticed that over 1 million iterations, half of which matched and half did not, the library consistently performed slower with `failFast` set to `true`. This seemed odd, so we made a build of our service with `failFast` set to `true` and deployed it to our staging environment where we have timer metrics around the validation step and saw that it's also slower there. I've included a chart showing the metrics I'm alluding to.

<img width="1483" alt="Screenshot 2023-03-29 at 10 46 26 AM" src="https://user-images.githubusercontent.com/152198/228624155-520127c0-1fc7-4399-82c5-e1e725678221.png">

The code we changed is simply this:
```
final SchemaValidatorsConfig config = new SchemaValidatorsConfig();
config.setFailFast(true);
return DRAFT7_JSON_SCHEMA_FACTORY.getSchema(filterString, config);
```

We are using version 1.0.62 of the library and decided to not upgrade to latest due to [this issue](https://github.com/networknt/json-schema-validator/issues/564)

**Comment by stevehu** [comment]
I will look into #564 once I have some free cycles first. Thanks a lot for sharing this info.

**Comment by stevehu** [comment]
@caseycrites The entire library is almost rewritten by @justin-tay, and I think this is no longer an issue. If this happens again, please reopen this issue. Thanks.
