### ISSUE TITLE
Return valid JSONPath (or JSONPointer) expressions for each ValidationMessage

### ISSUE THREAD

**Issue by costas80** [networknt/json-schema-validator#687]
The path returned in `ValidationMessage` results, is currently an expression that _resembles_ a [JSONPath expression](https://datatracker.ietf.org/doc/id/draft-goessner-dispatch-jsonpath-00.html). I'm saying "resembles" because there are cases where the path returned is invalid, specifically when property names include reserved characters (e.g. `.`, `[` or `]`). For example JSON content like ...
```
{
   "foo": 1,
   "b.a.r": 2
}
```
... where a schema results in an issue with property `b.a.r` will produce a `ValidationMessage` with a path value of `$.b.a.r` which is an invalid JSONPath expression. The correct one in this case would be `$["b.a.r"]`. The path generation rule for a given property can be generalised as follows:
- If the property name contains a reserved character append it to its parent path using `["PROPERTY_NAME"]`.
- If the property name does not contain a reserved character append it to parent path using `.PROPERTY_NAME`.

Once we have fully valid JSONPath expressions we can definitively use them for lookups or for transformations to e.g. JSONPointer instances (like what is being attempted in #567).

The update in the code seems rather simple. It suffices to delegate the manual string concatenations for the `at` value in each validator subclass to a general method in `AbstractJsonValidator` that will hold the relevant logic. The concern however is that the path expression of `ValidationMessage` instances is currently added in the messages' description. This means that if a user of this library was happy to have the "invalid" JSONPath present in messages, this would represent a change.

Alternatively, if we really want to play this safe, we could add a new preference in say `SchemaValidatorsConfig` to produce correct JSONPath as reported path values. Heck, this could in the future also be extended via a similar preference to produce the paths as JSONPointer expressions instead of JSONPath ones, for example:

```
SchemaValidatorsConfig config = new SchemaValidatorsConfig();
config.setPathsAsJsonPathExpressions(); // Paths will be JSONPath expressions.
config.setPathsAsJsonPointerExpressions(); // Paths will be JSONPointer expressions.
// If none of the above is set then the current approach is used.
```

I wonder however if there is any logic currently on the existing `at` values (apart from use in logging, exception messages and `ValidationMessage` paths) that could potentially break from this.
 
If you confirm and validate my above proposal I'd be happy to make a PR for this - thanks!

**Comment by costas80** [comment]
I went ahead and implemented the feature in question. Would a contributor please have a look and merge? Thanks!

**Comment by costas80** [comment]
Made an additional commit to the PR to update relevant documentation references. If any additional docs updates are needed let me know :)

**Comment by costas80** [comment]
Hi @stevehu. As a first-time contributor to this project I am not sure if there is any specific process to highlight a new PR for review (apart from creating the issue and then a PR). If there is something more to do would you please let me know? Thanks!

**Comment by stevehu** [comment]
@costas80 I am reviewing it now, but it takes some time. Stay tuned, please. Thanks.
