### ISSUE TITLE
Refactor test resources to separate JSON Schema Test Suite files from project specific files

### ISSUE THREAD

**Issue by fdutton** [networknt/json-schema-validator#692]
I propose moving the specification files from JSON Schema Test Suite to `src/test/suite`. This would provide the following benefits:
- Makes merging updates from that project into this one easier as it reduces the chance of removing or overwriting this project's files
- Makes it easier to see exactly what changed in the specification thus making it easier to see what functional changes are required to conform (e.g., `content.json` moved from `draft2019-09/optional` to `draft2019-09` and `draft2019-09/optional/zeroTerminatedFloats.json` was removed)
- Enables the opportunity to populate `src/test/suite` by linking to that project thus eliminating the need to manually merge its changes into this project (it is also possible for Maven to download and unpack a specific version of the source code)
- Enables more complicated processing of specification files. JSON Schema Test Suite has informed validators to expect specification files to appear at the root of the `tests` folder. The validators are now expected to extract `$schema` from the specification file rather than using the folder name (e.g., `tests/draft2019-09`)

This change depends on #690 being accepted.

**Comment by stevehu** [comment]
@fdutton This is a fantastic idea. Maintaining the Test Suite is time-consuming as the target changes all the time. Thanks.
