### ISSUE TITLE
Merge the latest specification files from JSON Schema Test Suite

### ISSUE THREAD

**Issue by fdutton** [networknt/json-schema-validator#693]
It appears that the last time this project synchronized the JSON Schema Test Suite specification files happened ~3.5 years ago. This project disabled many of the specification checks due to issues in that version of the test suite; presumably because of issues in the specification (e.g., `tests/draft2019-09/optional/content.json`). These issues have been resolved and successfully pass testing but only after updating `content.json` with the newest version.

This change would be easier if #692 is accepted but could be done without it. It would just be more effort to understand what actually changed. For example, the test suite is missing `tests/draft2019-09/optional/zeroTerminatedFloats.json`. Is this because `zeroTerminatedFloats.json` is specific to this project or it once existed in the test suite but no longer does. To find the answer, one must examine the test suite's commit history.

**Comment by stevehu** [comment]
With the changes in the test cases you have done, this move will allow us to see which validator has issues and get them fixed. There were three reasons that some of the test cases were commented out. 
1. specification issue
2. validator is not implemented or is incomplete for the version
3. part of the specification that is not used. i.e. https://github.com/networknt/json-schema-validator/issues/5

Let's implement all keywords from the specifications but need to prioritize the one users are concerned most. Thanks.

**Comment by fdutton** [comment]
Agreed.

I am looking for a good candidate. Do you have any suggestions?
