### ISSUE TITLE
A new test case ignores no-objects added in official test suites failed in this validator

### ISSUE THREAD

**Issue by stevehu** [networknt/json-schema-validator#7]
This is a brand new test case added in the official test suites and it failed as I am not ignoring non-objects. If foo object is required and you just pass in a number, I just don't understand why this can be valid. Need sometime to investigate why this is true before implement it. 
[
    {
        "description": "required validation",
        "schema": {
            "properties": {
                "foo": {},
                "bar": {}
            },
            "required": ["foo"]
        },
        "tests": [
            {
                "description": "ignores non-objects",
                "data": 12,
                "valid": true
            }
        ]
    }
]

**Comment by Relequestual** [comment]
Applicability rules apply here.
`requires` is only applied to objects. If the instance is not an object, that keyword is not applicable.

**Comment by fdutton** [comment]
This issue appears to have been fixed sometime in the past. The test-case passes.
