### ISSUE TITLE
$ref endpoint needs authentication

### ISSUE THREAD

**Issue by michapojo** [networknt/json-schema-validator#718]
Hi,
we are using this library for schema validation. This works very nice so far.
Now, we have a schema with a reference to another schema like this:
"$ref": "http://anyURL"

By executing the validation, the libray tries to resolve this URL, but returns a 401 status code as the endpoint needs authentication. Currently, just username and password.
Is there a way to support this?

Fyi, we are using quarkus. I already tried to implement some kind of url interceptor, but without success

Best regards

**Comment by fdutton** [comment]
Have you tried providing a custom implementation of `com.networknt.schema.uri.URIFetcher`?

**Comment by michapojo** [comment]
Yes, this was my first approach.
Like this:
`JsonSchemaFactory.builder().uriFetcher()`
This method takes a custom URIFetcher object and a list of schema names. But when executing the _validate_ function, the custom URI Fetcher doesn't gets called. 
For the second paramater - What are the names of schemas? Where do I get them from?

Thank you for supporting

**Comment by michapojo** [comment]
Ok, finally, after some debugging I found it.
As I have a complete URL, I needed to map my custom url fetcher to "http". This was a bit tricky. Would by nice to find this in some documentation :)

Now my custom url fetcher gets called.

**Comment by stevehu** [comment]
@michapojo, Could you please write a document in the doc folder on the steps to get it working? Other users will find this very valuable. Thanks.

**Comment by michapojo** [comment]
@stevehu I could document it, but I'm not allowed to create a branch at all
