### ISSUE TITLE
build JAR with OSGi support

### ISSUE THREAD

**Issue by lichtin** [networknt/json-schema-validator#72]
It'd be great to build the JAR so its MANIFEST becomes OSGi-compatible.
In case of building with Maven it's done just by adding a build plugin:
```
<plugin>
    <groupId>org.apache.felix</groupId>
    <artifactId>maven-bundle-plugin</artifactId>
    <extensions>true</extensions>
</plugin>
```
and by specifying the packaging:
```
<packaging>bundle</packaging>
```

**Comment by lichtin** [comment]
It's just a minor addition to the POM. I hope you'll see that this creates the JAR with the same contents, except for some additional headers in MANIFEST.MF. That's all to becoming an OSGi bundle.

**Comment by stevehu** [comment]
So that means I only need to release one jar to maven central and the jar file can be used as normal jar and in OSGi? Sorry, I have no ideas how OSGi works.

**Comment by lichtin** [comment]
Yes, sure. It all stays the same. The additional manifest headers are only meaningful to an OSGi container. It still is a perfectly normal JAR, so no worries.

**Comment by stevehu** [comment]
@lichtin Thanks a lot for your help. I have made the change and got the jar built locally. Need to test it before release another version.

**Comment by stevehu** [comment]
@lichtin 0.1.17 has been released. Could you please test it and let me know if it works with OSGi? Thanks.

**Comment by lichtin** [comment]
Works like a charm, thanks @stevehu
