### ISSUE TITLE
Draft 7 schemas should ignore siblings of $ref

### ISSUE THREAD

**Issue by michapojo** [networknt/json-schema-validator#723]
Hello,

I'm creating schemas like this (example):
`{
  "$schema": "http://json-schema.org/draft-07/schema",
  "definitions": {
    "node": {
      "type": "string",
      "enum": [
        "a",
        "b",
        "bcd"
      ]
    }
  },
  "type": "object",
  "properties": {
    "tree": {
      "title": "Recursive references",
      "$ref": "#/definitions/node",
      "minLength": 3
    }
  }
}`

Afterwards, I'm using this library to validate some data against this schema:
`{
  "tree": "b"
}`

According to the specification this data should be valid for the schema, whem using the meta schema V7. 
https://www.jsonschemavalidator.net/ confirms this.
But the library returns me the following validation error:
_String 'b' is less than minimum length of 3._

Could this be related to the reference of meta schema V7. The URI of the library code is using https.
When using https in the validator from above, I'm receiving the same error.

Any advices? Do you know if there is a difference between using http or https for meta schemas?

**Comment by fdutton** [comment]
@michapojo I think this is occurring because `"minLength": 3` requires that the value have at least 3 characters.

**Comment by michapojo** [comment]
@fdutton Yes, but according to specification, this should be ignored for the meta schema V7. With the meta schema 2019-09 it would be fine.
https://json-schema.org/draft/2019-09/release-notes.html
![image](https://user-images.githubusercontent.com/115477193/235119110-ebfea2fd-5a2a-4189-86f0-675f9c1f5e51.png)
