### ISSUE TITLE
Schema inside dependentSchemas not being traversed in walker

### ISSUE THREAD

**Issue by rishabh413** [networknt/json-schema-validator#724]
I want to collect all strings (with some constraints) in a json data given its json schema and for that I am using the below representative code for the example given in [json-schema documentation](https://json-schema.org/understanding-json-schema/reference/conditionals.html#dependentschemas):

```java
public final class Run {
  private static final class StringCollector implements JsonSchemaWalkListener {
    private final HashSet<String> strings = new HashSet<>();

    @Override
    public WalkFlow onWalkStart(WalkEvent walkEvent) {
      boolean isString =
          Optional.of(walkEvent.getSchemaNode())
              .map(jsonNode -> jsonNode.get("type"))
              .map(JsonNode::asText)
              .map(type -> type.equals("string"))
              .orElse(false);

      if (isString) {
        strings.add(walkEvent.getNode().asText());
      }

      return WalkFlow.CONTINUE;
    }

    @Override
    public void onWalkEnd(WalkEvent walkEvent, Set<ValidationMessage> validationMessages) {}
  }

  public static void main(String[] args) throws JsonProcessingException {
    SchemaValidatorsConfig config = new SchemaValidatorsConfig();
    StringCollector stringCollector = new StringCollector();
    config.addKeywordWalkListener(stringCollector);

    String schema =
        "{\n"
            + "  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n"
            + "  \"type\" : \"object\",\n"
            + "  \"properties\" : {\n"
            + "    \"credit_card\": {\n"
            + "      \"type\" : \"string\"\n"
            + "    }\n"
            + "  },\n"
            + "  \"dependentSchemas\": {\n"
            + "    \"credit_card\": {\n"
            + "      \"properties\": {\n"
            + "        \"billing_address\": {\n"
            + "          \"type\" : \"string\"\n"
            + "        }\n"
            + "      },\n"
            + "      \"required\": [\"billing_address\"]\n"
            + "    }\n"
            + "  }\n"
            + "}\n";
    String data =
        "{\n"
            + "  \"credit_card\" : \"my_credit_card\",\n"
            + "  \"billing_address\" : \"my_billing_address\"\n"
            + "}\n";

    JsonSchema jsonSchema = JsonSchemaFactory.getInstance(V202012).getSchema(schema, config);
    jsonSchema.walk(new ObjectMapper().readTree(data), /* shouldValidateSchema= */ false);

    System.out.println(stringCollector.strings);
  }
}
```
Output:
```
[my_credit_card]
```

The string `my_billing_address` is missing in output. This is because the walker is not going inside `dependentSchemas`. Is this a missing feature of the out of the box walker framework provided by this library? 
Or do i need to handle this case in my walker by handling `dependentSchemas` keyword?

**Comment by stevehu** [comment]
Although dependentSchemas was introduced after adding the walking feature, it should use the default walk method in BaseJsonValidator. It doesn't work as expected, but a debug might help find the root cause and fix it. Would you like to investigate it? Thanks.

**Comment by rishabh413** [comment]
Thanks for pointing me to `BaseJsonValidator`. I debugged it and its happening because of [this](https://github.com/networknt/json-schema-validator/blob/594479b734ed2640a0fa520f3a8c1168e8a6e0da/src/main/java/com/networknt/schema/BaseJsonValidator.java#L196) check where its not registering walker for `dependentSchemas` node if `shouldValidateSchema` is `false`.

The below code change in [above code](https://github.com/networknt/json-schema-validator/issues/724#issue-1681519083) fixed it:

```java
schema.walk(parseJson(dataAsString), /* shouldValidateSchema= */ true);
```

I will let this ticket open as it's an undesired behavior. I don't have free cycles right now and hence I will go ahead with this fix. Please feel free to take this up.

**Comment by rishabh413** [comment]
@stevehu 

I need some guidance. I think having `parentNode` in [WalkEvent](https://github.com/networknt/json-schema-validator/blob/a3eccdf66ddfc2e116d2b77dccdcc3212bf38413/src/main/java/com/networknt/schema/walk/WalkEvent.java#L14) would be helpful in the transformations which I am trying to develop by walkers. Here, `parenNode` is the parent of `node`. Its very similar to the relationship of `schema` and `parentSchema` which are already present in `WalkEvent`. Do you think its ok to add it in `WalkEvent`?

**Comment by stevehu** [comment]
@rishabh413 I need to become more familiar with the walking feature. @prashanthjos, could you please provide your recommendations? Thanks.

**Comment by rishabh413** [comment]
Hi @prashanthjos , PTAL. Any pointers to code or documentation would be helpful.

**Comment by rishabh413** [comment]
Thanks for the fix
