### ISSUE TITLE
Support Java Modules

### ISSUE THREAD

**Issue by aalmiray** [networknt/json-schema-validator#727]
`v2.4.4` defines an automatic module name

```
$ jarviz module name --gav com.networknt:json-schema-validator:1.0.8
subject: json-schema-validator-1.0.8.jar
name: json.schema.validator
source: filename
automatic: true
valid: true

$ jarviz module descriptor --gav com.networknt:json-schema-validator:1.0.8
subject: json-schema-validator-1.0.8.jar
name: json.schema.validator
version: 1.0.8
open: false
automatic: true
requires:
  java.base mandated
contains:
  com.networknt.schema
  com.networknt.schema.url

$ jarviz bytecode show --gav com.networknt:json-schema-validator:1.0.8
subject: json-schema-validator-1.0.8.jar
Unversioned classes. Bytecode version: 50 (Java 6) total: 72
```

I'd be great if the library supplied a full Java module descriptor. It's possible to keep bytecode baseline compatible with Java 8 while providing a full module descriptor thanks to [ModiTect](https://github.com/moditect/moditect). This will help modular projects that consume this library, specifically those that create custom Java Runtimes with `jlink`, as the latter does not support automatic modules but explicit modules. If interested I can send a PR to make it happen.

**Comment by aalmiray** [comment]
Depends on https://github.com/ethlo/itu/issues/14

**Comment by stevehu** [comment]
@aalmiray I am open to adding module support for the current Java 8 release package. FYI, @fdutton and I have discussed having two branches once we finish the validator implementations.

**Comment by aalmiray** [comment]
@stevehu Thanks! I did notice #562 before submitting this issue. Figured it was best to ask 😅 
Would you accept a PR configuring ModiTect to solve this feature?

**Comment by stevehu** [comment]
Yes. Let's do that before we have the two branches. Thanks a lot for your help.
