### ISSUE TITLE
Using subschema references in getSchema with a Uri Translated schema

### ISSUE THREAD

**Issue by jamesrgrinter** [networknt/json-schema-validator#742]
Per #625 we can use getSchema(URI) to obtain a schema with a subschema reference, and validate against that, and that works fine for a locally referenced schema (resource, file, etc).

But, if I have a 'remote' schema, and use `SchemaValidatorsConfig.addUriTranslator` to add a mapping between the remote URI and a local file or resource reference then it doesn't work unless I add an additional mapping for the subschema reference.

i.e. to successfully hit the translation mapping, requires an additional entry in the map with the subschema reference:
```
private static final String SCHEMA_USER = "http://example.com/schemas/user"; 
private static final String NEW = "#/definitions/new";

...

public void getSchemaThatFails() {
    SchemaValidatorsConfig config = new SchemaValidatorsConfig();
    config.addUriTranslator(URITranslator.map(Map.of(
      SCHEMA_USER, "file:templates/schemas/user.json"
    )));

    JsonSchemaFactory factory = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V7);
    JsonSchema schema = factory.getSchema(SCHEMA_USER + NEW, config);
}

public void getSchemaThatWorks() {
    SchemaValidatorsConfig config = new SchemaValidatorsConfig();
    config.addUriTranslator(URITranslator.map(Map.of(
      SCHEMA_USER, "file:templates/schemas/user.json",
      SCHEMA_USER + NEW, "file:templates/schemas/user.json" + NEW
    )));

    JsonSchemaFactory factory = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V7);
    JsonSchema schema = factory.getSchema(SCHEMA_USER + NEW, config);
}
```

Is this expected/desired behaviour, or should the UriTranslator look-up strip off the subschema reference before trying to find a mapping?

(I don't think it matters to the above example, but here's my test schema for context)
```
{
  "$id": "http://example.com/schemas/user",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "allOf": [{"$ref": "#/definitions/new"}],
  "properties": {
    "id": {"type": "integer", "readOnly": true},
    "username": {"readOnly": true}
  },
  "definitions": {
    "new": {
      "description": "Properties for creating a new user object",
      "type": "object",
      "properties": {
        "username": {"type": "string"},
        "name": {"type": "string"},
        "email": {"type": "string", "format": "email"}
      },
      "required": ["name", "email"]
    }
  }
}
```

**Comment by stevehu** [comment]
@jamesrgrinter Is the following doc answered your question? If not, let's complete the doc. Thanks.

https://github.com/networknt/json-schema-validator/blob/master/doc/schema-map.md

**Comment by jamesrgrinter** [comment]
> @jamesrgrinter Is the following doc answered your question? If not, let's complete the doc. Thanks.

That's what I followed to set up the mapping in the first place. Essentially, my question/issue is, should I have to add extra entries to that URI Translator mapping for subschema references, i.e.

    "http://example.com/schemas/user" -> "file:templates/schemas/user.json"
    "http://example.com/schemas/user#/definitions/new" -> "file:templates/schemas/user.json#/definitions/new"

Or should I just be able to add the first one, and the URI translation should know that the second logically follows.

**Comment by fdutton** [comment]
@jamesrgrinter Try this
```
config.addUriTranslator(original -> URI.create(original.toString().replace("http://example.com/schemas/user", "file:templates/schemas/user.json"));
```
