### ISSUE TITLE
build error on Windows environment

### ISSUE THREAD

**Issue by chenyan71** [networknt/json-schema-validator#75]
build 0.1.17 on windows environment and got error:

Tests in error:
 JsonSchemaTest.testLoadingWithId:111 » FileNotFound http://localhost:1234/self...

It looks like Undertow server wasn't started correctly to serve the schema.
The Undertow server should be up and running and listen to 1234.

**Comment by stevehu** [comment]
I don't have Windows machine to test. I guess the problem is due to the path difference between Windows and Linux. Since a lot of changes has been done since this issue was found, I am wondering if you could test it again. Thanks.

**Comment by stevehu** [comment]
@chenyan71 I guess this issue has been resolved already by one of the PRs. Could you please confirm and close the issue? Thanks.
