### ISSUE TITLE
[1.0.81] JSON Path does not handle all special characters

### ISSUE THREAD

**Issue by slisaasquatch** [networknt/json-schema-validator#750]
Here's a code example to reproduce the issue:

```java
public static void main(String[] args) throws Exception {
	final ObjectMapper mapper = new ObjectMapper();
	final SchemaValidatorsConfig schemaValidatorsConfig = new SchemaValidatorsConfig();
	schemaValidatorsConfig.setPathType(PathType.JSON_PATH);
	/*
		{
			"$schema": "https://json-schema.org/draft/2019-09/schema",
			"type": "object",
			"properties": {
				"\"": {
					"type": "boolean"
				}
			}
		}
	 */
	final JsonSchema schema = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V201909)
			.getSchema(mapper.readTree("{\n" +
					"    \"$schema\": \"https://json-schema.org/draft/2019-09/schema\",\n" +
					"    \"type\": \"object\",\n" +
					"    \"properties\": {\n" +
					"        \"\\\"\": {\n" +
					"            \"type\": \"boolean\"\n" +
					"        }\n" +
					"    }\n" +
					"}"), schemaValidatorsConfig);
	// {"\"": 1}
	final Set<ValidationMessage> validationMessages = schema.validate(mapper.readTree("{\"\\\"\": 1}"));
	for (ValidationMessage validationMessage : validationMessages) {
		// Prints $["""]
		System.out.println(validationMessage.getPath());
	}
}
```

If the field name has `"` (and potentially other special characters), the JSON Path generated is invalid.

**Comment by slisaasquatch** [comment]
Tagging the original author of the feature @costas80

**Comment by costas80** [comment]
Checking the code that generates the path expressions I see that the only special character that is not correctly handled is the double quote itself. In general field names with non-standard characters need to be wrapped in double quotes, but what was overlooked was the double quote itself that needs to be escaped.

This is a pretty simple fix. I'll correct it and add a unit test for it asap.

**Comment by slisaasquatch** [comment]
I'm not a JSON Path expert myself, but I'd assume the part between the square brackets can be any valid JSON string? If that's the case, maybe we can just take advantage of Jackson directly like this?

```java
"[" + JsonNodeFactory.instance.textNode(token) + "]"
```

**Comment by costas80** [comment]
Thanks for the suggestion @slisaasquatch. Using `JsonNodeFactory` or `TextNode` does not escape however. To do so one would need to serialise the JSON. I will go ahead with the simple replacement approach I had in mind which should be sufficient.

**Comment by costas80** [comment]
The fix is now ready to be merged. @stevehu are you the one responsible for reviewing PRs or @fdutton ?

**Comment by costas80** [comment]
By the way, when looking into the fix for this I noticed an issue in an update made recently by @fdutton . There was a method introduced to convert a Legacy or JSON Path path to a JSON Pointer to make a subsequent lookup.

Specifically in `PathType` the following was introduced:
```
    public String convertToJsonPointer(String path) {
        switch (this) {
            case JSON_POINTER: return path;
            default: return fromLegacyOrJsonPath(path);
        }
    }

    static String fromLegacyOrJsonPath(String path) {
        return path
                .replace("\"", "")
                .replace("]", "")
                .replace('[', '/')
                .replace('.', '/')
                .replace("$", "");
    }
```
That is used in `UnEvaluatedPropertiesValidator`:
```
    public Set<ValidationMessage> validate(JsonNode node, JsonNode rootNode, String at) {
       ...
        unevaluatedPaths.forEach(path -> {
            String pointer = getPathType().convertToJsonPointer(path);
            JsonNode property = rootNode.at(pointer);
            if (!schema.validate(property, rootNode, path).isEmpty()) {
                failingPaths.add(path);
            }
        });
       ...
    }
```

The `fromLegacyOrJsonPath` method of `PathType` is oversimplified and assumes that there are no characters with potentially special meaning in the property names being looked up. For example a property including `/`, `~`, `"`, `[`, `]`, `.` or `$` would end up with an invalid JSON pointer that would not throw an error but would never end up matching anything. In addition, as it stands, the default path approach is the legacy "JSON-Path-like" approach which may be invalid as JSON Path to begin with.

What are your thoughts @fdutton ?

**Comment by costas80** [comment]
As this issue was closed I created #752 about the likely issue I mentioned in the unevaluatedProperties evaluation.

**Comment by slisaasquatch** [comment]
@costas80 I just discovered another issue with the new implementation on master.

The issue is that the only character it's attempting to escape is the `'` character, while there are other characters that need to be escaped.

Here's a simple example:

```java
@Test
public void test123() throws Exception {
	final ObjectMapper mapper = new ObjectMapper();
	final SchemaValidatorsConfig schemaValidatorsConfig = new SchemaValidatorsConfig();
	schemaValidatorsConfig.setPathType(PathType.JSON_PATH);
	/*
		{
			"$schema": "https://json-schema.org/draft/2019-09/schema",
			"type": "object",
			"properties": {
				"\n": {
					"type": "boolean"
				}
			}
		}
	 */
	final JsonSchema schema = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V201909)
			.getSchema(mapper.readTree("{\n" +
					"    \"$schema\": \"https://json-schema.org/draft/2019-09/schema\",\n" +
					"    \"type\": \"object\",\n" +
					"    \"properties\": {\n" +
					"        \"\\n\": {\n" +
					"            \"type\": \"boolean\"\n" +
					"        }\n" +
					"    }\n" +
					"}"), schemaValidatorsConfig);
	// {"\n": 1}
	final Set<ValidationMessage> validationMessages = schema.validate(mapper.readTree("{\"\\n\": 1}"));
	for (ValidationMessage validationMessage : validationMessages) {
		/*
		 * Prints $['
		 * ']
		 * (with an actual new line)
		 */
		System.out.println(validationMessage.getPath());
	}
}
```

**Comment by slisaasquatch** [comment]
All I can find on what characters need to be escaped is [this page](https://www.freeformatter.com/json-escape.html) for JSON, not exactly for JSON path. If JSON path follows a similar pattern, I think it may be good enough to do something like this:

```java
s.replace("\\", "\\\\")
        .replace("\b", "\\b")
        .replace("\f", "\\f")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
        .replace("'", "\\'");
```

**Comment by costas80** [comment]
Issue fixed in #757. @stevehu can you check and merge please?

**Comment by stevehu** [comment]
Merged. Thanks for the joint effort.

**Comment by slisaasquatch** [comment]
@costas80 Thanks for the quick fix. I just checked out the new code and I think there's one lingering issue, and that's the fact that it's not escaping the `\` character. Using the same code example to demonstrate:

```java
@Test
public void test123() throws Exception {
    final ObjectMapper mapper = new ObjectMapper();
    final SchemaValidatorsConfig schemaValidatorsConfig = new SchemaValidatorsConfig();
    schemaValidatorsConfig.setPathType(PathType.JSON_PATH);
	/*
		{
			"$schema": "https://json-schema.org/draft/2019-09/schema",
			"type": "object",
			"properties": {
				"\\": {
					"type": "boolean"
				}
			}
		}
	 */
    final JsonSchema schema = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V201909)
            .getSchema(mapper.readTree("{\n" +
                    "    \"$schema\": \"https://json-schema.org/draft/2019-09/schema\",\n" +
                    "    \"type\": \"object\",\n" +
                    "    \"properties\": {\n" +
                    "        \"\\\\\": {\n" +
                    "            \"type\": \"boolean\"\n" +
                    "        }\n" +
                    "    }\n" +
                    "}"), schemaValidatorsConfig);
    // {"\\": 1}
    final Set<ValidationMessage> validationMessages = schema.validate(mapper.readTree("{\"\\\\\": 1}"));
    for (ValidationMessage validationMessage : validationMessages) {
        /*
         * Prints $['\']
         * It should be $['\\']
         */
        System.out.println(validationMessage.getPath());
    }
}
```

**Comment by costas80** [comment]
@slisaasquatch The `\` character is rather odd, and I can't see anywhere how this is really supposed to be handled. I tried out a simple test using JSON Pointer and lookup via Jackson. followed by the same using JSON Path and lookup via Jayway:
```java
// Test using JSON Pointer and lookup via Jackson
ObjectMapper mapper = new ObjectMapper();
// { "te\\st": 1 }
JsonNode rootNode = mapper.readTree("{ \"te\\\\st\": 1 }");
// Prints "1" meaning that the expected JSON Pointer is /te\st
System.out.println(rootNode.at("/te\\st"));

// Test using JSON Path and lookup via Jayway
// { "te\\st": 1 }
ReadContext ctx = JsonPath.parse("{ \"te\\\\st\": 1 }");
Integer result = ctx.read("$['te\\\\st']");
// Prints "1" meaning that the expected JSON Path is $['te\\st']
System.out.println(result);
```
So basically the `\` character is treated differently for JSON Pointer and JSON Path. In any case, given the behaviour of Jackson and Jayway I guess it is best to align with their respective approaches. I'll make a PR to adapt the handling as such.

**Comment by costas80** [comment]
Ok, looking further into this I'm convinced that Jackson has a bug on the handling of JSON Pointers... Checking [section 5](https://datatracker.ietf.org/doc/html/rfc6901#section-5) of the JSON Pointer specification, it clearly states that:
```
For example, given the JSON document

{
  "foo": ["bar", "baz"],
  "": 0,
  "a/b": 1,
  "c%d": 2,
  "e^f": 3,
  "g|h": 4,
  "i\\j": 5,
  "k\"l": 6,
  " ": 7,
  "m~n": 8
}

The following JSON strings evaluate to the accompanying values:

""           // the whole document
"/foo"       ["bar", "baz"]
"/foo/0"     "bar"
"/"          0
"/a~1b"      1
"/c%d"       2
"/e^f"       3
"/g|h"       4
"/i\\j"      5
"/k\"l"      6
"/ "         7
"/m~0n"      8
```
So basically a root property named `i\\j` would be matched using path `/i\\j`. This is not what happens though:
```java
String jsonContent = "{ \"i\\\\j\": 1 }";
System.out.println(new ObjectMapper().readTree(jsonContent).at("/i\\\\j")); // Correct path - No result
System.out.println(new ObjectMapper().readTree(jsonContent).at("/i\\j")); // Wrong path - prints 1
```
So, I'll adapt the implementation in this library to do the same escaping for JSON Path and JSON Pointer. I'll also open a bug report for Jackson to have this fixed. If the implementation in Jackson turns out to be correct we can easily adapt here.
