### ISSUE TITLE
Support for JSON Schema simplification?

### ISSUE THREAD

**Issue by jechterhoff** [networknt/json-schema-validator#770]
Hi,

Does the validator functionality include a feature that allows simplification of a given JSON Schema? With simplification, I mean merging all allOf constraints (and possibly de-referencing any schema references). I know that some other software tools exist that claim to support that kind of simplification, and that this is a non-trivial task. I am just interested to know if the networknt JSON Schema validator has something in this area.

Background: We have a schema that makes extensive use of allOf, but some (non-validator) tools which we would like to feed that schema do not support allOf.

Cheers,
Johannes

**Comment by stevehu** [comment]
@jechterhoff de-ref sub schemas is done during the schema loading, but merging allOf doesn't exist. I would suggest using some other tools to pre-process your schema before using it in the validator. Thanks.
