### ISSUE TITLE
Bootstrapping JsonSchemaFactory clarification needed

### ISSUE THREAD

**Issue by TF88641** [networknt/json-schema-validator#771]
So from the documentation there's a way to obtain a JsonSchemaFactory instance using SpecVersionDetector.detect(JsonNode), where the JsonNode is essentially the parsed Schema. Our use case is that we might obtain the URI of a schema, which could be _any_ of the spec versions at runtime. The thing is, in order to obtain the JsonNode representing the Schema, I would have to of fetched it without knowledge of the version and then (e.g. via Jackson) read in the schema document.
JsonSchemaFactory has the machinery to fetch URIs via URIFetcher/URLFetcher but these aren't accessible before obtaining an instance of the factory - which requires us to declare the Spec version. This becomes a chicken + egg problem?

Is there a way in the current framework to essentially do the equivalent of this -
```
URI someschema;   // could be any scheme, any version
InputStream is = JsonSchemaFactory.getURISchemeFetcher().fetch(someschema);  // doesn't exist
JsonNode schemaNode = objectMapper.readTree(is);
JsonSchemaFactory jsonSchemaFactory = JsonSchemaFactory.getInstance(SpecVersionDetector.detect(schemaNode);
// jsonSchemaFactory should have the spec version declared by someschema
```

**Comment by fdutton** [comment]
@TF88641 Drafts 4 through 2020-12 require that a meta-schema contain a `$schema` keyword but only suggests that a schema do so. When a schema lacks this keyword, an implementation is free to define whatever behavior it finds most reasonable. Things become more complicated with Drafts 2019-09 and 2020-12 in that the specification allows one to craft custom meta-schemas using standard and custom _vocabularies_. The specification considers each meta-schema as a separate dialect (e.g., Draft 2020-12 is a dialect as is any custom meta-schema).

Other complications:
- Is the URI dereferenceable (i.e., can i get an InputStream for this URI)? Maybe it is a URN or a scheme not supported by Java (e.g., `sftp://`).
- Does the InputStream contain JSON?
- Does the JSON represent a JSON Schema?
- Does the schema define its meta-schema?
- Is it a recognized dialect?

This list represents just a few issues we have to address when validating schemas. Currently, we assume the provided schema is valid and that the client knows which dialect to use. We are working to add support for vocabularies, which will make auto-detection better but this is unlikely to solve the problem of schemas that don't define their meta-schema.

Unfortunately, this means that you will need to handle these issues in the application code for now.

**Comment by TF88641** [comment]
OK I see the complicated nature of the context, thanks. Last question though, I wondered if this was a suitable workaround if I knew with good certainty that any schema encountered would be in a fixed list of draft specs?

```
        validatorFactory = JsonSchemaFactory.builder()
                .defaultMetaSchemaURI(new Version4().getInstance().getUri())
                .addMetaSchema(JsonMetaSchema.getV4())
                .addMetaSchema(JsonMetaSchema.getV6())
                .addMetaSchema(JsonMetaSchema.getV7())
                .addMetaSchema(JsonMetaSchema.getV201909())
                .addMetaSchema(JsonMetaSchema.getV202012())
                .build();
```

i.e., the resulting instance would be able to handle a schema that defined any of those drafts in $schema?
