### ISSUE TITLE
How to introduce a custom keyword?

### ISSUE THREAD

**Issue by htdan** [networknt/json-schema-validator#772]
Is there a way to introduce a custom keyword for validation without fork the library?

For example, a keyword indicate a date-time string is in the future. 

Thanks.

**Comment by stevehu** [comment]
It doesn't support the custom keywords at the moment. This has been discussed several times in the past, but it will involve dependency injection. The more dependencies to introduce, the more complicated for other projects to use this library. The goal is to provide a green library with minimum dependency. One thing that we can explore is the Service Provider Interface(SPI) though.

**Comment by htdan** [comment]
thank you

**Comment by htdan** [comment]
I saw this test case CustomMetaSchemaTest in the repo, it seems that one can introduce a keyword and hook into the validation process. Is it still a suggested way to extend the functionality of the library @stevehu ? Thanks

**Comment by stevehu** [comment]
Yes. There is a way to extend the validation. However, due to many changes, you must try it to confirm if this is suitable for your use case.

**Comment by htdan** [comment]
Cool, thanks
