### ISSUE TITLE
Issue with showing correct error message when referenced schema does not exist

### ISSUE THREAD

**Issue by vpylypenko2** [networknt/json-schema-validator#78]
Implementation of CustomErrorMessageType.of(String errorCode, MessageFormat messageFormat) does not pass second parameter to the class constructor

**Comment by stevehu** [comment]
@vpylypenko2 Thanks for raising this issue. I will take a look once completing the current tasks. Would you be able to submit a pull request to speed up the defect fixing process?

**Comment by tantou** [comment]
how to add custom error message?

**Comment by stevehu** [comment]
@tantou Start with the CustomErrorMessageType.java and you can see how it is used. We might just need to change the signature a little bit to introduce dynamic parameters. I don't know if two parameters are enough or not.
