### ISSUE TITLE
Custom date-time format not possible since version 1.0.82

### ISSUE THREAD

**Issue by kad-koninr1** [networknt/json-schema-validator#784]
In version 1.0.82 the following code was removed from FormatKeyword::newValidator. Making it impossible to add a custom format for date-time. 

```
format = formats.get(formatName);
// if you set custom format, override default Email/DateTime/UUID Validator
if (format != null) {
  return new FormatValidator(schemaPath, schemaNode, parentSchema, validationContext, format, type);
}
```

**Comment by josejulio** [comment]
It is part of this commit: https://github.com/networknt/json-schema-validator/commit/6382ac627bd941b33643a4c201e72e1568da73c6#diff-d768b2df893f0a8cfed7802c37b97d94caf1cfcc06cb77e0edaf25ffd26ac89eL52
