### ISSUE TITLE
Unable to Walk on schema nodes inside dependencies

### ISSUE THREAD

**Issue by kanchika-tech** [networknt/json-schema-validator#794]
I added a type Keyword listener to my schema . But it was not able to walk inside the schema fields present in dependencies keyword.
I am guessing that it is because of absence of walk() in DependenciesValidator/DependentSchemas , the walk() behaviour of DependenciesValidator/DependentSchemas should be same to that of PropertiesValidator.

**Comment by fdutton** [comment]
Please see the discussion in #724 

Closing as a duplicate
