### ISSUE TITLE
It is unclear on how readOnly and writeOnly are supported.

### ISSUE THREAD

**Issue by Lnrx** [networknt/json-schema-validator#798]
The readonly type is incorrect.

**Comment by Lnrx** [comment]
How to determine the problem of readOnly? Either by comparing the passed arguments to the previous one, or if readonly is true, as long as the corresponding passed arguments exist, an error will be reported.
Another problem is that the writeMode argument in ReadOnlyValidator is always true regardless of whether the ReadOnly argument is true or false.

**Comment by fdutton** [comment]
See this chapter of [Understanding JSON Schema](https://json-schema.org/understanding-json-schema/reference/generic.html?highlight=readonly). The relevant text is below.
 
> The boolean keywords readOnly and writeOnly are typically used in an API context. readOnly indicates that a value should not be modified. It could be used to indicate that a PUT request that changes a value would result in a 400 Bad Request response. writeOnly indicates that a value may be set, but will remain hidden. In could be used to indicate you can set a value with a PUT request, but it would not be included when retrieving that record with a GET request.

In general, _json-schema-validator_ has no knowledge of how a schema is to be used; it does not know if it is validating an API request or response so It attempts to support this additional context by providing `SchemaValidatorsConfig.setWriteMode(boolean writeMode)`. However, the current implementation is insufficient as @Lnrx discovered.

In the specification, `readOnly` and `writeOnly` are separate Boolean indicators. When present, it is possible for both to be `false`, both to be `true` or each to have a different value. It is also possible that one or both are not present in the schema. In essence, these are tristate values (i.e., true, false or missing). This gives us a 3x3 matrix of possibilities but only one is truly interesting (both are true).

When a property is annotated as `"readOnly": true` or `"writeOnly": true`, we should raise an issue if this property exists in the JSON instance. A client that naively creates a validator will receive a validation error if the property exists in the JSON instance regardless of the context. What we expect is that the client will create two validators; one for validating API requests and one for validating API responses. In this scenario, the client can specify whether to enforce the `readOnly` constraint or the `writeOnly` constraint.

Currently, we only truly support the client specifying that a property is `readOnly`. We simulate it when the client invokes `SchemaValidatorsConfig.setWriteMode(false)` but the logic is broken in that we only recognize the `readOnly` keyword so to get this behavior, the schema must contain `"readOnly": false` to get this behavior. `"readOnly": true` actually makes the property `writeOnly`. We ignore the `writeOnly` keyword. We do not consider the case where both are `true` and we incorrectly interpret `"readOnly": false` as implying that the property is `writeOnly`.
