### ISSUE TITLE
Suspected bug in PropertiesValidator.java

### ISSUE THREAD

**Issue by jakoblrosen** [networknt/json-schema-validator#817]
`if (propertyNode != null) {` at line 57 of PropertiesValidator.java evaluates to true, even when `!propertyNode.isNull()` would evaluate to false. In my case this is causing validation to fail when it should otherwise be successful.

<img width="685" alt="Screenshot 2023-06-08 at 5 32 12 PM" src="https://github.com/networknt/json-schema-validator/assets/62114964/a920627b-489b-4f91-893d-7bac681ff63d">
<img width="686" alt="Screenshot 2023-06-08 at 5 33 12 PM" src="https://github.com/networknt/json-schema-validator/assets/62114964/61d050cc-3b6a-4d69-a6da-2149f4dde926">

The following schema and json document give me the following errors:

Schema:
```
{
  "$id": "http://localhost:8000/user.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "email": {
      "type": "string"
    }
  },
  "required": [
    "email"
  ]
}
```

Request Document:
```
{
    "email": "user@mail.com"
}
```

Errors:
```
[
    {
        "type": "type",
        "code": "1029",
        "path": "$.name",
        "schemaPath": "#/properties/name/type",
        "arguments": [
            "null",
            "string"
        ],
        "details": null,
        "message": "$.name: null found, string expected"
    }
]
```

If this is intentional or if I have misconfigured anything, I would greatly appreciate an explanation. Otherwise, I believe a simple fix would be to change `(propertyNode != null)` on line 57 to `(propertyNode != null && !propertyNode.isNull())`.

**Comment by fdutton** [comment]
@jakoblrosen What version are you using? I tested this against the latest released version (1.0.83) and it behaves as expected.

**Comment by jakoblrosen** [comment]
I am as well. I think I've found the issue though. I was taking input from my RestController as a User record and then mapping to a JsonNode rather than taking in a JsonNode object and deserializing after validation. I'm not sure if that is expected behavior, but my issue is resolved.

**Comment by fdutton** [comment]
User reports that the issue is resolved.
