### ISSUE TITLE
unevaluatedProperties should not affect sub-schemas

### ISSUE THREAD

**Issue by aznan2** [networknt/json-schema-validator#826]
`unevaluatedProperties` gets its set of evaluated properties from **adjacent** `properties`, `patternProperties`, `additionalProperties` and `unevaluatedProperties` . This means that unevaluated properties from sub-schemas should not be considered. That is, given this schema:

```json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "properties": {
    "foo": {}
  },
  "unevaluatedProperties": false
}
```

the following instance should be valid:

```json
{
  "foo": {
    "bar": "baz"
  }
}
```

This is currently not the case - if `"unevaluatedProperties": false` is set at the root of a schema, then any deeply nested additional property will result in a validation error.

**Comment by manuelwaltschek** [comment]
I found this to be actually useful. I don't know if this violates the spec, but is it possible to make this configurable instead of a fixed rule?

**Comment by aznan2** [comment]
It should be easy to implement it so it reverts to the old (current) behavior if a configuration flag is set. I don't know if that is desirable though. Redefining JSON schema's validation rules feels a bit icky.

**Comment by fdutton** [comment]
@aznan2 This is the behavior defined in the specification. The JSON Schema Team provides a Test Suite for implementors to validate that their implementation conforms to the specification and this behavior is explicitly checked.

You can add `"unevaluatedProperties": true` to a nested schema if you wish to override the default behavior.

**Comment by fdutton** [comment]
_Sorry for the delay. I meant to post this yesterday but forgot to click the button._

@aznan2 I'm reading the spec again and reviewing some conversations from the JSON Schema slack channel so I need more time to complete the review of your pull-request.

Currently, I am agreeing with your position and think that my understanding of the spec is flawed. If your interpretation is correct, the pull-request will need some additional work to stop propagating _evaluated_ properties and items up the stack.

**Comment by aznan2** [comment]
@fdutton Sure, and thanks for looking into this. Do you see a test case where nested properties are still considered after the patch?
