### ISSUE TITLE
maxLength i18n  zh_CN  msg can not understand  

### ISSUE THREAD

**Issue by fei33423** [networknt/json-schema-validator#838]
https://github.com/networknt/json-schema-validator/blob/3ff32ee3fbb1c6287c6dfeda14a8bdeb965ef6c3/src/main/resources/jsv-messages.properties#L24C1-L24C49

```
maxLength = {0}: may only be {1} characters long
```
i think should use "must " similar as minLength.
should be 

```
maxLength = {0}: must be at most {1} characters long
minLength = {0}: must be at least {1} characters long
```

also other i18n should be fix.

**Comment by fdutton** [comment]
@fei33423 Are you willing to submit a pull request?

**Comment by justin-tay** [comment]
The maxLength messages were changed to the following

```
maxLength = {0}: must be at most {1} characters long
minLength = {0}: must be at least {1} characters long
```

```
maxLength = {0}: 长度不得超过 {1} 个字符
maxLength = {0}: 长度必须至少为 {1} 个字符
```

**Comment by stevehu** [comment]
@justin-tay Thanks for the confirmation. This issue is closed.
