### ISSUE TITLE
Not able to get field path when I use custom messages for array type.

### ISSUE THREAD

**Issue by Sayi-k** [networknt/json-schema-validator#839]
For other types I can add path manually to custom message, but for arrays I need its index to be printed as well.
Schema Example:
```
"requestedItems": {
  "type": "array",
  "minItems": 1,
  "items": {
    "properties": {
      "item": {
        "type": "string",
        "minLength": 1,
        "message": {
          "minLength": "Item should not be empty"
        }
      }
    }
  }
}
```

As per the above code when I do not put any value in the item field in the request I get below custom message as specified 
**"Item should not be empty"**

But I want custom message to be printed along  with its path, for ex: 
**"$.requestedItems[0].item: Item should not be empty"**

Path gets printed if I remove custom message. A dynamic message created by library would be printed along with field path as shown below. 
**"$.requestedItems[0].item: must be at least 1 characters long"**

But I want the path with custom message. I can add the path along with custom message but for array I can not pass its index. Please help

**Comment by Russell-Allen** [comment]
I have run into what I think is a related issue and I dug into the code.  I think I found the issue affecting us both...

In the [ValidationMethod](https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/ValidationMessage.java) class, the builder's build method is as follows:
```Java
        public ValidationMessage build() {
            ValidationMessage msg = new ValidationMessage();
            msg.setType(type);
            msg.setCode(code);
            msg.setPath(path);
            msg.setSchemaPath(schemaPath);
            msg.setArguments(arguments);
            msg.setDetails(details);

            if (format != null) {
                String[] objs = new String[(arguments == null ? 0 : arguments.length) + 1];
                objs[0] = path;
                if (arguments != null) {
                    for (int i = 1; i < objs.length; i++) {
                        objs[i] = arguments[i - 1];
                    }
                }
                if(StringUtils.isNotBlank(customMessage)) {
                    msg.setMessage(customMessage);
                } else {
                    msg.setMessage(format.format(objs));
                }

            }

            return msg;
        }
```
Note how the `customMessage` handling is inside of the `if (format != null)` block.  That's what bit us; we want to set a custom message w/o a `format`, which doesn't work.  I had to add a bogus format just to get the builder to enter this block of code and apply our custom message.

In @Sayi-k use case, it seems that the `if(StringUtils.isNotBlank(customMessage))` needs to support both a format and custom message, which the current code doesn't do ... that is, it assumes that the custom message overrides any format setting.
