### ISSUE TITLE
Make yaml dependency optional

### ISSUE THREAD

**Issue by alturkovic** [networknt/json-schema-validator#840]
I tried to parse a json-schema like: `JsonSchemaFactory.getInstance(version).getSchema(schema)` That produces an exception if you do not have `jackson-dataformat-yaml` dependency even though I do not want to use YAML because the internal builder (`com.networknt.schema.JsonSchemaFactory.Builder`) uses an instance of `YamlMapper` upon construction.

This should be revised to be able to use the library without the dependency.

**Comment by fdutton** [comment]
@alturkovic @stevehu YAML support was added 2023-03-04 (https://github.com/networknt/json-schema-validator/pull/670/commits/08158712a1bac13bccc4fb3f50adba21024dd8b8) and published in version 1.0.78.

While it would be simple to make the dependency on `jackson-dataformat-yaml` optional, it would break any client that started using this feature after its introduction. These clients will now be required to explicitly declare a dependency on `jackson-dataformat-yaml` when they previously relied on Maven's transitive dependency resolution.

Should we add this change to 1.1.x or should we make the change now, provide migration instructions and assume the impact will be small?

**Comment by stevehu** [comment]
The jackson-dataformat-yaml is a dependency in the pom.xml and would be included in your target application as a transitive dependency. How it would be missing? If possible, I don't think making this an optional dependency.

**Comment by alturkovic** [comment]
What I meant was, I tried excluding the `jackson-dataformat-yaml` dependency when importing this library using maven since I am not interested in the yaml format at all. I hoped that it would be possible to exclude it for users who are only interested in JSON format.

**Comment by stevehu** [comment]
It is not possible as partial code depends on it during runtime.
