### ISSUE TITLE
Custom walker

### ISSUE THREAD

**Issue by alturkovic** [networknt/json-schema-validator#841]
I am a bit confused by the walk functionality and how to implement it...

I want to walk the following schema to detect which properties have non-standard `faker` field:
```json
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "faker": "name.findName"
    },
    "email": {
      "type": "string"
    }
  }
}
```

How would I implement a `JsonSchemaWalker` to detect such fields? 

For the payload below, I would like to pass the value of the `name` from the input object together with my custom `faker` field value. I would like to call something like `faker.fake(input, jsonPointerToName, "name.findName")`. 

```json
{
  "name": "John Doe",
  "email": "john.doe@gmail.com"
}
```

This seems similar to "Applying defaults" functionality already present in the library, but instead of applying defaults, I would like to pass the current value of the field, where it is located at (so I can replace it), and the value of the `faker` field so I know how to generate its replacement.

**Comment by fdutton** [comment]
@alturkovic This project focuses on validation and is not really suitable for transformations. You may be able to achieve your goal by using walkers, listeners and collectors but I suspect the solution will be quite complicated as you would have to deal with transitions across objects, arrays, properties, items and other schemas. For example, consider this simple refactor of your schema. Your solution would have to take these types of constructs into consideration. I recommend looking for another solution before pursuing this one.
```
{
  "type": "object",
  "properties": {
    "name": { "$ref": "#/$defs/Name" },
    "email": { "type": "string" }
  },
  "$defs": {
    "Name": {
      "type": "string",
      "faker": "name.findName"
    }
  }
}
```

You can find an examples of how to use `JsonSchemaWalker`, `JsonSchemaWalkListener` and `Collector` in several unit-tests.
