### ISSUE TITLE
Enumeration, Const (Arrays and Objects)

### ISSUE THREAD

**Issue by h3IIf1r3** [networknt/json-schema-validator#843]
Schema:

val jsonSchemaMockUser = """{
    "type": "object",
    "properties": {
        "name": {
            "enum": ["hello world", [1337]]
        },
        "age": {
            "type": "integer",
            "minimum": 0
        },
        "email": {
            "type": "string",
            "format": "email"
        }
    },
    "required": ["name", "age", "email"]
}
"""

Payload:

val jsonSchemaPayloadMockUserValid = """{
    "name": [1337],
    "age": 1337,
    "email": "john.doe@example.com"
}
"""

Issue:

Once you use Arrays or Objects in enum or in const, the arguments are broken.
The error message will result in a blank at the place of the array or the object.

The JSON schema implementation is not fulfilled cause the above schema is a valid schema. 
Also the provided Payload is valid.

What works is to stringify the array in both cases so in the payload and also in the Schema. 
But this would be not a correct implementation. 
Both cases should be supported.

Arrays are arrays not strings, also objects are objects and not strings. We would never stringify every nested object. 
We would only stringify the full payload to be able to parse it from the backend.

In my opinion this is a critical bug and needs high priority.

**Comment by fdutton** [comment]
@h3IIf1r3 Which draft version are you using?
