### ISSUE TITLE
I18N Custom Locale or Can we support more languages (i.e spanish, Japanese, Korean )

### ISSUE THREAD

**Issue by channaveer1** [networknt/json-schema-validator#844]
Hi Team, 

I want to support more languages in i18N as ResourceBundle has few "jsv-messages", Please let me know any possibility of overriding or how to add more languages. or any chances of contributing from our end.

Thanks
Channaveer patil
yakshya10@gmail.com

**Comment by stevehu** [comment]
You can submit PRs to add more translations. Most team members are English speakers, and it is hard for us to help.

**Comment by channaveer1** [comment]
@stevehu you want me to give translated messages in other languages? so that can be added to ResourceBundles

**Comment by stevehu** [comment]
Please submit a PR with your resource bundles. Thanks.

**Comment by channaveer1** [comment]
Okay i will raise soon.

**Comment by channaveer1** [comment]
Hi @stevehu i need permission so that  i can raise PR to json-schema-validator, please find the error in below image and suggest what to do next. or provide the access to contribute.  

![image](https://github.com/networknt/json-schema-validator/assets/16414370/9eaeb395-1b3e-47df-a7c8-f6ed3d6a135c)

**Comment by costas80** [comment]
Hi @channaveer1 , note that you can also supply your own resource bundle as part of the validation's configuration (see the docs via the README page). Of course if you do this you need to make sure your bundle aligns in terms of keys with the default one, but at least like that you have full flexibility to e.g. override messages or support other locales.

**Comment by stevehu** [comment]
More locales are supported in the latest version. If anyone still has specific issues, please open a new issue. Thanks.
