### ISSUE TITLE
ResourceBundle - with additional languages support

### ISSUE THREAD

**Issue by channaveer1** [networknt/json-schema-validator#847]
[jsv-messages.zip](https://github.com/networknt/json-schema-validator/files/12322519/jsv-messages.zip)

Hi Team, 

Please check the attached zip file with new additional languages added. review and merge its needed for us

**Comment by stevehu** [comment]
Please check your email, I have granted access to you. Could you please submit a PR so others to review it? Thanks.

**Comment by channaveer1** [comment]
Hi @stevehu.

I was on vacation last week. link is expired can you please resend it.

 
![image](https://github.com/networknt/json-schema-validator/assets/16414370/b806433e-169a-4cae-821a-8e1689d4a314)

regards
channaveer

**Comment by channaveer1** [comment]
@stevehu can you please resend the link to permit to raise PR

**Comment by stevehu** [comment]
Resent. Thanks.

**Comment by channaveer1** [comment]
okay let me check

**Comment by channaveer1** [comment]
I have raised the PR, Below is the link for the PR for master branch thank you.

https://github.com/networknt/json-schema-validator/pull/852

**Comment by channaveer1** [comment]
https://github.com/networknt/json-schema-validator/pull/852

Please check and update me the status
