### ISSUE TITLE
maxLength validation behaviour with oneOf

### ISSUE THREAD

**Issue by theseeker58** [networknt/json-schema-validator#850]
I have a json schema like this:

```
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "title" : "Other Identification",
  "properties": {
    "identification": { "$ref" : "#/defs/Max35Text" },
    "issuer": { "$ref" : "#/defs/Max35Text" }
  },
  "required": [ "identification" ],
    "oneOf" : [
      {
        "type" : "object",
        "properties" : {
          "schemeNameCode" : { "$ref" : "#/defs/AccountIdentificationTypeCode" }
        },
        "required" : [ "schemeNameCode" ]
      }, 
      {
        "type" : "object",
        "properties" : {
            "schemeNameProprietary" : { "$ref" : "#/defs/Max35Text" }
        },
        "required" :[ "schemeNameProprietary" ]
      }
    ],
  "defs": {
    "Max35Text": {
      "type": "string",
      "minLength" : 1,
      "maxLength": 35
    },
    "AccountIdentificationTypeCode": {
      "type": "string",
      "enum": [ "BBAN", "BIC", "BICFI" ]
    }
  }
}
```

When I validate this json object against the schema

```
  {
    "identification" : "1",
    "schemeNameProprietary" : "AAAAAAAAA1AAAAAAAAA2AAAAAAAAA3AAAA5A",
    "issuer" : "ABI"  
  }
```

I get the following 3 errors:

```
$.schemeNameCode: null found, string expected
$.schemeNameCode: does not have a value in the enumeration [BBAN, BIC, BICFI]
$.schemeNameProprietary: may only be 35 characters long
```

while I expect to receive just the last one that actually breaks the maxLength restriction. The first 2 relate to a different sub-schema that shouldn't be present, according to the oneOf keyword.

Is it a bug or am I missing something in the validator configuration? Or even is there something wrong with the schema?

**Comment by theseeker58** [comment]
I managed to figure out that seemingly weird behavior. I am using Jackson ObjectMapper to convert beans to JsonNode before validate them.
I forgot to annotate beans with @JsonInclude(Include.NON_NULL), so properties were actually present even if absent in the source json. Adding that annotation did the trick!

**Comment by stevehu** [comment]
@theseeker58 Thanks for the confirmation. I am closing this issue.
