### ISSUE TITLE
Loading a json schema from classpath. Fail to resolve $ref

### ISSUE THREAD

**Issue by avishaybp81** [networknt/json-schema-validator#854]
I load a schema from the classpath.

    private JsonSchema getJsonSchemaFromClasspath(String name) {
        JsonSchemaFactory factory = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V7);
        InputStream is = Thread.currentThread().getContextClassLoader()
                .getResourceAsStream(name);
        return factory.getSchema(is);
    }

If there is a $ref in the schema that looks like the below

    "metadata": {
      "$ref": "request_metadata.json"
    }

I fail to load the schema with the error below.
Caused by: com.networknt.schema.JsonSchemaException: #/properties/metadata/$ref: Reference request_metadata.json cannot be resolved

any idea how to solve it?

**Comment by takanuva15** [comment]
Hi, I am able to reference other schema files in my resources using the following notation:
```json
"key-to-validate-in-other-schema": {
  "$ref": "classpath:///resources/schemas/model/content-schema.yml"
}
```
Assuming your schema is in `src/test/resources/request_metadata.json`, you might be able to just do this for the ref: `classpath:///request_metadata.json`

Please let me know if that works for you
