### ISSUE TITLE
When can we use #847 issue which is merged recently

### ISSUE THREAD

**Issue by channaveer1** [networknt/json-schema-validator#856]
Hi Team,

Additional language support PR(#847) is merged i hope, how to use now any specific version you are providing or we have to wait for the next release.

Regards
channaveera

**Comment by stevehu** [comment]
I can plan a new release if someone is waiting for this. Thanks @channaveer1

**Comment by channaveer1** [comment]
@stevehu Yes we are actually waiting for it. please plan. we would like to uptake ASAP

**Comment by channaveer1** [comment]
@stevehu Please update me the timeline when can we expect.

**Comment by stevehu** [comment]
https://github.com/networknt/json-schema-validator/releases/tag/1.0.87

**Comment by channaveer1** [comment]
Thank you @stevehu
