### ISSUE TITLE
JsonSchemaFactory uriSchemaCache

### ISSUE THREAD

**Issue by ecfree** [networknt/json-schema-validator#860]
this.uriSchemaCache  Unable to refresh  ，also JsonSchemaFactory no extends,When json schema changes occur；
only uri change，But at this point, there may be memory issues

**Comment by stevehu** [comment]
@ecfree could you please elaborate a little bit more about the issue? Are you saying the remote-referenced schema is changed but the working schema is not updated? or event you restart the application, it won't update? Thanks.

**Comment by jkosternl** [comment]
Let's close this issue @stevehu? It contains too less info and is > 1 year old.
