### ISSUE TITLE
readOnly property validation

### ISSUE THREAD

**Issue by palwe-prafulla** [networknt/json-schema-validator#865]
Hi,
I am using schema validator version 1.0.57 and realised that schema validation for readOnly doesnt work or not implemented ion this version.
I am using json schema with few properties marked as "readOnly" : true but with json payload which has these properties validated against schema doesnt return any errors.
I saw few issues closed related to readOnly validator.

Wanted to check what version has readOnly validator and if its supported how it works with any context of the json payload?

e.g. if a simple validation of json payload against json schema with readOnly properties, how would validator know if this is post/put request payload vs if its response payload to do any sort of validation on these proprties?

Is there any documentation on how to validate this based on some context to be passed for validation indicating if its post/put (create/update) vs response etc essentially indicating in either json schema about this or while calliing validate api?

**Comment by stevehu** [comment]
I would recommend upgrading to 1.4.x. Thanks.
