### ISSUE TITLE
Please revert fix from #815 (pattern validation)

### ISSUE THREAD

**Issue by kool79** [networknt/json-schema-validator#872]
Please revert fix made in scope of #815.
This fix was deployed based on incorrect assumption that java works incorrectly with regexp.
But actually issue is not in java. Issue (reported in #814) was caused by incorrect regexp which author uses us json schema.

STR:
GIVEN:
user (in schema) defines regexp as:   `^red|banana$`   (starts with 'red' OR ends with 'banana')
to pass any strings like: "red", "banana", "red apple",  "green banana", "red oval apple"

But the #815 fix will will change regexp to `^(red|banana)$` which will pass ONLY "red" or "banana"

For more details please see my comment to the code
https://github.com/networknt/json-schema-validator/pull/815/files#diff-776968543c85221a4907857a99fb117ab32872c5f0c020a717c11fe8162ef310R12-R24

**Comment by kool79** [comment]
Alternative tool for visualization: https://regexper.com/#%5Ered%7Cbanana%24
![scr_2023_10_11T15_39_37](https://github.com/networknt/json-schema-validator/assets/4625317/b16ad81a-ceb5-43fb-bdfd-4424a6eccbcb)
![scr_2023_10_11T15_39_56](https://github.com/networknt/json-schema-validator/assets/4625317/391e82ad-b050-48f7-b775-64d9ff09ce56)

**Comment by stevehu** [comment]
@fdutton What do you think? Thanks.

**Comment by Stephan202** [comment]
I started looking into this, and the topic is quite a rabbit hole, both in terms of regex matching behavior and invalidate test cases. I tried my best at cleaning things up in #888. @kool79 @fdutton reviews very welcome!
