### ISSUE TITLE
Please made schemaPath in ValidationMessage refer to full path for complex schemas with 2+ files

### ISSUE THREAD

**Issue by kool79** [networknt/json-schema-validator#873]
**GIVEN:**
1. the 'schema.json' which is used as json schema to validate my data.
```
{ "type":"object",
  "properties": {
     "myProperty": {"$ref": "types.json#/$defs/my-type"}
   }
}    
```
2. another file "types.json" which contain types definitions, used by prev. file
```
{"$defs":   {  "my-type": { "type": "object", "required": ["xxx"]}}}
```
**WHEN** I verify my json data (below) with the schema file 'schema.json'
```
 {"myProperty": {}}   // without xxx inside 'myProperty'
```

**THEN**  I have the next ValidationMessage:
```
{ValidationMessage@11667}
 type = "required"
 code = "1028"
 path = "$"
 schemaPath = "#/$defs/my-type/required"
 arguments = ["xxx"]
 details = null
 message = "$.myProperty.xxx: is missing but it is required"
 ```
 The  schemaPath in this message contains details only about definition from 'types.json' and does not contain any information about original context from schema.json.
 
 **Expected** schemaPath is something like::
`schemaPath = "#/properties/myProperty/$ref/types.json#$defs/my-type/required"`
or to have schemaPath as an ordered list (array): 
```
[#/properties/myProperty/$ref,
types.json#$defs/my-type/required]
```

**Comment by justin-tay** [comment]
As at 1.2.0 the validation message contains both the evaluation path and schema location.

https://github.com/networknt/json-schema-validator/blob/f3825f3881d6247e7328c685232e484a9b5f8b5e/src/main/java/com/networknt/schema/ValidationMessage.java#L77-L98
