### ISSUE TITLE
UnevaluatedProperties specified spec support level is incorrect

### ISSUE THREAD

**Issue by fvanham-coveo** [networknt/json-schema-validator#885]
If I understand the json schema spec correctly `unevaluatedProperties` was only added to the 2019-09 spec. The validator [supports it as of V6](https://github.com/networknt/json-schema-validator/blob/f03a30607c86de7c563ff110650cbcf82d0c65ad/src/main/java/com/networknt/schema/ValidatorTypeCode.java#L103C29-L103C29). Is there a specific reason it was added to the V6 and above spec level?

**Comment by justin-tay** [comment]
This has been fixed in 1.2.0

https://github.com/networknt/json-schema-validator/blob/f3825f3881d6247e7328c685232e484a9b5f8b5e/src/main/java/com/networknt/schema/ValidatorTypeCode.java#L108
