### ISSUE TITLE
Support other JSON libraries

### ISSUE THREAD

**Issue by priand** [networknt/json-schema-validator#9]
Yes, JSON in Java is a mess that is not going to be fixed in Java 9. As such, projects are using different libraries.
A common pattern to workaround this is to use a JsonFactory object that exposes all the needed methods and delegate to the actual implementation (Jackson, org.json, ...). It does not add significant performance overhead while making the code portable across libraries.
An example is provided here: [https://github.com/jayway/JsonPath/blob/master/json-path/src/main/java/com/jayway/jsonpath/spi/json/JsonProvider.java](https://github.com/jayway/JsonPath/blob/master/json-path/src/main/java/com/jayway/jsonpath/spi/json/JsonProvider.java)
It would be great to have this library follow this pattern. We are using our own JSON library, so our only choice is to fork the code and update it. Now, instead of doing that our own way, I'll be happy to implement the pattern above and contribute it back, if you wish to accept it.

**Comment by stevehu** [comment]
@priand I think that is a good idea and I am using JsonPath in my light-java framework. It is possible to make Jackson the default library as it is the most popular? Thanks.

**Comment by stevehu** [comment]
It looks like Jackson is getting more popular these days and the need to support other parser is not that urgent anymore. Closing it.
