### ISSUE TITLE
Custom error message for missing field

### ISSUE THREAD

**Issue by Tomtouta** [networknt/json-schema-validator#903]
Hello,

I discover recently the way to customize error message using this feature : https://github.com/networknt/json-schema-validator/pull/440

Nevertheless, I don't find a way to define error message in case of missing field in a json message 
For example, if a json schema expect to have an id but the json sent by a user does not contain this id, I want to have a specific error message saying something like "JSON schema not respected, missing id field".
How can this be done ?

Regards,

Tom

**Comment by fvanham-coveo** [comment]
This request with a similar ask was open-end a while back: https://github.com/networknt/json-schema-validator/issues/803
