### ISSUE TITLE
Question around `JsonSchema.getValidators()` getting marked private

### ISSUE THREAD

**Issue by awoodbury** [networknt/json-schema-validator#909]
With version `1.0.82`, `JsonSchema.getValidators()` was changed from public to private.

Curious if this is a design decision, as I was using it to poke at some of the included validators to do some gathering around the `JsonSchema` created after ingesting a schema file.

**Comment by justin-tay** [comment]
Related issue
- https://github.com/networknt/json-schema-validator/issues/269

**Comment by justin-tay** [comment]
This has been changed in 1.2.0 to be `public`.

https://github.com/networknt/json-schema-validator/blob/f3825f3881d6247e7328c685232e484a9b5f8b5e/src/main/java/com/networknt/schema/JsonSchema.java#L693
