### ISSUE TITLE
Using $ref with Relative Path

### ISSUE THREAD

**Issue by akuzin1** [networknt/json-schema-validator#920]
I am attempting to use `$ref` as part of a schema, in order to reference a repetitive schema definition in a separate file within the same directory. 
However, after trying multiple path variations I still continue to receive a `com.networknt.schema.JsonSchemaException: java.io.IOException` stating that the "Resource common-definitions.json not found in classpath"

Main Schema
```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "required" : ["DriverProperties"],
    "properties": {
        "DriverProperties": {
            "type": "object",
            "properties": {
                "CommonProperties": {
                    "$ref": "common-definitions.json#/definitions/DriverProperties"
                }
            },
            "required": ["CommonProperties"]
            "additionalProperties": false
        }
    },
    "additionalProperties": false
}
```

common-defintions.json:
```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "additionalProperties": false,
    "definitions": {
        "DriverProperties": {
            "type": "object",
            "properties": {
                "field1": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 512
                },
                "field2": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 512
                }
            },
            "required": ["field1"],
            "additionalProperties": false
        }
    }
}
```

Whenever I input the absolute path, referencing the external definition works. However, I want this to work on any machine, so I want to define the classpath relatively. 
Any recommendations would be greatly appreciated. 
Thank you.

**Comment by SudBisht** [comment]
have you tried this

`"properties": {
                "CommonProperties": {
                    "$ref": "classpath:///common-definitions.json#/definitions/DriverProperties"
                }
            }`

**Comment by Tjlastnumber** [comment]
try

```java
factory.getSchema(uri);
```

Do not use
```java
facotry.getSchema(string);
```

This could be a bug

**Comment by akuzin1** [comment]
Where should I try this?

**Comment by SudBisht** [comment]
tried this and working fine for me
```
Schema
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required" : ["DriverProperties"],
  "properties": {
    "DriverProperties": {
      "type": "object",
      "properties": {
        "CommonProperties": {
          "$ref": "classpath:///schema/common-definitions.json#/definitions/DriverProperties"
        }
      },
      "required": ["CommonProperties"],
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}


Test
 @Test
  public void validInput_test() throws IOException {

    JsonSchemaFactory factory = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V6);
    JsonSchema jsonSchema = factory.getSchema(readFile("schema/def.schema.json"));
    JsonNode jsonNode = mapper.readTree(IOUtils.toString(
        Objects.requireNonNull(this.getClass().getClassLoader().getResourceAsStream("schema/def.example.1.json")),
        StandardCharsets.UTF_8.name()));

    Set<ValidationMessage> errors = jsonSchema.validate(jsonNode);
    assertThat(errors).isEmpty();
  }
    
Input
{
  "DriverProperties": {
    "CommonProperties": {
      "field2": "abc-def-xyz"
    }
  }
}

**Comment by akuzin1** [comment]
What does `readFile` do? Does it return a URI or an InputStream?
I am using version 1.0.83, would that possibly affect the behavior I'm experiencing?
What is the file structure of the example?

**Comment by SudBisht** [comment]
> What does `readFile` do? Does it return a URI or an InputStream? I am using version 1.0.83, would that possibly affect the behavior I'm experiencing? What is the file structure of the example?

updated the above code, 
`readFile` was returning String
version : `1.1.0`
file structure: `src/test/resources/schema`

**Comment by akuzin1** [comment]
Hi, @macohen! We were waiting for the implementation of shard partitioning, which would allow to parallelize the fetching of data with the JDBC driver. Currently the connector implements a single partition solution, which resulted in performance regression compared to current connector version. 
I had opened an feature request and was working with the OpenSearch team to track the item, however, due to shifting priorities the item got backlogged.
