### ISSUE TITLE
different messages specified for different properties does not work

### ISSUE THREAD

**Issue by manbusky** [networknt/json-schema-validator#924]
https://github.com/networknt/json-schema-validator/blob/master/doc/cust-msg.md

different messages specified for different properties does not work.

At 
Example 3

I test like this

$.foo：is missing but it is required
$.bar：is missing but it is required

**Comment by justin-tay** [comment]
What version are you using? This was only recently introduced in 1.2.0.

The relevant test below is passing.

https://github.com/networknt/json-schema-validator/blob/747b47fb2758589d86b29dbfce9c84accca2a51a/src/test/resources/schema/customMessageTests/custom-message-tests.json#L103-L156

**Comment by manbusky** [comment]
so kind of you, thanks!

**Comment by manbusky** [comment]
> What version are you using? This was only recently introduced in 1.2.0.
> 
> The relevant test below is passing.
> 
> https://github.com/networknt/json-schema-validator/blob/747b47fb2758589d86b29dbfce9c84accca2a51a/src/test/resources/schema/customMessageTests/custom-message-tests.json#L103-L156


so kind of you, thanks!
