### ISSUE TITLE
Question about how to refactor my code post Path refactor

### ISSUE THREAD

**Issue by mikebell90** [networknt/json-schema-validator#932]
After the large refactor of paths by @justin-tay , being fairly neophytish in my understanding of JsonSchema and many of the objects therein, my code broke. Basically I used `validationMessage.getPath()` in two places

1. An informational message. There I suspect the normal `toString` of the new path object will be fine
2. I adapted a helpful post by one of the users of this library earlier to determine the line at which the violation caused in the original YAML. The code that broke was

```
JsonNode findJsonNode(ValidationMessage msg, JsonNode rootNode) {
        // Construct the JSONPointer.
        JsonPointer pathPtr = JsonPointer.valueOf(msg.getPath());
        // Now see if we can find the node.
        return rootNode.at(pathPtr);
    }
LocationDetails getLocationDetails(ValidationMessage msg, JsonNode rootNode) {
        LocationDetails retval = null;
        JsonNode node = findJsonNode(msg, rootNode);
        if (node instanceof LocationProvider) {
            retval = ((LocationProvider) node).getLocationDetails();
        }
        return retval == null ? LocationDetails.EMPTY : retval;
    }
```
The code breaks because JsonPointer requires a string here. I've given additional context here, and can provide more

I'm not sure how to adjust this, and would appreciate assistance

**Comment by justin-tay** [comment]
You can try the following.

```java
JsonNode findJsonNode(ValidationMessage msg, JsonNode rootNode) {
    // Construct the JSONPointer.
    JsonPointer pathPtr = JsonPointer.valueOf(msg.getSchemaLocation().getFragment().toString());
    // Now see if we can find the node.
    return rootNode.at(pathPtr);
}
```

**Comment by mikebell90** [comment]
Thanks I’ll dig deeper. This is very helpful

**Comment by mikebell90** [comment]
That did the trick thanks
