### ISSUE TITLE
Since 1.3.0: URIFactory is gone. Any migration guide? 

### ISSUE THREAD

**Issue by flozano** [networknt/json-schema-validator#948]
It looks like a major version should have been used, this seems like a major change to me. 

Is there any guide about how to proceed to upgrade?

**Comment by justin-tay** [comment]
The following are removed and replaced by `SchemaLoader` and `SchemaMapper`.
* `URIFactory` - No replacement. The resolve logic is in `AbsoluteIRI`.
* `URISchemeFactory` - No replacement as `URIFactory` isn't required anymore.
* `URISchemeFetcher` - No replacement. The `SchemaLoaders` are iterated and called.
* `URITranslator` - Replaced by `SchemaMapper`.
* `URLFactory` - No replacement as `URIFactory` isn't required anymore.
* `URLFetcher` - Replaced by `UriSchemaLoader`.
* `URNURIFactory` - No replacement as `URIFactory` isn't required anymore.

You can also see [Customizing schema retrieval](https://github.com/networknt/json-schema-validator/blob/master/doc/schema-retrieval.md).
