### ISSUE TITLE
FailFast Property Does Not Throw JsonSchemaException for Validation Errors in v1.3.1

### ISSUE THREAD

**Issue by OgyDev** [networknt/json-schema-validator#960]
After upgrading to version 1.3.1, a bug has been identified where the **failFast** property fails to throw a JsonSchemaException when validation errors are discovered. It's important to note that this issue did not occur in version 1.3.0

**Comment by justin-tay** [comment]
Sorry, I think I missed this out as a breaking change. Setting `failFast` now just returns normally as a validation message.

**Comment by OgyDev** [comment]
Thanks, @justin-tay 🙂
So, is this the expected behavior for **failFast** from now on?

**Comment by justin-tay** [comment]
Yes. This was partially done to distinguish the fail fast result from true exceptions such as when references could not be resolved. Sorry for the inconvenience.
