### ISSUE TITLE
ethlo as an optional dependency?

### ISSUE THREAD

**Issue by b-wils** [networknt/json-schema-validator#973]
Is it possible to make ethlo an optional dependency? Similar to how YAML parsing is optional as well. I suspect this may already work the same way (throws an exception), but haven't experimented yet. If that is the case, it would be just updating the docs to reflect this.

I'm trying to minimize the number of third party dependencies needed to use this library. We don't need date/time validation for our use case.

**Comment by lscoughlin** [comment]
Can you make it an optional dependency because they can't get they're modules right?
