### ISSUE TITLE
Handle Jackson Databind's 'MissingNode' null object better

### ISSUE THREAD

**Issue by adityachatterjee42** [networknt/json-schema-validator#976]
Jackson Databind uses com.fasterxml.jackson.databind.node.MissingNode as a 'null object'

Supplying the MissingNode singleton to JsonSchema.validate(...) leads to the following validation error message:
```$: unknown found, {} expected```

I suggest we explicitly handle MissingNode and return a more descriptive error message, or fail in a different way.

**Comment by justin-tay** [comment]
Can you provide the example and input data used? Are you sure it is MissingNode and not NullNode? I don't really see any issue with the message.

**Comment by stevehu** [comment]
Closing the issue as there is no action.
