### ISSUE TITLE
Are there plans to support custom vocabularies?

### ISSUE THREAD

**Issue by Kaaviyan** [networknt/json-schema-validator#977]
Currently, the vocabulary set is limited to https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/Vocabulary.java#L30

Are there plans to support custom vocabularies that consumers can define?

**Comment by justin-tay** [comment]
There are no plans to do so as typically defining a custom meta schema is sufficient.

**Comment by justin-tay** [comment]
This will likely be implemented in the next minor version as it will likely involve some breaking changes to people defining custom meta schemas.
