### ISSUE TITLE
How to set the language type of networknt exception information

### ISSUE THREAD

**Issue by Dloadinghao** [networknt/json-schema-validator#982]
Does the networknt have a built-in method to modify the language type of exception information  For example, I would like the language type of exception information to be unified in English

**Comment by justin-tay** [comment]
If you are referring to the validation messages, by default it will use the system locale. 

You can either set the system locale, via `Locale.setDefault` or configure the `SchemaValidatorsConfig` with `Locale.ENGLISH`.

**Comment by Dloadinghao** [comment]
> If you are referring to the validation messages, by default it will use the system locale.
> 
> You can either set the system locale, via `Locale.setDefault` or configure the `SchemaValidatorsConfig` with `Locale.ENGLISH`.

Thank you for your reply. My problem has been solved
