### ISSUE TITLE
JsonNode.canConvertToExactIntegral NoSuchMethodError with current jackson-databind 2.16.2

### ISSUE THREAD

**Issue by sonymaster** [networknt/json-schema-validator#987]
Hallo team,
after updating our jackson-databind library to version 2.16.2 the min-/maxLength properties in json schema file dosn't work anymore, because the method has been removed. The Jackson libraries are used by many other frameworks and we are not able to downgrade.
Are there any plans to migrate json-schema-validator to current jackson-databind version?

**Comment by stevehu** [comment]
Do you know any replacement methods? Or upgrade document link? Thanks.

**Comment by sonymaster** [comment]
Sorry! After researching the version where the method was removed, I couldn't find it. There was a classloader problem in our environment, so an old Jackson version was used. Also in the development environment the wrong version was always used.
I apologize again!
